import type { VideoProject } from '../schema';

const media = {
  financeSkyline: 'video-factory/media/wealthy-debt/finance-skyline.jpg',
  apartments: 'video-factory/media/wealthy-debt/apartments.jpg',
  charlotte: 'video-factory/media/wealthy-debt/charlotte.jpg',
  manhattan: 'video-factory/media/wealthy-debt/manhattan.jpg',
};

export const wealthyDebtProject: VideoProject = {
  id: 'wealthy-debt', title: 'Why wealthy people use debt differently', topic: 'Why wealthy people use debt differently.',
  description: `The Money Behind It explains why some wealthy people borrow even when they could pay cash, using story, wit, curiosity, and clear financial principles.\n\nEditorial style: story before lesson; conversational intelligence; restrained humor; recurring curiosity gaps; memorable payoff. Hook → mystery → story → reveal → explanation → twist → practical takeaway → final payoff.\n\nThis is educational, not individualized financial, legal, or tax advice. Leverage can magnify losses as well as gains. Whether borrowing is appropriate depends on cash flow, risk tolerance, and the quality of the underlying asset.`,
  aspectRatio: '16:9', fps: 30, width: 1920, height: 1080,
  youtubeTags: ['personal finance','debt','leverage','wealth','The Money Behind It','edutainment'],
  scenes: [
    { id:'hook', type:'image', durationInSeconds:11, kicker:'The Money Behind It', headline:'Debt has a terrible publicist.', body:'So why do people with plenty of money still borrow?', mediaUrl:media.manhattan, narration:`Debt has a terrible publicist. Most of us were taught to run from it. Meanwhile, some very wealthy people can buy something outright... and borrow anyway. Which sounds absurd. Until you follow the money.` },
    { id:'mystery', type:'image', durationInSeconds:12, kicker:'Here’s where it gets interesting', headline:'They may not be buying money. They’re buying options.', body:'The question is not simply “Do I owe money?” It is “What is my money doing while I owe it?”', mediaUrl:media.financeSkyline, narration:`Their question is often not, can I afford to pay cash? Of course they can. The question is, what happens to my cash if I do? Cash can invest, absorb surprises, or jump on the next opportunity. Once you spend it, its career options become... limited.` },
    { id:'two-kinds', type:'image', durationInSeconds:13, kicker:'Same word. Very different job.', headline:'Debt can finance consumption or an asset.', body:'Consumer debt usually finances something already consumed. Productive debt is tied to an asset, business, or opportunity expected to create value.', mediaUrl:media.apartments, narration:`A credit card balance from last summer's vacation and a loan on a cash-flowing property are both called debt. Technically true. Also technically unhelpful. One mostly sends money backward. The other is hired to help money move forward.` },
    { id:'bank-joke', type:'stat', durationInSeconds:10, kicker:'Banking has a sense of humor', headline:'The easier it is to prove you don’t need money...', statValue:'...the easier it can be to borrow it.', statLabel:'Assets, income and collateral change the conversation.', narration:`Banks have a strange sense of humor. The easier it is to prove you do not desperately need their money, the more interested they become in giving it to you. Assets, income, collateral and cash flow completely change the conversation.` },
    { id:'leverage', type:'image', durationInSeconds:13, kicker:'Now watch what happens', headline:'Keep the asset. Keep some cash. Add a loan.', body:'Borrowing against a productive asset can preserve ownership and liquidity instead of forcing a sale.', mediaUrl:media.charlotte, narration:`Suppose an owner needs cash. Selling an asset solves that problem, but it also sells the future upside. Borrowing against the asset may unlock cash while ownership stays put. Clever? Sometimes. You have also invited a lender to dinner, and they absolutely expect dessert.` },
    { id:'opportunity-cost', type:'chart', durationInSeconds:13, kicker:'The hidden calculation', headline:'Interest is only one side of the equation.', body:'The comparison is often interest paid versus what the retained cash or asset might produce, adjusted for risk.', chart:[{label:'Interest cost',value:38,note:'What borrowing costs'},{label:'Liquidity kept',value:64,note:'Cash remains available'},{label:'Asset upside',value:76,note:'Ownership remains, with risk'}], narration:`Here is the part people skip. The cost is not just the interest rate. There is opportunity cost too. What could the cash you kept do? What could the asset you did not sell become? The answer is not automatically borrow. The answer is: stop staring at one square and look at the whole board.` },
    { id:'tax', type:'image', durationInSeconds:12, kicker:'Another wrinkle', headline:'Selling and borrowing are not the same financial event.', body:'Selling an appreciated asset can create a taxable gain. Borrowing against an asset generally does not itself mean selling it.', mediaUrl:media.financeSkyline, narration:`Then taxes enter the room, because apparently money was getting dangerously easy. Selling an appreciated asset can create a taxable gain. Borrowing against it is a different event. Exact treatment depends on the facts, so this is where your tax professional finally gets to justify that lunch.` },
    { id:'twist', type:'quote', durationInSeconds:11, kicker:'The twist', headline:'Debt is not automatically sophisticated.', body:'Bad debt wearing an expensive suit is still bad debt.', quoteAttribution:'The Money Behind It', narration:`Now the important part. Do not confuse wealthy people using leverage with leverage making people wealthy. Bad debt wearing an expensive suit is still bad debt. A fancy strategy can still produce an extremely unfancy loss.` },
    { id:'risk', type:'image', durationInSeconds:12, kicker:'The bill still arrives', headline:'Leverage magnifies mistakes too.', body:'If the asset falls, income disappears, or rates change, the debt remains.', mediaUrl:media.apartments, narration:`Leverage is delightful when the math behaves. When it does not, mathematics gets very personal, very quickly. If the asset drops or cash flow disappears, the lender does not grade on effort. The payment still shows up, cheerful as ever.` },
    { id:'takeaway', type:'image', durationInSeconds:12, kicker:'The useful question', headline:'Don’t ask whether debt is good or bad.', body:'Ask what it buys, what it preserves, what it costs, and what happens if the plan fails.', mediaUrl:media.manhattan, narration:`So forget asking whether debt is good or bad. Ask four better questions. What does it buy? What does it preserve? What does it cost? And what happens when the beautiful spreadsheet meets an ugly Tuesday? Those questions separate leverage from wishful thinking.` },
    { id:'sources', type:'citation', durationInSeconds:9, kicker:'Evidence, not folklore', headline:'The ideas are hiding in plain sight.', citations:[{label:'Household balance sheets',detail:'Federal Reserve Survey of Consumer Finances — debt exists alongside assets.'},{label:'Capital structure',detail:'Core finance principle — compare cost of capital, liquidity, cash flow and risk.'},{label:'Tax treatment',detail:'IRS guidance on capital gains and interest — fact-specific; consult a professional.'}], narration:`None of this requires a secret billionaire handbook hidden behind a painting. The principles are sitting in public data, tax rules and basic finance. The difference is how the pieces are used together.` },
    { id:'outro', type:'outro', durationInSeconds:10, kicker:'The Money Behind It', headline:'The wealthy don’t necessarily hate debt. They give it a job.', body:'And if the debt has no productive job, that may be the most important answer of all.', narration:`The lesson is not to copy somebody else's debt. It is to know the job every dollar and every liability is supposed to do. If the debt has no job, maybe fire it. And that... is the money behind it.` },
  ],
};
