import type { IndustryPack } from '@/lib/portal-universal/industry-pack';
import { AMANDA_PORTAL_PACK_ID } from '@/lib/amanda-catherine/config';

export const AMANDA_CATHERINE_PACK: IndustryPack = {
  id: AMANDA_PORTAL_PACK_ID,
  version: '1.0.0',
  title: 'Amanda Catherine Member Experience',
  description:
    'Role-aware home for clients, students, practitioners, members, media guests, volunteers, partners, staff, and administrators.',
  presentation: 'workspace',
  suggestedModuleIds: [
    'dashboard',
    'member',
    'training',
    'calendar',
    'events',
    'documents',
    'messaging',
    'resources',
    'connect',
    'intake',
    'applications',
    'people',
    'reports',
    'billing',
    'settings',
  ],
  useClientExperienceChrome: false,
  nav: [
    {
      id: 'home',
      universalCapabilityId: 'home',
      label: 'Home',
      order: 10,
      preferredModuleId: 'member',
    },
    {
      id: 'my-path',
      universalCapabilityId: 'programs',
      label: 'My Path',
      order: 20,
      preferredModuleId: 'member',
    },
    {
      id: 'learning',
      universalCapabilityId: 'resources',
      label: 'Courses & Training',
      order: 30,
      preferredModuleId: 'training',
    },
    {
      id: 'calendar',
      universalCapabilityId: 'calendar',
      label: 'Appointments & Calendar',
      order: 40,
      preferredModuleId: 'calendar',
    },
    {
      id: 'events',
      universalCapabilityId: 'calendar',
      label: 'Events & Registration',
      order: 45,
      preferredModuleId: 'events',
    },
    {
      id: 'documents',
      universalCapabilityId: 'documents',
      label: 'Files & Media',
      order: 50,
      preferredModuleId: 'documents',
    },
    {
      id: 'messages',
      universalCapabilityId: 'messages',
      label: 'Messages',
      order: 60,
      preferredModuleId: 'messaging',
    },
    {
      id: 'resources',
      universalCapabilityId: 'resources',
      label: 'Resources',
      order: 70,
      preferredModuleId: 'resources',
    },
    {
      id: 'connections',
      universalCapabilityId: 'programs',
      label: 'Connections & Opportunities',
      order: 80,
      preferredModuleId: 'member',
    },
    {
      id: 'directory',
      universalCapabilityId: 'people',
      label: 'People & Directory',
      order: 85,
      preferredModuleId: 'people',
      minRole: 'staff',
    },
    {
      id: 'intake',
      universalCapabilityId: 'programs',
      label: 'Forms',
      order: 90,
      preferredModuleId: 'intake',
    },
    {
      id: 'applications',
      universalCapabilityId: 'programs',
      label: 'Applications & Enrollments',
      order: 100,
      preferredModuleId: 'applications',
      minRole: 'staff',
    },
    {
      id: 'settings',
      universalCapabilityId: 'messages',
      label: 'Preferences & Notifications',
      order: 105,
      preferredModuleId: 'settings',
    },
    {
      id: 'reports',
      universalCapabilityId: 'resources',
      label: 'Reports',
      order: 110,
      preferredModuleId: 'reports',
      minRole: 'staff',
    },
    {
      id: 'billing',
      universalCapabilityId: 'payments',
      label: 'Payments',
      order: 120,
      preferredModuleId: 'billing',
    },
  ],
  branding: {
    themeId: 'amanda-editorial',
    workspaceName: 'Studio Lab · By Amanda Catherine',
    brandName: 'AesthetiKine',
    logoSrc: '/amanda-catherine/aesthetikine-mark.svg',
    terminology: {
      members: 'Members',
      home: 'Home',
      startPrompt: 'Continue your path',
      focus: 'Your next step',
      attention: 'Needs your attention',
      start: 'Continue',
    },
  },
  extensions: {
    people: { enabled: false },
    tasks: { enabled: false },
    notifications: { enabled: false },
    formSchemaRefs: [
      {
        id: 'lifeline-guest-information',
        universalCapabilityId: 'programs',
        title: 'LIFELINE Featured Guest Information',
        schemaRef: 'amanda://forms/lifeline-guest-information/v1',
      },
      {
        id: 'lifeline-media-consent',
        universalCapabilityId: 'documents',
        title: 'LIFELINE Photography and Media Consent',
        schemaRef: 'amanda://forms/lifeline-media-consent/v1',
      },
      {
        id: 'injection-qualification',
        universalCapabilityId: 'programs',
        title: 'Injection Training Qualification Confirmation',
        schemaRef: 'amanda://forms/injection-qualification/v1',
      },
    ],
    workflowRefs: [
      {
        id: 'lifeline-guest-delivery',
        purpose: 'Move a LIFELINE guest from intake through interview and media delivery.',
        providerHint: 'pulse',
        envKeyOrSlug: 'amanda-lifeline-guest-delivery',
      },
      {
        id: 'entrepreneurial-artist-fixed-release',
        purpose: 'Release six Entrepreneurial Artist lessons per week on fixed days.',
        providerHint: 'cron',
        envKeyOrSlug: 'amanda-entrepreneurial-artist-release',
      },
      {
        id: 'portal-welcome-email',
        purpose: 'Send the welcome email matching the member audience after enrollment.',
        providerHint: 'pulse',
        envKeyOrSlug: 'amanda-portal-welcome',
      },
      {
        id: 'role-aware-application-onboarding',
        purpose: 'Start the correct onboarding sequence after an Amanda application or intake is submitted.',
        providerHint: 'pulse',
        envKeyOrSlug: 'amanda-role-aware-onboarding',
      },
      {
        id: 'incomplete-application-follow-up',
        purpose: 'Remind applicants when required answers or documents are incomplete.',
        providerHint: 'cron',
        envKeyOrSlug: 'amanda-incomplete-application-follow-up',
      },
      {
        id: 'appointment-confirmation-and-reminders',
        purpose: 'Send booking confirmation plus 24-hour and 2-hour appointment reminders.',
        providerHint: 'pulse',
        envKeyOrSlug: 'amanda-appointment-reminders',
      },
      {
        id: 'appointment-preparation-and-aftercare',
        purpose: 'Send service-specific preparation before an appointment and aftercare afterward.',
        providerHint: 'pulse',
        envKeyOrSlug: 'amanda-appointment-care',
      },
      {
        id: 'event-registration-communication',
        purpose: 'Confirm event registration and send event reminders and updates.',
        providerHint: 'pulse',
        envKeyOrSlug: 'amanda-event-registration-communication',
      },
    ],
    nba: {
      providerId: 'amanda-path',
      staticHeadline: 'Continue the next step in your Amanda Catherine experience.',
    },
  },
};
