import type { IndustryPack } from '@/lib/portal-universal/industry-pack';

/**
 * Built-in executive workspace pack — labels align with experience-registry displayLabel.
 * legacyPlatformClientId: ea
 */
export const EA_EXECUTIVE_PACK: IndustryPack = {
  id: 'ea-executive',
  version: '1.0.0',
  title: 'EA Executive Workspace',
  description: 'Default entitlement-driven executive portal navigation.',
  presentation: 'workspace',
  legacyPlatformClientId: 'ea',
  suggestedModuleIds: [
    'dashboard',
    'pulse',
    'simplifi',
    'amplifi',
    'connect',
    'update-hub',
    'documents',
    'messaging',
    'events',
    'resources',
    'training',
    'ask',
    'billing',
    'ctp',
    'member',
  ],
  useClientExperienceChrome: false,
  nav: [
    {
      id: 'home',
      universalCapabilityId: 'home',
      label: 'Dashboard',
      order: 10,
      preferredModuleId: 'dashboard',
    },
    {
      id: 'progress',
      universalCapabilityId: 'progress',
      label: 'Pulse',
      order: 20,
      preferredModuleId: 'pulse',
    },
    {
      id: 'programs-simplifi',
      universalCapabilityId: 'programs',
      label: 'Simplifi',
      order: 30,
      preferredModuleId: 'simplifi',
    },
    {
      id: 'programs-amplifi',
      universalCapabilityId: 'programs',
      label: 'Amplifi',
      order: 40,
      preferredModuleId: 'amplifi',
    },
    {
      id: 'programs-connect',
      universalCapabilityId: 'programs',
      label: 'Connect',
      order: 50,
      preferredModuleId: 'connect',
    },
    {
      id: 'messages-updates',
      universalCapabilityId: 'messages',
      label: 'Project Updates',
      order: 60,
      preferredModuleId: 'update-hub',
    },
    {
      id: 'documents',
      universalCapabilityId: 'documents',
      label: 'Document Hub™',
      order: 70,
      preferredModuleId: 'documents',
    },
    {
      id: 'messages-contact',
      universalCapabilityId: 'messages',
      label: 'Contact',
      order: 80,
      preferredModuleId: 'messaging',
    },
    {
      id: 'calendar',
      universalCapabilityId: 'calendar',
      label: 'Event Hub™',
      order: 90,
      preferredModuleId: 'events',
    },
    {
      id: 'resources-lib',
      universalCapabilityId: 'resources',
      label: 'Resource library',
      order: 100,
      preferredModuleId: 'resources',
    },
    {
      id: 'resources-training',
      universalCapabilityId: 'resources',
      label: 'Training Hub™',
      order: 110,
      preferredModuleId: 'training',
    },
    {
      id: 'resources-ask',
      universalCapabilityId: 'resources',
      label: 'Guide™',
      order: 120,
      preferredModuleId: 'ask',
    },
    {
      id: 'programs-ctp',
      universalCapabilityId: 'programs',
      label: 'Consider the Possibilities',
      order: 130,
      preferredModuleId: 'ctp',
    },
    {
      id: 'programs-member',
      universalCapabilityId: 'programs',
      label: 'Member',
      order: 140,
      preferredModuleId: 'member',
    },
    {
      id: 'payments',
      universalCapabilityId: 'payments',
      label: 'Billing',
      order: 150,
      preferredModuleId: 'billing',
      minRole: 'owner',
    },
    {
      id: 'people',
      universalCapabilityId: 'people',
      label: 'People',
      order: 900,
      visibility: { kind: 'never' },
    },
    {
      id: 'tasks',
      universalCapabilityId: 'tasks',
      label: 'Tasks',
      order: 910,
      visibility: { kind: 'never' },
    },
  ],
  branding: {
    terminology: {
      members: 'Clients',
      home: 'Dashboard',
    },
  },
  extensions: {
    people: { enabled: false },
    tasks: { enabled: false },
    notifications: { enabled: false },
    nba: { providerId: 'none' },
  },
};
