import { getAmandaSiteContent } from '@/lib/amanda-catherine/site-content';

export const dynamic = 'force-dynamic';

function HeroMedia({ imageUrl, videoUrl }: { imageUrl: string; videoUrl: string }) {
  if (videoUrl) return <video className="hero-media" src={videoUrl} poster={imageUrl || undefined} autoPlay muted loop playsInline preload="metadata" />;
  if (imageUrl) return <img className="hero-media" src={imageUrl} alt="Amanda Catherine" />;
  return null;
}

export default async function AmandaCatherinePublicPage() {
  const site = await getAmandaSiteContent();
  return (
    <div className="ac" id="top">
      <style dangerouslySetInnerHTML={{ __html: `
:root{--ink:#17211c;--cream:#f6f0e6;--paper:#fffdf8;--gold:#b48a49;--line:#ddd7cb;--muted:#667069}.ac{margin:-8px;font:16px/1.6 Arial,sans-serif;color:var(--ink);background:var(--paper)}.ac *{box-sizing:border-box}.ac h1,.ac h2,.ac h3{font-family:Georgia,serif;font-weight:500;line-height:1.06;margin:0 0 18px}.ac a{color:inherit}.wrap{width:min(1120px,92vw);margin:auto}.ac nav{position:sticky;top:0;z-index:9;background:#17211cf5;color:#fff}.bar{min-height:70px;display:flex;align-items:center;justify-content:space-between}.brand{font:24px Georgia,serif}.links{display:flex;gap:20px;font-size:12px;text-transform:uppercase;letter-spacing:.1em}.hero{position:relative;min-height:72vh;display:grid;align-items:center;color:#fff;overflow:hidden;background:radial-gradient(circle at 80% 20%,#748776 0,#455747 26%,#17211c 68%)}.hero-media{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.48}.hero:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,#17211cd9,#17211c40)}.hero .wrap{position:relative;z-index:2}.hero h1{font-size:clamp(54px,8vw,100px);white-space:pre-line}.hero p{max-width:700px;font-size:21px;color:#ffffffd8}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.2em;font-weight:700;color:var(--gold);margin-bottom:18px}.btn{display:inline-block;padding:13px 19px;margin:8px 8px 0 0;border:1px solid currentColor;text-decoration:none;text-transform:uppercase;letter-spacing:.09em;font-size:11px;font-weight:bold}.fill{background:var(--gold);border-color:var(--gold);color:#fff}.ac section{padding:82px 0}.intro{text-align:center;background:var(--cream)}.title,.intro h2{font-size:clamp(40px,5vw,66px)}.intro p{max-width:780px;margin:20px auto;color:var(--muted);font-size:19px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:56px}.panel{padding:30px;border:1px solid var(--line);background:#fff}.facts,.programs,.cards{display:grid;gap:14px}.facts{grid-template-columns:1fr 1fr}.fact,.program{padding:16px;border-top:1px solid var(--line)}.fact b,.program span{color:var(--gold)}.dark{background:var(--ink);color:#fff}.cards{grid-template-columns:repeat(3,1fr)}.card{padding:28px;border:1px solid #ffffff33}.learn{background:#eef1eb}.program{display:grid;grid-template-columns:1fr auto;gap:8px}.program small{grid-column:1/-1;color:var(--muted)}.create{background:var(--cream)}.section-media{width:100%;max-height:520px;object-fit:cover;margin-top:24px}footer{background:var(--ink);color:#fff;padding:42px 0}@media(max-width:760px){.links{display:none}.grid2,.cards,.facts{grid-template-columns:1fr}.ac section{padding:62px 0}}
      ` }} />
      <nav><div className="wrap bar"><div className="brand">Amanda Catherine</div><div className="links"><a href="#restore">Restore</a><a href="#learn">Learn</a><a href="#create">Create</a><a href="#contact">Contact</a></div></div></nav>
      <header className="hero"><HeroMedia imageUrl={site.hero.imageUrl} videoUrl={site.hero.videoUrl} /><div className="wrap"><div className="eyebrow">{site.hero.eyebrow}</div><h1>{site.hero.title}</h1><p>{site.hero.subtitle}</p><a className="btn fill" href={site.hero.primaryHref}>{site.hero.primaryLabel}</a><a className="btn" href={site.hero.secondaryHref}>{site.hero.secondaryLabel}</a></div></header>
      <section className="intro"><div className="wrap"><div className="eyebrow">{site.intro.eyebrow}</div><h2>{site.intro.title}</h2><p>{site.intro.body}</p></div></section>
      <section id="restore"><div className="wrap grid2"><div><div className="eyebrow">{site.restore.eyebrow}</div><h2 className="title">{site.restore.title}</h2><p>{site.restore.body}</p><a className="btn fill" href={site.restore.bookingUrl}>Book an appointment</a>{site.restore.imageUrl ? <img className="section-media" src={site.restore.imageUrl} alt="AesthetiKine" /> : null}</div><div className="panel"><h3>{site.restore.clinicName}</h3><p>{site.restore.clinicSubtitle}</p><div className="facts"><div className="fact"><b>Clinic</b><br />{site.restore.address}</div><div className="fact"><b>Phone</b><br />{site.restore.phone}</div><div className="fact"><b>Email</b><br />{site.restore.email}</div><div className="fact"><b>Booking</b><br />Jane App</div></div></div></div></section>
      <section className="dark"><div className="wrap"><div className="eyebrow">{site.pathways.eyebrow}</div><h2 className="title">{site.pathways.title}</h2><div className="cards"><div className="card"><h3>Restore</h3><p>{site.pathways.restoreBody}</p></div><div className="card"><h3>Learn</h3><p>{site.pathways.learnBody}</p></div><div className="card"><h3>Create</h3><p>{site.pathways.createBody}</p></div></div></div></section>
      <section className="learn" id="learn"><div className="wrap grid2"><div><div className="eyebrow">{site.learn.eyebrow}</div><h2 className="title">{site.learn.title}</h2><p>{site.learn.body}</p><a className="btn fill" href={site.learn.ctaHref}>{site.learn.ctaLabel}</a>{site.learn.imageUrl ? <img className="section-media" src={site.learn.imageUrl} alt="Amanda Catherine training" /> : null}</div><div className="programs">{site.learn.programs.map((p) => <div className="program" key={p.title}><b>{p.title}</b><span>{p.price}</span>{p.description ? <small>{p.description}</small> : null}</div>)}</div></div></section>
      <section className="create" id="create"><div className="wrap"><div className="eyebrow">{site.create.eyebrow}</div><h2 className="title">{site.create.title}</h2>{site.create.body ? <p>{site.create.body}</p> : null}<div className="cards">{site.create.cards.map((card) => <div className="panel" key={card.title}><h3>{card.title}</h3><p>{card.body}</p></div>)}</div>{site.create.imageUrl ? <img className="section-media" src={site.create.imageUrl} alt="Amanda Catherine creative work" /> : null}</div></section>
      <section id="contact"><div className="wrap grid2"><div><div className="eyebrow">{site.contact.eyebrow}</div><h2 className="title">{site.contact.title}</h2><p>{site.contact.body}</p><a className="btn fill" href={`mailto:${site.contact.email}`}>Email Amanda</a><a className="btn" href={`tel:${site.contact.phone.replace(/[^+\d]/g,'')}`}>Call {site.contact.phone}</a></div><div className="panel"><b>Clinic</b><p>{site.contact.address}</p><b>Hours</b><p>{site.contact.hours}</p><b>Course enrollment</b><p><a href={site.contact.enrollUrl}>Amanda Catherine enrollment portal</a></p></div></div></section>
      <footer><div className="wrap"><b>{site.footer.tagline}</b><br />{site.footer.note}<br /><br />© 2026 Amanda Catherine</div></footer>
    </div>
  );
}
