"use client";

import { createContext, useContext, useCallback, useEffect, useMemo, useRef, useState, type ReactNode, type FormEvent } from "react";
import { z } from "zod";

export const activityTypes = ["Academics", "Training", "Opportunity", "Community"] as const;
export type ActivityType = typeof activityTypes[number];
const stages = ["Inbound", "In Discussion", "Contracted", "Completed"] as const;
const recordSchema = z.object({
  id: z.string().min(1), title: z.string().min(1).max(160), type: z.enum(activityTypes),
  start: z.string().datetime(), end: z.string().datetime(), link: z.string().max(100),
  earnings: z.number().nonnegative().max(100000000), kids: z.number().int().nonnegative().max(100000),
  purpose: z.enum(["activity", "study", "training", "community", "opportunity"]),
  stage: z.enum(stages), completed: z.boolean(),
}).refine(record => new Date(record.end) > new Date(record.start));
export type Activity = z.infer<typeof recordSchema>;
type Draft = Partial<Activity> & { date?: string };
const storageKey = "tb3.hq.v2.1.preview.records";
export const colors: Record<ActivityType, string> = {Academics: "#3B82F6", Training: "#EF4444", Opportunity: "#111111", Community: "#6B7280"};
const moduleLinks: Record<ActivityType, string> = {Academics: "Academic Tutor", Training: "Training Weekly Plan", Opportunity: "Opportunity card", Community: "Community Event"};
function localDay(date: Date) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`; }
function localTime(iso: string) { const d=new Date(iso);return `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`; }
export function eventTime(event: Activity) { return new Date(event.start).toLocaleString(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}); }

export function HqDialog({ id, title, children, onClose, fullScreen=false }: {id:string;title:string;children:ReactNode;onClose:()=>void;fullScreen?:boolean}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>{dialog?.close();};},[]);
  return <dialog ref={ref} id={id} aria-labelledby={id+"-title"} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} className={"fixed z-[1000] m-auto w-[calc(100%-32px)] max-w-[900px] overflow-y-auto rounded-2xl border-0 bg-white p-5 text-[#111] shadow-2xl backdrop:bg-black/80 "+(fullScreen?"h-[100dvh] w-screen max-w-none rounded-none":"max-h-[90dvh]")}>
    <header className="mb-4 flex items-start justify-between gap-4"><h2 id={id+"-title"} className="text-xl font-black">{title}</h2><button type="button" onClick={onClose} aria-label="Close" className="rounded-lg border border-black/20 px-3 py-2 text-sm">Close ×</button></header>{children}
  </dialog>;
}

type Workspace = {
  records: Activity[]; calendar: Activity[]; upcoming: Activity[]; ready: boolean; notice:string;
  module: string; setModule:(name:string)=>void; openActivity:(draft?:Draft)=>void;
  remove:(id:string)=>void; changeStage:(id:string,stage:Activity["stage"])=>void;
  openEva:()=>void; openAssets:(category?:string)=>void; setAssetOpener:(opener:((category:string)=>void)|null)=>void;
};
const Context=createContext<Workspace|null>(null);
export function useHq(){const v=useContext(Context);if(!v)throw new Error("HQ workspace missing");return v;}

export function HqWorkspaceProvider({children}:{children:ReactNode}){
  const [records,setRecords]=useState<Activity[]>([]),[ready,setReady]=useState(false),[notice,setNotice]=useState("");
  const [now,setNow]=useState(()=>Date.now());
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
  const [draft,setDraft]=useState<Draft|null>(null),[module,setModule]=useState("Home"),[evaOpen,setEvaOpen]=useState(false);
  const assetOpener=useRef<((category:string)=>void)|null>(null);
  useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;try{const stored=localStorage.getItem(storageKey);if(stored){const parsed=z.array(recordSchema).max(1000).safeParse(JSON.parse(stored));if(parsed.success)setRecords(parsed.data);else setNotice("Saved preview records could not be read. No records were loaded.");}}catch{setNotice("Browser storage is unavailable. New records will last only for this visit.");}setReady(true);});return()=>{active=false;};},[]);
  useEffect(()=>{if(ready){try{localStorage.setItem(storageKey,JSON.stringify(records));}catch{queueMicrotask(()=>setNotice("Browser storage is unavailable. New records will last only for this visit."));}}},[records,ready]);
  const calendar=useMemo(()=>records.filter(r=>r.purpose!=="opportunity"||r.stage==="Contracted"||r.stage==="Completed").sort((a,b)=>a.start.localeCompare(b.start)),[records]);
  const upcoming=calendar.filter(r=>!r.completed&&new Date(r.start).getTime()>=now).slice(0,3);
  function save(value:Activity){setRecords(current=>[...current.filter(r=>r.id!==value.id),value]);setDraft(null);}
  function openAssets(category="All"){assetOpener.current?.(category);document.getElementById("media-library")?.scrollIntoView({behavior:"smooth"});setModule("Media Library");}
  const setAssetOpener=useCallback((opener:((category:string)=>void)|null)=>{assetOpener.current=opener;},[]);
  const value:Workspace={records,calendar,upcoming,ready,notice,module,setModule,openActivity:(next={})=>setDraft(next),remove:id=>setRecords(current=>current.filter(r=>r.id!==id)),changeStage:(id,stage)=>setRecords(current=>current.map(r=>r.id===id?{...r,stage,completed:stage==="Completed"}:r)),openEva:()=>{if(window.innerWidth>=1280)document.getElementById("desktop-eva-chat")?.focus();else setEvaOpen(true);},openAssets,setAssetOpener};
  return <Context.Provider value={value}>{children}{draft&&<ActivityForm draft={draft} onSave={save} onClose={()=>setDraft(null)} onDelete={draft.id?()=>{value.remove(draft.id!);setDraft(null);}:undefined}/>} {evaOpen&&<HqDialog id="eva-mobile-chat" title="EVA · Your AI Assistant" fullScreen onClose={()=>setEvaOpen(false)}><EvaContent prefix="mobile"/></HqDialog>}</Context.Provider>;
}

function ActivityForm({draft,onSave,onClose,onDelete}:{draft:Draft;onSave:(value:Activity)=>void;onClose:()=>void;onDelete?:()=>void}){
  const [type,setType]=useState<ActivityType>(draft.type||"Training"),[error,setError]=useState("");
  const date=draft.date||localDay(draft.start?new Date(draft.start):new Date());
  const purpose=draft.purpose||"activity";
  const title=draft.id?"Edit Activity":purpose==="study"?"Log Study Hall":purpose==="training"?"Log Workout":purpose==="community"?"Log Community Clinic":purpose==="opportunity"?"Track Opportunity":"Add Activity";
  const input="mt-1 block w-full rounded-lg border border-black/20 bg-white px-3 py-2 text-sm text-black";
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const start=new Date(`${f.get("date")}T${f.get("start")}`),end=new Date(`${f.get("date")}T${f.get("end")}`);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start){setError("End time must be later than start time on the selected date.");return;}
    const value=recordSchema.safeParse({id:draft.id||crypto.randomUUID(),title:String(f.get("title")||"").trim(),type,start:start.toISOString(),end:end.toISOString(),link:String(f.get("link")||moduleLinks[type]),earnings:type==="Opportunity"?Number(f.get("earnings")||0):0,kids:type==="Community"?Number(f.get("kids")||0):0,purpose,stage:String(f.get("stage")||draft.stage||"Inbound"),completed:f.get("completed")==="on"||f.get("stage")==="Completed"});if(!value.success){setError("Check the title, times and amounts before saving.");return;}onSave(value.data);}
  return <HqDialog id="add-activity-modal" title={title} onClose={onClose}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">
    <p className="text-xs text-black/60 sm:col-span-2">Preview records are saved in this browser. Shared account and booking sync follows approval.</p>
    <label className="text-xs font-bold">Type<select name="type" disabled={purpose!=="activity"} value={type} onChange={e=>setType(e.target.value as ActivityType)} className={input}>{activityTypes.map(t=><option key={t}>{t}</option>)}</select></label>
    <label className="text-xs font-bold">Date<input name="date" type="date" required defaultValue={date} className={input}/></label>
    <label className="text-xs font-bold sm:col-span-2">Title<input name="title" maxLength={160} required defaultValue={draft.title||""} className={input}/></label>
    <label className="text-xs font-bold">Start time<input name="start" type="time" required defaultValue={draft.start?localTime(draft.start):"09:00"} className={input}/></label>
    <label className="text-xs font-bold">End time<input name="end" type="time" required defaultValue={draft.end?localTime(draft.end):"10:00"} className={input}/></label>
    <label className="text-xs font-bold sm:col-span-2">Link to module<select name="link" key={type} defaultValue={draft.link||moduleLinks[type]} className={input}>{Object.values(moduleLinks).map(l=><option key={l}>{l}</option>)}</select></label>
    {type==="Opportunity"&&<><label className="text-xs font-bold">Earnings ($)<input name="earnings" type="number" min="0" max="100000000" step="0.01" defaultValue={draft.earnings||0} className={input}/></label>{purpose==="opportunity"&&<label className="text-xs font-bold">Stage<select name="stage" defaultValue={draft.stage||"Inbound"} className={input}>{stages.map(s=><option key={s}>{s}</option>)}</select></label>}</>}
    {type==="Community"&&<label className="text-xs font-bold">Kids impacted<input name="kids" type="number" min="0" max="100000" step="1" defaultValue={draft.kids||0} className={input}/></label>}
    <label className="flex items-center gap-2 text-sm sm:col-span-2"><input name="completed" type="checkbox" defaultChecked={draft.completed||["study","training","community"].includes(purpose)}/>Completed activity</label>
    {error&&<p role="alert" className="text-sm text-red-700 sm:col-span-2">{error}</p>}
    <div className="flex flex-wrap gap-3 sm:col-span-2"><button type="submit" className="rounded-lg bg-[#C41E3A] px-5 py-3 text-xs font-bold text-white">Save Activity</button>{onDelete&&<button type="button" onClick={onDelete} className="rounded-lg border border-red-700 px-4 py-3 text-xs font-bold text-red-700">Delete Activity</button>}</div>
  </form></HqDialog>;
}

export function ModuleActions({module}:{module:ActivityType|"Brand"}){const h=useHq();const category=module==="Training"?"Athlete":module==="Opportunity"?"Future":module;
  return <div className="mt-4 flex flex-wrap gap-2">{module!=="Brand"&&<button type="button" onClick={()=>h.openActivity({type:module,purpose:module==="Academics"?"study":module==="Training"?"training":module==="Community"?"community":"opportunity"})} className="rounded-lg bg-[#C41E3A] px-4 py-2 text-xs font-bold text-white">{module==="Academics"?"Log Study Hall":module==="Training"?"Log Workout":module==="Community"?"Log Community Clinic":"Track Opportunity"}</button>}<button type="button" onClick={()=>h.openAssets(category)} className="rounded-lg border border-white/30 px-4 py-2 text-xs font-bold">View Approved Assets</button></div>;
}

export function ProactiveEva({module}:{module:ActivityType}){const h=useHq();const rows=h.records.filter(r=>r.type===module);const text=module==="Academics"?`${rows.filter(r=>r.purpose==="study").length} study sessions recorded. Plan the next session?`:module==="Training"?`${rows.filter(r=>r.completed).length} completed activities recorded. Plan recovery?`:module==="Opportunity"?`${rows.filter(r=>r.purpose==="opportunity"&&r.stage!=="Completed").length} active opportunities. Review partnership criteria before contracting.`:`${rows.filter(r=>r.completed).reduce((n,r)=>n+r.kids,0)} kids impacted in recorded activities. Plan a clinic?`;
  return <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#C41E3A]/30 bg-[#C41E3A]/5 p-4"><p className="max-w-xl text-xs leading-5"><span className="mr-2 font-black text-[#C41E3A]">EVA</span>{text}</p><button type="button" onClick={()=>h.openActivity({type:module})} className="text-xs font-bold underline">Add to Calendar →</button></div>;
}

export function HqFocus(){const h=useHq();const study=h.records.filter(r=>r.purpose==="study"&&r.completed),workouts=h.records.filter(r=>r.purpose==="training"&&r.completed),opps=h.records.filter(r=>r.purpose==="opportunity"),clinics=h.records.filter(r=>r.purpose==="community"&&r.completed);const hours=study.reduce((n,r)=>n+(new Date(r.end).getTime()-new Date(r.start).getTime())/3600000,0);
  const cards=[{id:"training",title:"TRAINING",status:workouts.length?`${workouts.length} Logged`:"No records yet",detail:"Completed workouts",href:"training-module"},{id:"academics",title:"ACADEMICS",status:study.length?`${hours.toFixed(1)} Hours`:"No records yet",detail:"Study hall time recorded",href:"academics-module"},{id:"nil",title:"NIL / BRAND",status:`${opps.filter(r=>r.stage!=="Completed").length} Active`,detail:`${opps.filter(r=>r.stage==="In Discussion").length} In Discussion · ${opps.filter(r=>r.stage==="Contracted").length} Contracted`,href:"opportunities-module"},{id:"growth",title:"PERSONAL GROWTH",status:"Different On Purpose",detail:`${clinics.length} clinics · ${clinics.reduce((n,r)=>n+r.kids,0)} kids recorded`,href:"community-module"}];
  return <section id="my-focus" className="mt-6 rounded-2xl border border-white/10 bg-[#111] p-5 sm:p-7"><h2 className="text-xl font-black">MY FOCUS</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{cards.map(c=><article id={"focus-"+c.id} key={c.id} className="rounded-xl border border-white/10 bg-white/[0.03] p-4"><h3 className="text-xs font-bold tracking-wider">{c.title}</h3><p className="mt-3 font-semibold text-[#C41E3A]">{c.status}</p><p className="mt-1 text-xs text-white/60">{c.detail}</p><a href={"#"+c.href} className="mt-3 inline-block text-xs underline">View {c.title.toLowerCase()} →</a></article>)}</div></section>;
}
export function Upcoming(){const h=useHq();return <section id="upcoming" className="mt-6 rounded-2xl border border-white/10 bg-[#111] p-5 sm:p-7"><div className="flex justify-between"><h2 className="text-xl font-black">UPCOMING</h2><a href="#calendar-module" className="text-xs underline">View All →</a></div>{h.upcoming.length?<ul className="mt-4 space-y-3">{h.upcoming.map(r=><li key={r.id} className="flex items-center gap-3 rounded-xl bg-[#1A1A1A] p-4"><span aria-hidden="true" className="h-3 w-3 shrink-0 rounded-full border border-white/30" style={{background:colors[r.type]}}/><button type="button" className="min-w-0 text-left" onClick={()=>h.openActivity(r)}><p className="break-words text-sm font-bold">{r.title}</p><p className="mt-1 text-xs text-white/60">{eventTime(r)} · {r.type}</p></button></li>)}</ul>:<p className="mt-4 text-sm text-white/60">No events scheduled - Add activity</p>}<button type="button" onClick={()=>h.openActivity()} className="mt-4 rounded-lg bg-[#C41E3A] px-4 py-2 text-xs font-bold">Add Activity</button></section>}
export function OpportunitySummary(){const h=useHq();return <section id="home-opportunities" className="mt-6 rounded-2xl border border-white/10 bg-[#111] p-5 sm:p-7"><div className="flex justify-between"><h2 className="text-xl font-black">OPPORTUNITIES</h2><a href="#opportunity-pipeline" className="text-xs underline">View All →</a></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{stages.slice(0,3).map(stage=><article key={stage} className="rounded-xl bg-[#1A1A1A] p-4"><h3 className="text-xs font-bold uppercase">{stage}</h3><p className="mt-3 text-3xl font-black">{h.records.filter(r=>r.purpose==="opportunity"&&r.stage===stage).length}</p></article>)}</div><p className="mt-4 text-xs text-white/60">Public booking inquiries will create cards here after Phase 2 connection.</p></section>}
export function OpportunityPipeline(){const h=useHq(),opps=h.records.filter(r=>r.purpose==="opportunity");return <article id="opportunity-pipeline" className="rounded-2xl bg-[#1A1A1A] p-5 lg:col-span-2"><h3 className="font-bold">OPPORTUNITY PIPELINE</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{stages.map(stage=><div key={stage} className="rounded-xl border border-white/10 p-4"><h4 className="text-xs font-bold">{stage}</h4>{opps.filter(r=>r.stage===stage).map(r=><div key={r.id} className="mt-3 rounded-lg bg-white/5 p-3"><button type="button" onClick={()=>h.openActivity(r)} className="w-full break-words text-left text-xs font-bold">{r.title}</button><p className="mt-2 text-[10px] text-white/60">{eventTime(r)}</p><label className="mt-2 block text-[10px] text-white/60">Stage<select value={r.stage} aria-label={"Stage for "+r.title} onChange={e=>h.changeStage(r.id,e.target.value as Activity["stage"])} className="mt-1 w-full rounded border border-white/20 bg-black p-2 text-xs text-white">{stages.map(s=><option key={s}>{s}</option>)}</select></label><p className="mt-2 text-[10px] text-white/60">{r.stage==="Contracted"?"Linked calendar hold":r.stage==="Completed"?"Completed":"No calendar hold yet"}</p></div>)}{!opps.some(r=>r.stage===stage)&&<p className="mt-4 text-xs text-white/50">No opportunities</p>}</div>)}</div><ModuleActions module="Opportunity"/></article>}
export function EarningsValue(){const {records}=useHq();const opps=records.filter(r=>r.purpose==="opportunity");return <><p className="mt-3 text-2xl font-black">${opps.filter(r=>r.stage==="Completed").reduce((n,r)=>n+r.earnings,0).toLocaleString()} Tracked</p><p className="mt-1 text-xs text-white/60">{opps.length} Opportunities</p></>}

export function CalendarModule(){const h=useHq();const [view,setView]=useState<"Month"|"Week"|"Day">("Month"),[cursor,setCursor]=useState(()=>new Date());
  const start=new Date(cursor.getFullYear(),cursor.getMonth(),view==="Month"?1:cursor.getDate());if(view==="Month")start.setDate(start.getDate()-((start.getDay()+6)%7));if(view==="Week")start.setDate(start.getDate()-((start.getDay()+6)%7));
  const days=Array.from({length:view==="Month"?42:view==="Week"?7:1},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d;});
  function move(direction:number){const date=new Date(cursor);if(view==="Month")date.setMonth(date.getMonth()+direction,1);else date.setDate(date.getDate()+direction*(view==="Week"?7:1));setCursor(date);}
  return <section id="calendar-module" className="mt-6 scroll-mt-6 rounded-2xl bg-white p-4 text-[#111] sm:p-7"><p className="text-xs font-bold tracking-widest text-[#C41E3A]">CALENDAR</p><h2 className="mt-2 text-2xl font-black">Plan. Where time turns into progress.</h2><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><button type="button" aria-label="Previous period" onClick={()=>move(-1)} className="rounded border border-black/20 px-3 py-2">‹</button><button type="button" onClick={()=>setCursor(new Date())} className="rounded border border-black/20 px-3 py-2 text-xs">Today</button><button type="button" aria-label="Next period" onClick={()=>move(1)} className="rounded border border-black/20 px-3 py-2">›</button></div><h3 className="text-sm font-bold">{cursor.toLocaleDateString(undefined,{month:"long",year:"numeric",...(view!=="Month"?{day:"numeric"}: {})})}</h3><div id="calendar-views" className="flex rounded-lg border border-black/20 p-1">{["Month","Week","Day"].map(v=><button type="button" key={v} aria-pressed={v===view} onClick={()=>setView(v as typeof view)} className={"rounded px-3 py-2 text-xs font-bold "+(v===view?"bg-[#111] text-white":"")}>{v}</button>)}</div></div>
    <div className="mt-4 flex flex-wrap gap-3 text-[10px]">{activityTypes.map(t=><span key={t} className="flex items-center gap-1"><span className="h-2 w-2 rounded-full" style={{background:colors[t]}}/>{t}</span>)}</div>
    {!h.calendar.length&&<div className="mt-4 rounded-lg bg-[#F5F5F0] p-4 text-sm">No events scheduled - Add activity</div>}
    <div id="calendar-grid" className={"mt-4 grid border-l border-t border-black/10 "+(view==="Day"?"grid-cols-1":"grid-cols-7")}>{days.map(date=>{const key=localDay(date);const rows=h.calendar.filter(r=>localDay(new Date(r.start))===key);return <div key={key} className={"min-w-0 border-b border-r border-black/10 p-1 sm:p-2 "+(view==="Month"?"min-h-20 sm:min-h-28":"min-h-40")+(date.getMonth()!==cursor.getMonth()?" bg-[#F5F5F0]":"")}><button type="button" aria-label={"Add activity on "+key} onClick={()=>h.openActivity({date:key})} className={"mb-1 w-full rounded py-2 text-left text-[10px] font-bold sm:text-xs "+(key===localDay(new Date())?"text-[#C41E3A]":"")}><span className="hidden sm:inline">{date.toLocaleDateString(undefined,{weekday:"short"})} </span>{date.getDate()}</button>{rows.map(r=><button type="button" key={r.id} title={r.title+" · "+eventTime(r)} onClick={()=>h.openActivity(r)} className="mb-1 block w-full truncate rounded px-1 py-1.5 text-left text-[9px] text-white sm:px-2 sm:text-[10px]" style={{background:colors[r.type]}}>{r.completed?"✓ ":""}{r.title}{view==="Day"?" · "+new Date(r.start).toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"})+"–"+new Date(r.end).toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"}):""}</button>)}</div>})}</div>
    <button type="button" onClick={()=>h.openActivity({date:localDay(cursor)})} className="mt-4 rounded-lg bg-[#C41E3A] px-4 py-3 text-xs font-bold text-white">Add Activity</button><p className="mt-3 text-xs text-black/60">Browser-saved preview calendar. Google Calendar sync is not connected.</p><div className="mt-4 flex flex-wrap justify-between gap-3 rounded-xl bg-[#F5F5F0] p-4 text-xs"><p><strong className="text-[#C41E3A]">EVA</strong> · {h.calendar.some(r=>r.type==="Community"&&new Date(r.start).getMonth()===cursor.getMonth()&&new Date(r.start).getFullYear()===cursor.getFullYear())?"Community activity recorded this month.":"No community activity this month. Schedule a clinic?"}</p><button type="button" onClick={()=>h.openActivity({type:"Community",date:localDay(cursor)})} className="font-bold underline">Schedule clinic →</button></div>
  </section>;
}

function EvaContent({prefix}:{prefix:string}){const h=useHq();const [message,setMessage]=useState(""),[response,setResponse]=useState("I can help you log activity, plan your calendar and track opportunities."),[busy,setBusy]=useState(false);
  const study=h.records.filter(r=>r.purpose==="study"&&r.completed),training=h.records.filter(r=>r.purpose==="training"&&r.completed),opps=h.records.filter(r=>r.purpose==="opportunity"&&r.stage!=="Completed");
  async function send(e:FormEvent){e.preventDefault();const query=message.trim();if(!query)return;setMessage("");const lower=query.toLowerCase();if(/study|tutor|academic/.test(lower)){h.openActivity({type:"Academics",purpose:"study"});setResponse("Your Study Hall Log is open. Save it to update Calendar and My Focus.");return;}if(/training log|workout|log training/.test(lower)){h.openActivity({type:"Training",purpose:"training"});setResponse("Your Training Log is open. Save it to update Calendar and My Focus.");return;}if(/opportunity|nil inquiry/.test(lower)){h.openActivity({type:"Opportunity",purpose:"opportunity"});setResponse("Enter an opportunity. Contracted opportunities create linked calendar holds.");return;}if(/calendar|event/.test(lower)){h.openActivity();setResponse("Add Activity is open. Your saved activity will appear in Calendar.");return;}if(/media|asset/.test(lower)){h.openAssets();setResponse("The approved asset vault is ready. Click View Asset to load an image.");return;}if(/focus|today/.test(lower)){setResponse(`${study.length} study sessions, ${training.length} completed workouts and ${opps.length} active opportunities recorded. ${h.upcoming.length?h.upcoming.map(r=>r.title+" · "+eventTime(r)).join("; "):"No upcoming activities scheduled."}`);return;}
    setBusy(true);try{const res=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"user",content:query}],system:"You are Eva, TB3 HQ's assistant. Do not invent athlete metrics, eligibility, contracts, events or completed actions. You cannot write HQ records; guide the user to Calendar, log or opportunity forms. No athlete records are supplied. Public booking and Google Calendar sync are not connected in this preview.",maxOutputTokens:400,metadata:{surface:"tb3-hq-preview"}})});const body=await res.json();setResponse(res.ok&&body.ok&&body.text?String(body.text):"Live AI chat requires a connected, signed-in account. Preview quick actions work now: log study hall, add a workout, track an opportunity or add a calendar event.");}catch{setResponse("Live chat is unavailable. You can still use the activity, calendar and opportunity quick actions.");}finally{setBusy(false);}}
  return <div className="flex min-h-0 flex-1 flex-col"><p className="text-xs leading-6 opacity-70">You’re in {h.module}. {study.length} study sessions · {training.length} workouts recorded.</p><div className="mt-5 grid gap-2">{[["Log Study Hall","study"],["Add Calendar Event","calendar"],["Track Opportunity","opportunity"],["Update Media","media"]].map(([label,action])=><button key={action} type="button" onClick={()=>{if(action==="media")h.openAssets();else h.openActivity(action==="study"?{type:"Academics",purpose:"study"}:action==="opportunity"?{type:"Opportunity",purpose:"opportunity"}:{});}} className="rounded-lg border border-[#C41E3A]/60 px-3 py-3 text-left text-xs font-bold">{label} →</button>)}</div><div className="mt-6 border-t border-current/10 pt-5"><p className="text-[10px] font-bold tracking-widest opacity-50">YOUR WORKSPACE</p><p className="mt-3 text-xs leading-6">{opps.length} active opportunities recorded.</p><p className="text-xs leading-6">{h.upcoming.length} upcoming activities.</p></div><p role="status" className="mt-5 whitespace-pre-wrap break-words rounded-xl bg-[#C41E3A]/10 p-4 text-xs leading-6">{response}</p><form onSubmit={send} className="mt-auto pt-6"><label htmlFor={prefix+"-eva-chat"} className="text-xs font-bold">Chat with Eva</label><div className="mt-2 flex gap-2"><input id={prefix+"-eva-chat"} maxLength={1200} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Chat with Eva →" className="min-w-0 flex-1 rounded-lg border border-current/20 bg-transparent px-3 py-3 text-xs"/><button disabled={busy} type="submit" className="rounded-lg bg-[#C41E3A] px-3 py-3 text-xs font-bold text-white">{busy?"…":"Send"}</button></div></form></div>;
}
export function EvaPanel(){return <aside id="eva-panel" className="fixed bottom-0 right-0 top-0 z-[100] hidden w-80 flex-col overflow-y-auto border-l border-[#222] bg-[#0A0A0A] p-6 text-white xl:flex"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black">EVA</h2><span aria-hidden="true" className="h-2 w-2 rounded-full bg-[#C41E3A]"/></div><p className="mb-6 text-xs opacity-60">Your AI Assistant</p><EvaContent prefix="desktop"/></aside>}
export function EvaFab(){const h=useHq();return <div className="fixed bottom-0 left-0 right-0 z-[100] flex h-24 items-center justify-end border-t border-white/10 bg-[#0A0A0A] px-5 xl:hidden"><button id="eva-fab" type="button" onClick={h.openEva} className="grid h-14 w-14 place-items-center rounded-full bg-[#C41E3A] text-xs font-black text-white shadow-xl" aria-label="Open Eva">EVA</button></div>}
export function EvaCommandBar(){const h=useHq();const [command,setCommand]=useState("");function submit(e:FormEvent){e.preventDefault();const q=command.trim().toLowerCase();if(!q){h.openEva();return;}setCommand("");if(/study|academic|tutor/.test(q))h.openActivity({type:"Academics",purpose:"study"});else if(/training|workout/.test(q))h.openActivity({type:"Training",purpose:"training"});else if(/opportunity/.test(q))h.openActivity({type:"Opportunity",purpose:"opportunity"});else if(/calendar|event/.test(q))h.openActivity();else if(/media|asset/.test(q))h.openAssets();else h.openEva();}return <div className="mb-6 rounded-2xl border border-white/10 bg-[#111] p-4"><form id="eva-command-bar" onSubmit={submit} className="flex gap-3"><span className="self-center text-xs font-black text-[#C41E3A]">EVA</span><input aria-label="Ask Eva" maxLength={1200} value={command} onChange={e=>setCommand(e.target.value)} placeholder="Ask Eva..." className="min-w-0 flex-1 bg-transparent text-sm outline-none"/><button type="submit" className="rounded-lg bg-[#C41E3A] px-4 py-2 text-xs font-bold">Ask →</button></form><p className="mt-3 text-[10px] text-white/50">Add training log · Track opportunity · Add calendar event</p><p className="mt-2 text-[10px] text-white/50">Preview workspace · Activities saved in this browser · Shared tracking follows approval</p>{h.notice&&<p role="status" className="mt-2 text-xs text-amber-300">{h.notice}</p>}</div>}
