export type CanonicalProjectRecord = {
  id: string;
  name: string;
  aliases: string[];
  kind: 'platform' | 'product' | 'client';
  officialWebsite: string | null;
  officialPortal: string | null;
  loginUrl: string | null;
  adminUrl: string | null;
  githubRepo: string | null;
  vercelProjects: string[];
  assetLocations: string[];
  status: 'active' | 'attention' | 'repository-only';
  verifiedOn: string | null;
  missing: string[];
  notes?: string;
};

const login = (slug: string) =>
  `https://efficiencyarchitects.online/portal/login?next=%2Fportal%2F${slug}`;

export const CANONICAL_PROJECT_REGISTRY: CanonicalProjectRecord[] = [
  {
    id: 'AMANDA',
    name: 'Amanda Catherine',
    aliases: ['Amanda', 'AesthetiKine', 'AesthetiKine Studio Lab', 'Empower Art Collective'],
    kind: 'client',
    officialWebsite: 'https://amandacatherine.ca',
    officialPortal: 'https://portal.efficiencyarchitects.online/amanda-catherine',
    loginUrl: login('amanda-catherine'),
    adminUrl: 'https://portal.efficiencyarchitects.online/amanda-catherine/reports',
    githubRepo: 'TheArchitect1111/ea-payments',
    vercelProjects: ['amanda-catherine-preview', 'ea-payments'],
    assetLocations: [
      'public/amanda-catherine',
      'app/components/experience/themes/amanda-editorial',
      'lib/amanda-catherine',
      'lib/portal-universal/packs/amanda-catherine.ts',
    ],
    status: 'active',
    verifiedOn: '2026-08-17',
    missing: [],
    notes: 'The website and portal are separate production surfaces. Do not use /portal/amanda.',
  },
  {
    id: 'EA-PLATFORM',
    name: 'EA Ecosystem Platform',
    aliases: ['Efficiency Architects', 'EA'],
    kind: 'platform',
    officialWebsite: 'https://efficiencyarchitects.online',
    officialPortal: 'https://efficiencyarchitects.online/portal/ea',
    loginUrl: 'https://efficiencyarchitects.online/portal/login',
    adminUrl: 'https://efficiencyarchitects.online/admin/client-registry',
    githubRepo: 'TheArchitect1111/ea-payments',
    vercelProjects: ['ea-payments'],
    assetLocations: ['public', 'app/portal', 'config'],
    status: 'active',
    verifiedOn: '2026-08-17',
    missing: [],
  },
  {
    id: 'AMPLIFI',
    name: 'Amplifi by Efficiency Architects',
    aliases: ['Amplifi', 'Amplifi Social'],
    kind: 'product',
    officialWebsite: 'https://efficiencyarchitects.online/amplifi',
    officialPortal: 'https://efficiencyarchitects.online/amplifi/workspace',
    loginUrl: 'https://efficiencyarchitects.online/portal/login?next=%2Famplifi%2Fworkspace',
    adminUrl: null,
    githubRepo: 'TheArchitect1111/ea-payments',
    vercelProjects: ['ea-payments'],
    assetLocations: ['app/amplifi', 'public/amplifi'],
    status: 'attention',
    verifiedOn: '2026-08-17',
    missing: ['adminUrl'],
    notes: 'The legacy ea-amplifi project redirects to this canonical surface.',
  },
  {
    id: 'SIMPLIFI',
    name: 'Simplifi by Efficiency Architects',
    aliases: ['Simplifi', 'Simplifi Orb'],
    kind: 'product',
    officialWebsite: 'https://simplifi.ai',
    officialPortal: 'https://efficiencyarchitects.online/simplifi/workspace',
    loginUrl: 'https://efficiencyarchitects.online/api/auth/demo-enter?next=/simplifi/workspace',
    adminUrl: null,
    githubRepo: 'TheArchitect1111/ea-payments',
    vercelProjects: ['ea-payments'],
    assetLocations: ['app/simplifi', 'app/simplifiorb'],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['adminUrl', 'verified source connection'],
  },
  {
    id: 'CPR',
    name: 'Canadian Prospect Recruitment',
    aliases: ['CPR', 'CPR Global Prospects', 'Coach Mike'],
    kind: 'client',
    officialWebsite: 'https://www.cprglobalsports.com',
    officialPortal: null,
    loginUrl: null,
    adminUrl: 'https://www.cprglobalsports.com/admin/create-client',
    githubRepo: 'TheArchitect1111/cpr-site',
    vercelProjects: ['cpr-site'],
    assetLocations: ['TheArchitect1111/cpr-site'],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['officialPortal', 'loginUrl'],
  },
  {
    id: 'EA-EXEC',
    name: 'EA Executive OS',
    aliases: ['Executive OS', 'EA Command Center', 'EA WT Home'],
    kind: 'platform',
    officialWebsite: 'https://ea-wt-home.vercel.app',
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: null,
    vercelProjects: ['ea-wt-home'],
    assetLocations: [],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['officialPortal', 'loginUrl', 'adminUrl', 'githubRepo', 'assetLocations'],
  },
  {
    id: 'NSP',
    name: 'Next Steps Pro',
    aliases: ['NSP', 'Next Steps'],
    kind: 'product',
    officialWebsite: 'https://next-steps-pro.vercel.app',
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: 'TheArchitect1111/next-steps-pro',
    vercelProjects: ['next-steps-pro'],
    assetLocations: ['TheArchitect1111/next-steps-pro'],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['officialPortal', 'loginUrl', 'adminUrl'],
  },
  {
    id: 'ETFM',
    name: 'Escaping the Financial Matrix',
    aliases: ['ETFM', 'Financial Matrix'],
    kind: 'product',
    officialWebsite: 'https://etfm-assessment.vercel.app',
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: 'TheArchitect1111/ETFM-ASSESSMENT-',
    vercelProjects: ['etfm-assessment'],
    assetLocations: ['TheArchitect1111/ETFM-ASSESSMENT-'],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['officialPortal', 'loginUrl', 'adminUrl'],
  },
  {
    id: 'MAGNIFI',
    name: 'Magnifi',
    aliases: ['EA Magnifi'],
    kind: 'product',
    officialWebsite: 'https://ea-magnifi.vercel.app',
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: null,
    vercelProjects: ['ea-magnifi'],
    assetLocations: [],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['officialPortal', 'loginUrl', 'adminUrl', 'githubRepo', 'assetLocations', 'canonical route confirmation'],
  },
  {
    id: 'EA-TRAIN',
    name: 'EA Training Transformation',
    aliases: ['Training Transformation'],
    kind: 'product',
    officialWebsite: 'https://ea-training-transformation.vercel.app',
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: null,
    vercelProjects: ['ea-training-transformation'],
    assetLocations: [],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['officialPortal', 'loginUrl', 'adminUrl', 'githubRepo', 'assetLocations'],
  },
  {
    id: 'EA-COMMS',
    name: 'EA Communications Chassis',
    aliases: ['Communications Chassis'],
    kind: 'product',
    officialWebsite: 'https://ea-communications-chassis.vercel.app',
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: null,
    vercelProjects: ['ea-communications-chassis'],
    assetLocations: [],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['officialPortal', 'loginUrl', 'adminUrl', 'githubRepo', 'assetLocations'],
  },
  {
    id: 'EA-BBALL',
    name: 'EA Basketball Program OS',
    aliases: ['Basketball OS', 'Form to Finish'],
    kind: 'product',
    officialWebsite: 'https://form-to-finish-executive-review.vercel.app',
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: null,
    vercelProjects: ['form-to-finish-executive-review'],
    assetLocations: [],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['officialPortal', 'loginUrl', 'adminUrl', 'githubRepo', 'assetLocations'],
  },
  {
    id: 'MAGIC',
    name: 'Mississauga Magic',
    aliases: ['Magic', 'Mike McKenzie'],
    kind: 'client',
    officialWebsite: 'https://mississaugamagic.com',
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: 'TheArchitect1111/cpr-site',
    vercelProjects: ['cpr-site'],
    assetLocations: ['TheArchitect1111/cpr-site'],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['officialPortal', 'loginUrl', 'adminUrl', 'canonical website source confirmation'],
  },
  {
    id: 'GSA',
    name: 'Gastonia-Shelby BrotherHub',
    aliases: ['BrotherHub', 'Gastonia Shelby Nupes', 'GSA Kappas'],
    kind: 'client',
    officialWebsite: 'https://brother-hub.vercel.app',
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: 'TheArchitect1111/BrotherHub',
    vercelProjects: ['brother-hub'],
    assetLocations: ['TheArchitect1111/BrotherHub'],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['officialPortal', 'loginUrl', 'adminUrl'],
  },
  {
    id: 'RUMBALL',
    name: 'Bob Rumball',
    aliases: ['Bob Rumball Experience Lab'],
    kind: 'client',
    officialWebsite: 'https://bobrumball-experience-lab.vercel.app',
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: null,
    vercelProjects: ['bobrumball-experience-lab'],
    assetLocations: [],
    status: 'attention',
    verifiedOn: '2026-08-15',
    missing: ['officialPortal', 'loginUrl', 'adminUrl', 'githubRepo', 'assetLocations'],
  },
  {
    id: 'EA-IP',
    name: 'EA Operating System',
    aliases: ['EA IP', 'EA OS'],
    kind: 'platform',
    officialWebsite: null,
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: 'TheArchitect1111/ea-operating-system',
    vercelProjects: [],
    assetLocations: ['TheArchitect1111/ea-operating-system'],
    status: 'repository-only',
    verifiedOn: '2026-08-15',
    missing: [],
  },
  {
    id: 'MBI',
    name: 'Money Behind It',
    aliases: ['MBI'],
    kind: 'product',
    officialWebsite: null,
    officialPortal: null,
    loginUrl: null,
    adminUrl: null,
    githubRepo: 'TheArchitect1111/ea-payments',
    vercelProjects: ['ea-payments'],
    assetLocations: [],
    status: 'attention',
    verifiedOn: null,
    missing: ['officialWebsite', 'officialPortal', 'loginUrl', 'adminUrl', 'assetLocations', 'canonical route'],
  },
];

export function findCanonicalProject(query: string) {
  const normalized = query.trim().toLowerCase();
  return CANONICAL_PROJECT_REGISTRY.find((project) =>
    [project.id, project.name, ...project.aliases].some((value) =>
      value.toLowerCase().includes(normalized) || normalized.includes(value.toLowerCase()),
    ),
  );
}

export function assertCanonicalRegistry() {
  const ids = new Set<string>();
  for (const project of CANONICAL_PROJECT_REGISTRY) {
    if (ids.has(project.id)) throw new Error(`Duplicate canonical project id: ${project.id}`);
    ids.add(project.id);
    if (project.status === 'active' && project.missing.length) {
      throw new Error(`Active project ${project.id} has unresolved canonical fields.`);
    }
    if (project.officialPortal?.includes('/portal/amanda')) {
      throw new Error('The invalid Amanda /portal/amanda route must never be canonical.');
    }
  }
  return true;
}
