/**
 * Downloadable Factory package (markdown) for email + admin export.
 */
import type { FactoryProject } from '@/lib/factory-project-store';
import { factoryFriendlyLabel } from '@/lib/factory-status-labels';
import { EA_PLATFORM_URL } from '@/lib/platform-urls';

export function factoryPackageDownloadUrl(projectId: string): string {
  const base = (
    process.env.NEXT_PUBLIC_BASE_URL ||
    EA_PLATFORM_URL ||
    'https://efficiencyarchitects.online'
  )
    .replace(/\/$/, '')
    .replace(/^https?:\/\/www\.efficiencyarchitects\.online/i, 'https://efficiencyarchitects.online');
  return `${base}/api/projects/${encodeURIComponent(projectId)}/export`;
}

export function exportFactoryProjectMarkdown(project: FactoryProject): string {
  const context = project.context;
  const artifacts = context?.artifacts ?? [];
  const outputs = context?.outputs ?? [];
  const lines: string[] = [
    `# Factory Package — ${project.client}`,
    '',
    `- **Project ID:** ${project.id}`,
    `- **Status:** ${factoryFriendlyLabel(project.pipelineStatus)} (\`${project.pipelineStatus}\`)`,
    `- **Goal:** ${project.goal}`,
    `- **Deliverable:** ${project.deliverable}`,
    project.industry ? `- **Industry:** ${project.industry}` : '',
    project.url ? `- **URL:** ${project.url}` : '',
    `- **Created:** ${project.createdAt}`,
    `- **Updated:** ${project.updatedAt}`,
    '',
    '## Notes',
    '',
    project.notes?.trim() || '_None_',
    '',
    '## Pipeline activity',
    '',
  ];

  for (const item of [...(project.activity || [])].reverse()) {
    lines.push(
      `- ${item.at}: ${item.from ?? '—'} → **${item.to}** (${item.worker})${item.detail ? ` — ${item.detail}` : ''}`,
    );
  }

  lines.push('', '## Capability outputs', '');
  if (!outputs.length) {
    lines.push('_No outputs yet._', '');
  } else {
    for (const out of outputs) {
      lines.push(`### ${out.kind} (\`${out.id}\`)`);
      lines.push('');
      lines.push(`- Worker: ${out.worker}`);
      lines.push(`- Created: ${out.createdAt}`);
      lines.push('');
      lines.push('```json');
      lines.push(JSON.stringify(out.payload ?? {}, null, 2));
      lines.push('```');
      lines.push('');
    }
  }

  lines.push('## Artifacts', '');
  if (!artifacts.length) {
    lines.push('_No artifacts yet._', '');
  } else {
    for (const art of artifacts) {
      lines.push(`### ${art.kind} — ${art.providerId} (\`${art.id}\`)`);
      lines.push('');
      lines.push('```json');
      lines.push(JSON.stringify(art.data ?? {}, null, 2));
      lines.push('```');
      lines.push('');
    }
  }

  if (project.launchId) {
    lines.push('## Linked EACP package', '');
    lines.push(`- Launch ID: ${project.launchId}`);
    if (project.launchReviewUrl) {
      lines.push(`- Review: ${project.launchReviewUrl}`);
    }
    lines.push('');
  }

  lines.push('---', '');
  lines.push('_Generated by EA Factory Core_');
  lines.push('');

  return lines.filter((line, index, arr) => !(line === '' && arr[index - 1] === '')).join('\n');
}

export function exportFactoryProjectJson(project: FactoryProject): string {
  return JSON.stringify(
    {
      exportedAt: new Date().toISOString(),
      project,
    },
    null,
    2,
  );
}
