/**
 * Brick OS capability taxonomy — single source of truth mapping the
 * Efficiency Architects capability list onto the portal chassis.
 *
 * Lifecycle tags live in lib/os-lifecycle.ts to avoid circular imports
 * with lib/experience-registry.ts.
 */
import type { ModuleId } from '@/lib/modules/registry';
import type { OsLifecycleTag } from '@/lib/os-lifecycle';

export type { OsLifecycleTag } from '@/lib/os-lifecycle';

export type OsCapabilityStatus = 'live' | 'thin' | 'admin' | 'planned';

export type OsCapabilitySurface = 'portal' | 'admin' | 'none';

export type OsCapabilityRow = {
  /** Kebab-case stable id */
  id: string;
  label: string;
  /** User-facing category, e.g. "Visibility & Intelligence" */
  category: string;
  lifecycle: OsLifecycleTag;
  moduleId?: ModuleId;
  surface: OsCapabilitySurface;
  status: OsCapabilityStatus;
  notes?: string;
};

export const OS_CAPABILITY_TAXONOMY: OsCapabilityRow[] = [
  {
    id: 'visibility-and-intelligence-visibility-intelligence-dashboard',
    label: "Visibility Intelligence Dashboard",
    category: "Visibility & Intelligence",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'visibility-and-intelligence-opportunity-tracking',
    label: "Opportunity Tracking",
    category: "Visibility & Intelligence",
    lifecycle: 'capture',
    moduleId: 'simplifi',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'visibility-and-intelligence-bottleneck-identification',
    label: "Bottleneck Identification",
    category: "Visibility & Intelligence",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'visibility-and-intelligence-capacity-analysis',
    label: "Capacity Analysis",
    category: "Visibility & Intelligence",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'visibility-and-intelligence-activity-monitoring',
    label: "Activity Monitoring",
    category: "Visibility & Intelligence",
    lifecycle: 'measure',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'visibility-and-intelligence-performance-tracking',
    label: "Performance Tracking",
    category: "Visibility & Intelligence",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'visibility-and-intelligence-engagement-tracking',
    label: "Engagement Tracking",
    category: "Visibility & Intelligence",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'visibility-and-intelligence-participation-tracking',
    label: "Participation Tracking",
    category: "Visibility & Intelligence",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'visibility-and-intelligence-follow-up-tracking',
    label: "Follow-Up Tracking",
    category: "Visibility & Intelligence",
    lifecycle: 'act',
    moduleId: 'simplifi',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'visibility-and-intelligence-executive-reporting',
    label: "Executive Reporting",
    category: "Visibility & Intelligence",
    lifecycle: 'measure',
    surface: 'admin',
    status: 'admin',
    notes: "Mission Control",
  },
  {
    id: 'visibility-and-intelligence-kpi-dashboards',
    label: "KPI Dashboards",
    category: "Visibility & Intelligence",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'visibility-and-intelligence-trend-analysis',
    label: "Trend Analysis",
    category: "Visibility & Intelligence",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'visibility-and-intelligence-operational-mri-assessment',
    label: "Operational MRI Assessment",
    category: "Visibility & Intelligence",
    lifecycle: 'measure',
    moduleId: 'discovery',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'visibility-and-intelligence-operational-blueprint-development',
    label: "Operational Blueprint Development",
    category: "Visibility & Intelligence",
    lifecycle: 'act',
    moduleId: 'ctp',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'communication-update-hub',
    label: "Update Hub",
    category: "Communication",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'communication-internal-announcements',
    label: "Internal Announcements",
    category: "Communication",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'communication-team-notifications',
    label: "Team Notifications",
    category: "Communication",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'communication-organization-wide-updates',
    label: "Organization-Wide Updates",
    category: "Communication",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'communication-department-communications',
    label: "Department Communications",
    category: "Communication",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'communication-automated-notifications',
    label: "Automated Notifications",
    category: "Communication",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'communication-sms-notifications',
    label: "SMS Notifications",
    category: "Communication",
    lifecycle: 'communicate',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'communication-email-notifications',
    label: "Email Notifications",
    category: "Communication",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'live',
    notes: "Resend + Update Hub",
  },
  {
    id: 'communication-push-notifications',
    label: "Push Notifications",
    category: "Communication",
    lifecycle: 'communicate',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'communication-member-communications',
    label: "Member Communications",
    category: "Communication",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'communication-volunteer-communications',
    label: "Volunteer Communications",
    category: "Communication",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'communication-staff-communications',
    label: "Staff Communications",
    category: "Communication",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'communication-stakeholder-communications',
    label: "Stakeholder Communications",
    category: "Communication",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'social-media-social-media-content-creation',
    label: "Social Media Content Creation",
    category: "Social Media",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'social-media-ai-assisted-post-creation',
    label: "AI-Assisted Post Creation",
    category: "Social Media",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'social-media-social-media-scheduling',
    label: "Social Media Scheduling",
    category: "Social Media",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'social-media-approval-workflows',
    label: "Approval Workflows",
    category: "Social Media",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'social-media-multi-platform-publishing',
    label: "Multi-Platform Publishing",
    category: "Social Media",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'social-media-social-media-calendar',
    label: "Social Media Calendar",
    category: "Social Media",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'social-media-automated-posting',
    label: "Automated Posting",
    category: "Social Media",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'social-media-content-library',
    label: "Content Library",
    category: "Social Media",
    lifecycle: 'organize',
    surface: 'admin',
    status: 'admin',
    notes: "Creative Studio",
  },
  {
    id: 'social-media-industry-content-discovery',
    label: "Industry Content Discovery",
    category: "Social Media",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'social-media-engagement-tracking',
    label: "Engagement Tracking",
    category: "Social Media",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'social-media-campaign-management',
    label: "Campaign Management",
    category: "Social Media",
    lifecycle: 'communicate',
    surface: 'admin',
    status: 'admin',
    notes: "Creative Studio campaigns",
  },
  {
    id: 'lead-management-lead-capture',
    label: "Lead Capture",
    category: "Lead Management",
    lifecycle: 'capture',
    moduleId: 'simplifi',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'lead-management-lead-tracking',
    label: "Lead Tracking",
    category: "Lead Management",
    lifecycle: 'capture',
    moduleId: 'simplifi',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'lead-management-lead-assignment',
    label: "Lead Assignment",
    category: "Lead Management",
    lifecycle: 'capture',
    moduleId: 'simplifi',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'lead-management-lead-nurturing',
    label: "Lead Nurturing",
    category: "Lead Management",
    lifecycle: 'act',
    moduleId: 'connect',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'lead-management-lead-qualification',
    label: "Lead Qualification",
    category: "Lead Management",
    lifecycle: 'capture',
    moduleId: 'simplifi',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'lead-management-contact-management',
    label: "Contact Management",
    category: "Lead Management",
    lifecycle: 'capture',
    moduleId: 'simplifi',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'lead-management-follow-up-automation',
    label: "Follow-Up Automation",
    category: "Lead Management",
    lifecycle: 'act',
    moduleId: 'connect',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'lead-management-prospect-pipeline-management',
    label: "Prospect Pipeline Management",
    category: "Lead Management",
    lifecycle: 'capture',
    moduleId: 'simplifi',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'lead-management-referral-tracking',
    label: "Referral Tracking",
    category: "Lead Management",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'lead-management-inquiry-management',
    label: "Inquiry Management",
    category: "Lead Management",
    lifecycle: 'capture',
    moduleId: 'ctp',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'event-management-event-creation',
    label: "Event Creation",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-event-registration',
    label: "Event Registration",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-event-promotion',
    label: "Event Promotion",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-rsvp-tracking',
    label: "RSVP Tracking",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-attendee-management',
    label: "Attendee Management",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-volunteer-scheduling',
    label: "Volunteer Scheduling",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-event-communication',
    label: "Event Communication",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-reminder-campaigns',
    label: "Reminder Campaigns",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-check-in-management',
    label: "Check-In Management",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-event-reporting',
    label: "Event Reporting",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-sponsorship-tracking',
    label: "Sponsorship Tracking",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-tournament-management',
    label: "Tournament Management",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-camp-registration',
    label: "Camp Registration",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'event-management-conference-management',
    label: "Conference Management",
    category: "Event Management",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'forms-and-applications-intake-forms',
    label: "Intake Forms",
    category: "Forms & Applications",
    lifecycle: 'capture',
    moduleId: 'ctp',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'forms-and-applications-applications',
    label: "Applications",
    category: "Forms & Applications",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'forms-and-applications-registration-forms',
    label: "Registration Forms",
    category: "Forms & Applications",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'forms-and-applications-membership-forms',
    label: "Membership Forms",
    category: "Forms & Applications",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'forms-and-applications-volunteer-forms',
    label: "Volunteer Forms",
    category: "Forms & Applications",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'forms-and-applications-contact-forms',
    label: "Contact Forms",
    category: "Forms & Applications",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'forms-and-applications-scholarship-applications',
    label: "Scholarship Applications",
    category: "Forms & Applications",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'forms-and-applications-recruiting-forms',
    label: "Recruiting Forms",
    category: "Forms & Applications",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'forms-and-applications-evaluation-forms',
    label: "Evaluation Forms",
    category: "Forms & Applications",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'forms-and-applications-surveys',
    label: "Surveys",
    category: "Forms & Applications",
    lifecycle: 'capture',
    moduleId: 'discovery',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'forms-and-applications-feedback-forms',
    label: "Feedback Forms",
    category: "Forms & Applications",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'forms-and-applications-digital-agreements',
    label: "Digital Agreements",
    category: "Forms & Applications",
    lifecycle: 'capture',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'forms-and-applications-digital-waivers',
    label: "Digital Waivers",
    category: "Forms & Applications",
    lifecycle: 'capture',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'workflow-automation-process-automation',
    label: "Process Automation",
    category: "Workflow Automation",
    lifecycle: 'act',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'workflow-automation-workflow-design',
    label: "Workflow Design",
    category: "Workflow Automation",
    lifecycle: 'act',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'workflow-automation-approval-workflows',
    label: "Approval Workflows",
    category: "Workflow Automation",
    lifecycle: 'act',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'workflow-automation-escalation-workflows',
    label: "Escalation Workflows",
    category: "Workflow Automation",
    lifecycle: 'act',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'workflow-automation-task-routing',
    label: "Task Routing",
    category: "Workflow Automation",
    lifecycle: 'act',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'workflow-automation-automated-reminders',
    label: "Automated Reminders",
    category: "Workflow Automation",
    lifecycle: 'act',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'workflow-automation-trigger-based-actions',
    label: "Trigger-Based Actions",
    category: "Workflow Automation",
    lifecycle: 'act',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'workflow-automation-multi-step-workflows',
    label: "Multi-Step Workflows",
    category: "Workflow Automation",
    lifecycle: 'act',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'workflow-automation-follow-up-sequences',
    label: "Follow-Up Sequences",
    category: "Workflow Automation",
    lifecycle: 'act',
    moduleId: 'connect',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'workflow-automation-automated-communications',
    label: "Automated Communications",
    category: "Workflow Automation",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'ai-workforce-ai-research-assistant',
    label: "AI Research Assistant",
    category: "AI Workforce",
    lifecycle: 'act',
    surface: 'admin',
    status: 'admin',
    notes: "EA Factory research workers",
  },
  {
    id: 'ai-workforce-ai-content-assistant',
    label: "AI Content Assistant",
    category: "AI Workforce",
    lifecycle: 'act',
    surface: 'admin',
    status: 'admin',
    notes: "Creative Studio / Amplifi drafts",
  },
  {
    id: 'ai-workforce-ai-communication-assistant',
    label: "AI Communication Assistant",
    category: "AI Workforce",
    lifecycle: 'act',
    moduleId: 'ask',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'ai-workforce-ai-follow-up-assistant',
    label: "AI Follow-Up Assistant",
    category: "AI Workforce",
    lifecycle: 'act',
    moduleId: 'ask',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'ai-workforce-ai-knowledge-assistant',
    label: "AI Knowledge Assistant",
    category: "AI Workforce",
    lifecycle: 'act',
    moduleId: 'ask',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'ai-workforce-ai-administrative-assistant',
    label: "AI Administrative Assistant",
    category: "AI Workforce",
    lifecycle: 'act',
    moduleId: 'ask',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'ai-workforce-ai-monitoring-assistant',
    label: "AI Monitoring Assistant",
    category: "AI Workforce",
    lifecycle: 'act',
    surface: 'admin',
    status: 'admin',
    notes: "Mission Control / Platform Guardian",
  },
  {
    id: 'ai-workforce-ai-opportunity-scanner',
    label: "AI Opportunity Scanner",
    category: "AI Workforce",
    lifecycle: 'act',
    moduleId: 'simplifi',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'ai-workforce-ai-newsletter-assistant',
    label: "AI Newsletter Assistant",
    category: "AI Workforce",
    lifecycle: 'act',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'ai-workforce-ai-social-media-assistant',
    label: "AI Social Media Assistant",
    category: "AI Workforce",
    lifecycle: 'act',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'websites-and-landing-pages-business-websites',
    label: "Business Websites",
    category: "Websites & Landing Pages",
    lifecycle: 'capture',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'websites-and-landing-pages-campaign-landing-pages',
    label: "Campaign Landing Pages",
    category: "Websites & Landing Pages",
    lifecycle: 'capture',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'websites-and-landing-pages-event-landing-pages',
    label: "Event Landing Pages",
    category: "Websites & Landing Pages",
    lifecycle: 'capture',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'websites-and-landing-pages-registration-pages',
    label: "Registration Pages",
    category: "Websites & Landing Pages",
    lifecycle: 'capture',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'websites-and-landing-pages-lead-generation-pages',
    label: "Lead Generation Pages",
    category: "Websites & Landing Pages",
    lifecycle: 'capture',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'websites-and-landing-pages-recruitment-pages',
    label: "Recruitment Pages",
    category: "Websites & Landing Pages",
    lifecycle: 'capture',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'websites-and-landing-pages-donor-pages',
    label: "Donor Pages",
    category: "Websites & Landing Pages",
    lifecycle: 'capture',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'websites-and-landing-pages-sponsor-pages',
    label: "Sponsor Pages",
    category: "Websites & Landing Pages",
    lifecycle: 'capture',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'websites-and-landing-pages-coach-pages',
    label: "Coach Pages",
    category: "Websites & Landing Pages",
    lifecycle: 'capture',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'websites-and-landing-pages-speaker-pages',
    label: "Speaker Pages",
    category: "Websites & Landing Pages",
    lifecycle: 'capture',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'websites-and-landing-pages-program-pages',
    label: "Program Pages",
    category: "Websites & Landing Pages",
    lifecycle: 'capture',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'portals-client-portals',
    label: "Client Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'portals-member-portals',
    label: "Member Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'portals-parent-portals',
    label: "Parent Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'portals-student-portals',
    label: "Student Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'portals-coach-portals',
    label: "Coach Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'portals-church-portals',
    label: "Church Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'portals-staff-portals',
    label: "Staff Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'portals-volunteer-portals',
    label: "Volunteer Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'portals-leadership-portals',
    label: "Leadership Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'portals-committee-portals',
    label: "Committee Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'portals-alumni-portals',
    label: "Alumni Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'portals-recruiting-portals',
    label: "Recruiting Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'portals-association-portals',
    label: "Association Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'portals-fraternity-portals',
    label: "Fraternity Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'portals-sorority-portals',
    label: "Sorority Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'portals-nonprofit-portals',
    label: "Nonprofit Portals",
    category: "Portals",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'content-and-resources-resource-libraries',
    label: "Resource Libraries",
    category: "Content & Resources",
    lifecycle: 'organize',
    moduleId: 'resources',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'content-and-resources-knowledge-centers',
    label: "Knowledge Centers",
    category: "Content & Resources",
    lifecycle: 'organize',
    moduleId: 'resources',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'content-and-resources-document-repositories',
    label: "Document Repositories",
    category: "Content & Resources",
    lifecycle: 'organize',
    moduleId: 'resources',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'content-and-resources-training-centers',
    label: "Training Centers",
    category: "Content & Resources",
    lifecycle: 'organize',
    moduleId: 'training',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'content-and-resources-policy-libraries',
    label: "Policy Libraries",
    category: "Content & Resources",
    lifecycle: 'organize',
    moduleId: 'resources',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'content-and-resources-video-libraries',
    label: "Video Libraries",
    category: "Content & Resources",
    lifecycle: 'organize',
    moduleId: 'training',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'content-and-resources-download-centers',
    label: "Download Centers",
    category: "Content & Resources",
    lifecycle: 'organize',
    moduleId: 'resources',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'content-and-resources-meeting-archives',
    label: "Meeting Archives",
    category: "Content & Resources",
    lifecycle: 'organize',
    moduleId: 'resources',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'content-and-resources-historical-archives',
    label: "Historical Archives",
    category: "Content & Resources",
    lifecycle: 'organize',
    moduleId: 'resources',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'document-management-document-storage',
    label: "Document Storage",
    category: "Document Management",
    lifecycle: 'organize',
    moduleId: 'documents',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'document-management-document-organization',
    label: "Document Organization",
    category: "Document Management",
    lifecycle: 'organize',
    moduleId: 'documents',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'document-management-secure-document-sharing',
    label: "Secure Document Sharing",
    category: "Document Management",
    lifecycle: 'organize',
    moduleId: 'documents',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'document-management-permission-based-access',
    label: "Permission-Based Access",
    category: "Document Management",
    lifecycle: 'organize',
    moduleId: 'documents',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'document-management-file-libraries',
    label: "File Libraries",
    category: "Document Management",
    lifecycle: 'organize',
    moduleId: 'documents',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'document-management-digital-forms',
    label: "Digital Forms",
    category: "Document Management",
    lifecycle: 'organize',
    moduleId: 'documents',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'document-management-resource-distribution',
    label: "Resource Distribution",
    category: "Document Management",
    lifecycle: 'organize',
    moduleId: 'documents',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'team-coordination-task-assignment',
    label: "Task Assignment",
    category: "Team Coordination",
    lifecycle: 'organize',
    moduleId: 'connect',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'team-coordination-responsibility-tracking',
    label: "Responsibility Tracking",
    category: "Team Coordination",
    lifecycle: 'organize',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'team-coordination-project-coordination',
    label: "Project Coordination",
    category: "Team Coordination",
    lifecycle: 'organize',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'team-coordination-committee-management',
    label: "Committee Management",
    category: "Team Coordination",
    lifecycle: 'organize',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'team-coordination-team-communication',
    label: "Team Communication",
    category: "Team Coordination",
    lifecycle: 'organize',
    moduleId: 'messaging',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'team-coordination-accountability-systems',
    label: "Accountability Systems",
    category: "Team Coordination",
    lifecycle: 'organize',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'team-coordination-progress-tracking',
    label: "Progress Tracking",
    category: "Team Coordination",
    lifecycle: 'organize',
    moduleId: 'ctp',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'team-coordination-action-item-tracking',
    label: "Action Item Tracking",
    category: "Team Coordination",
    lifecycle: 'organize',
    moduleId: 'connect',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'marketing-campaign-management',
    label: "Campaign Management",
    category: "Marketing",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'marketing-content-marketing',
    label: "Content Marketing",
    category: "Marketing",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'marketing-email-marketing',
    label: "Email Marketing",
    category: "Marketing",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'marketing-newsletter-creation',
    label: "Newsletter Creation",
    category: "Marketing",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'marketing-event-promotion',
    label: "Event Promotion",
    category: "Marketing",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'marketing-lead-generation-campaigns',
    label: "Lead Generation Campaigns",
    category: "Marketing",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'marketing-sponsor-outreach',
    label: "Sponsor Outreach",
    category: "Marketing",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'marketing-donor-outreach',
    label: "Donor Outreach",
    category: "Marketing",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'marketing-community-engagement-campaigns',
    label: "Community Engagement Campaigns",
    category: "Marketing",
    lifecycle: 'communicate',
    moduleId: 'amplifi',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'email-systems-email-campaigns',
    label: "Email Campaigns",
    category: "Email Systems",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'email-systems-automated-email-sequences',
    label: "Automated Email Sequences",
    category: "Email Systems",
    lifecycle: 'communicate',
    moduleId: 'connect',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'email-systems-newsletters',
    label: "Newsletters",
    category: "Email Systems",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'email-systems-welcome-sequences',
    label: "Welcome Sequences",
    category: "Email Systems",
    lifecycle: 'communicate',
    moduleId: 'connect',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'email-systems-reminder-campaigns',
    label: "Reminder Campaigns",
    category: "Email Systems",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'email-systems-follow-up-sequences',
    label: "Follow-Up Sequences",
    category: "Email Systems",
    lifecycle: 'communicate',
    moduleId: 'connect',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'email-systems-announcement-campaigns',
    label: "Announcement Campaigns",
    category: "Email Systems",
    lifecycle: 'communicate',
    moduleId: 'update-hub',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'recruiting-and-enrollment-athlete-recruiting',
    label: "Athlete Recruiting",
    category: "Recruiting & Enrollment",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'recruiting-and-enrollment-student-recruiting',
    label: "Student Recruiting",
    category: "Recruiting & Enrollment",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'recruiting-and-enrollment-membership-recruitment',
    label: "Membership Recruitment",
    category: "Recruiting & Enrollment",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'recruiting-and-enrollment-volunteer-recruitment',
    label: "Volunteer Recruitment",
    category: "Recruiting & Enrollment",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'recruiting-and-enrollment-enrollment-tracking',
    label: "Enrollment Tracking",
    category: "Recruiting & Enrollment",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'recruiting-and-enrollment-candidate-tracking',
    label: "Candidate Tracking",
    category: "Recruiting & Enrollment",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'recruiting-and-enrollment-coach-outreach',
    label: "Coach Outreach",
    category: "Recruiting & Enrollment",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'recruiting-and-enrollment-prospect-tracking',
    label: "Prospect Tracking",
    category: "Recruiting & Enrollment",
    lifecycle: 'capture',
    moduleId: 'connect',
    surface: 'portal',
    status: 'planned',
  },
  {
    id: 'fundraising-and-sponsorships-sponsorship-tracking',
    label: "Sponsorship Tracking",
    category: "Fundraising & Sponsorships",
    lifecycle: 'act',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'fundraising-and-sponsorships-donor-tracking',
    label: "Donor Tracking",
    category: "Fundraising & Sponsorships",
    lifecycle: 'act',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'fundraising-and-sponsorships-fundraising-campaigns',
    label: "Fundraising Campaigns",
    category: "Fundraising & Sponsorships",
    lifecycle: 'act',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'fundraising-and-sponsorships-contribution-tracking',
    label: "Contribution Tracking",
    category: "Fundraising & Sponsorships",
    lifecycle: 'act',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'fundraising-and-sponsorships-partner-management',
    label: "Partner Management",
    category: "Fundraising & Sponsorships",
    lifecycle: 'act',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'fundraising-and-sponsorships-grant-tracking',
    label: "Grant Tracking",
    category: "Fundraising & Sponsorships",
    lifecycle: 'act',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'membership-management-member-directory',
    label: "Member Directory",
    category: "Membership Management",
    lifecycle: 'organize',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'membership-management-membership-tracking',
    label: "Membership Tracking",
    category: "Membership Management",
    lifecycle: 'organize',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'membership-management-member-communications',
    label: "Member Communications",
    category: "Membership Management",
    lifecycle: 'organize',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'membership-management-renewal-tracking',
    label: "Renewal Tracking",
    category: "Membership Management",
    lifecycle: 'organize',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'membership-management-participation-tracking',
    label: "Participation Tracking",
    category: "Membership Management",
    lifecycle: 'organize',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'membership-management-committee-assignments',
    label: "Committee Assignments",
    category: "Membership Management",
    lifecycle: 'organize',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'scheduling-calendar-management',
    label: "Calendar Management",
    category: "Scheduling",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'scheduling-event-calendars',
    label: "Event Calendars",
    category: "Scheduling",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'scheduling-team-calendars',
    label: "Team Calendars",
    category: "Scheduling",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'scheduling-appointment-scheduling',
    label: "Appointment Scheduling",
    category: "Scheduling",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'scheduling-reminder-systems',
    label: "Reminder Systems",
    category: "Scheduling",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'scheduling-deadline-tracking',
    label: "Deadline Tracking",
    category: "Scheduling",
    lifecycle: 'organize',
    moduleId: 'events',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'analytics-and-reporting-executive-dashboards',
    label: "Executive Dashboards",
    category: "Analytics & Reporting",
    lifecycle: 'measure',
    surface: 'admin',
    status: 'admin',
    notes: "Mission Control",
  },
  {
    id: 'analytics-and-reporting-participation-reports',
    label: "Participation Reports",
    category: "Analytics & Reporting",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'analytics-and-reporting-event-reports',
    label: "Event Reports",
    category: "Analytics & Reporting",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'analytics-and-reporting-engagement-reports',
    label: "Engagement Reports",
    category: "Analytics & Reporting",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'analytics-and-reporting-marketing-reports',
    label: "Marketing Reports",
    category: "Analytics & Reporting",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'analytics-and-reporting-membership-reports',
    label: "Membership Reports",
    category: "Analytics & Reporting",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'analytics-and-reporting-sponsorship-reports',
    label: "Sponsorship Reports",
    category: "Analytics & Reporting",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'analytics-and-reporting-lead-reports',
    label: "Lead Reports",
    category: "Analytics & Reporting",
    lifecycle: 'measure',
    moduleId: 'simplifi',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'analytics-and-reporting-capacity-reports',
    label: "Capacity Reports",
    category: "Analytics & Reporting",
    lifecycle: 'measure',
    moduleId: 'pulse',
    surface: 'portal',
    status: 'thin',
  },
  {
    id: 'mobile-experience-mobile-friendly-portals',
    label: "Mobile-Friendly Portals",
    category: "Mobile Experience",
    lifecycle: 'communicate',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'live',
    notes: "Responsive portal chassis",
  },
  {
    id: 'mobile-experience-progressive-web-apps-pwa',
    label: "Progressive Web Apps (PWA)",
    category: "Mobile Experience",
    lifecycle: 'communicate',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'mobile-experience-home-screen-installation',
    label: "Home Screen Installation",
    category: "Mobile Experience",
    lifecycle: 'communicate',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'mobile-experience-branded-app-experience',
    label: "Branded App Experience",
    category: "Mobile Experience",
    lifecycle: 'communicate',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'mobile-experience-push-notifications',
    label: "Push Notifications",
    category: "Mobile Experience",
    lifecycle: 'communicate',
    surface: 'none',
    status: 'planned',
  },
  {
    id: 'branding-and-customization-custom-branding',
    label: "Custom Branding",
    category: "Branding & Customization",
    lifecycle: 'organize',
    surface: 'admin',
    status: 'admin',
    notes: "Creative Studio brand",
  },
  {
    id: 'branding-and-customization-custom-portal-design',
    label: "Custom Portal Design",
    category: "Branding & Customization",
    lifecycle: 'organize',
    moduleId: 'landing',
    surface: 'portal',
    status: 'live',
    notes: "Experience Builder",
  },
  {
    id: 'branding-and-customization-custom-app-icons',
    label: "Custom App Icons",
    category: "Branding & Customization",
    lifecycle: 'organize',
    surface: 'admin',
    status: 'admin',
    notes: "Creative Studio / theme-engine",
  },
  {
    id: 'branding-and-customization-custom-splash-screens',
    label: "Custom Splash Screens",
    category: "Branding & Customization",
    lifecycle: 'organize',
    surface: 'admin',
    status: 'admin',
    notes: "Creative Studio / theme-engine",
  },
  {
    id: 'branding-and-customization-custom-login-experiences',
    label: "Custom Login Experiences",
    category: "Branding & Customization",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'thin',
    notes: "Creative Studio / theme-engine",
  },
  {
    id: 'branding-and-customization-custom-email-templates',
    label: "Custom Email Templates",
    category: "Branding & Customization",
    lifecycle: 'organize',
    surface: 'admin',
    status: 'admin',
    notes: "Creative Studio / theme-engine",
  },
  {
    id: 'branding-and-customization-organization-specific-workflows',
    label: "Organization-Specific Workflows",
    category: "Branding & Customization",
    lifecycle: 'organize',
    surface: 'admin',
    status: 'admin',
    notes: "Creative Studio / theme-engine",
  },
  {
    id: 'branding-and-customization-industry-specific-solutions',
    label: "Industry-Specific Solutions",
    category: "Branding & Customization",
    lifecycle: 'organize',
    surface: 'admin',
    status: 'admin',
    notes: "Creative Studio / theme-engine",
  },
  {
    id: 'industry-solutions-churches',
    label: "Churches",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-nonprofits',
    label: "Nonprofits",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-coaches',
    label: "Coaches",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-athletic-programs',
    label: "Athletic Programs",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-aau-organizations',
    label: "AAU Organizations",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-recruiting-services',
    label: "Recruiting Services",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-real-estate-professionals',
    label: "Real Estate Professionals",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-financial-professionals',
    label: "Financial Professionals",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-professional-associations',
    label: "Professional Associations",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-fraternities',
    label: "Fraternities",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-sororities',
    label: "Sororities",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-chambers-of-commerce',
    label: "Chambers of Commerce",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-educational-programs',
    label: "Educational Programs",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-community-organizations',
    label: "Community Organizations",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-small-businesses',
    label: "Small Businesses",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'industry-solutions-service-businesses',
    label: "Service Businesses",
    category: "Industry Solutions",
    lifecycle: 'organize',
    moduleId: 'dashboard',
    surface: 'portal',
    status: 'planned',
    notes: "Industry skin / personality preset",
  },
  {
    id: 'strategic-services-operational-mri',
    label: "Operational MRI™",
    category: "Strategic Services",
    lifecycle: 'measure',
    moduleId: 'discovery',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'strategic-services-capacity-assessment',
    label: "Capacity Assessment",
    category: "Strategic Services",
    lifecycle: 'measure',
    moduleId: 'discovery',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'strategic-services-process-mapping',
    label: "Process Mapping",
    category: "Strategic Services",
    lifecycle: 'measure',
    moduleId: 'discovery',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'strategic-services-workflow-design',
    label: "Workflow Design",
    category: "Strategic Services",
    lifecycle: 'measure',
    moduleId: 'discovery',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'strategic-services-organizational-blueprint-development',
    label: "Organizational Blueprint Development",
    category: "Strategic Services",
    lifecycle: 'act',
    moduleId: 'ctp',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'strategic-services-capacity-recovery-planning',
    label: "Capacity Recovery Planning",
    category: "Strategic Services",
    lifecycle: 'measure',
    moduleId: 'discovery',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'strategic-services-visibility-strategy',
    label: "Visibility Strategy",
    category: "Strategic Services",
    lifecycle: 'measure',
    moduleId: 'discovery',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'strategic-services-communication-strategy',
    label: "Communication Strategy",
    category: "Strategic Services",
    lifecycle: 'measure',
    moduleId: 'discovery',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'strategic-services-growth-infrastructure-design',
    label: "Growth Infrastructure Design",
    category: "Strategic Services",
    lifecycle: 'act',
    moduleId: 'ctp',
    surface: 'portal',
    status: 'live',
  },
  {
    id: 'strategic-services-organizational-transformation-planning',
    label: "Organizational Transformation Planning",
    category: "Strategic Services",
    lifecycle: 'act',
    moduleId: 'ctp',
    surface: 'portal',
    status: 'live',
  },
];

export function listOsCapabilitiesByLifecycle(tag: OsLifecycleTag): OsCapabilityRow[] {
  return OS_CAPABILITY_TAXONOMY.filter((row) => row.lifecycle === tag);
}

export function listOsCapabilitiesByModule(moduleId: ModuleId): OsCapabilityRow[] {
  return OS_CAPABILITY_TAXONOMY.filter((row) => row.moduleId === moduleId);
}

export type OsCapabilityCoverageSummary = {
  total: number;
  byStatus: Record<OsCapabilityStatus, number>;
  byLifecycle: Record<OsLifecycleTag, number>;
};

export function osCapabilityCoverageSummary(): OsCapabilityCoverageSummary {
  const byStatus: Record<OsCapabilityStatus, number> = {
    live: 0,
    thin: 0,
    admin: 0,
    planned: 0,
  };
  const byLifecycle: Record<OsLifecycleTag, number> = {
    capture: 0,
    organize: 0,
    communicate: 0,
    act: 0,
    measure: 0,
  };

  for (const row of OS_CAPABILITY_TAXONOMY) {
    byStatus[row.status] += 1;
    byLifecycle[row.lifecycle] += 1;
  }

  return { total: OS_CAPABILITY_TAXONOMY.length, byStatus, byLifecycle };
}
