import { NextRequest, NextResponse } from 'next/server';
import { guardPortalApi, portalApiUnauthorized, portalTenant } from '@/lib/api/portal-route';
import { callClaudeText } from '@/lib/ai';
import type { AIRequestContext } from '@/lib/ai/types';
import { getAgent } from '@/lib/agents/registry';
import { normalizeCampaignArchitecture } from '@/lib/creative-studio/campaign-architecture';
import { assignPortfolioPosts } from '@/lib/amplifi-campaign-command';

type CampaignPost={title:string;caption:string;callToAction:string;imageDirection:string;imageUrl?:string};
const cleanJson=(t:string)=>t.replace(/^```json\s*/i,'').replace(/^```\s*/,'').replace(/```\s*$/,'').trim();
const short=(v:unknown,n:number)=>String(v||'').replace(/[\u2013\u2014]/g,',').replace(/\s+/g,' ').trim().slice(0,n);
function parse(text:string,promotion:string,architecture:any){const p=JSON.parse(cleanJson(text));if(!Array.isArray(p.posts)||p.posts.length!==5)throw new Error('five posts required');return{title:short(p.campaignTitle||promotion,90),strategy:short(p.strategy,300),posts:assignPortfolioPosts(p.posts.map((x:any)=>({title:short(x.title,70),caption:short(x.caption,360),callToAction:short(x.callToAction,100),imageDirection:short(x.imageDirection,240)})),architecture),architecture}}
function fallback(goal:string,audience:string,details:string,cta:string,architecture:any){const lower=goal.toLowerCase();const midweek=/tuesday|wednesday|midweek/.test(lower);const appointment=/appointment|booking|barber|salon|client/.test(lower);const title=midweek&&appointment?'Take Back the Middle of Your Week':'Make the Goal Visible';const result=goal;const posts:CampaignPost[]=[{title:midweek?'Your weekend appointment has a midweek solution':'Start with the result you actually want',caption:`${audience} do not need another generic promotion. Give them a specific reason to act now. ${details}`.trim(),callToAction:cta,imageDirection:'Photographic hero: a real person from the target audience enjoying the desired experience, premium editorial lighting, minimal headline.'},{title:midweek?'Skip the weekend scramble':'Make the problem recognizable',caption:`Show the friction the audience already feels, then position the offer as the easier path toward ${result}.`,callToAction:cta,imageDirection:'Lifestyle problem/solution creative with human emotion and strong visual contrast, not a text-only card.'},{title:midweek?'Tuesday just opened up':'Give them a reason to choose now',caption:`Turn availability into an advantage. Make the timing, convenience and benefit concrete. ${details}`.trim(),callToAction:cta,imageDirection:'Offer-led conversion graphic using photography, a clear benefit, restrained typography and visible action.'},{title:'See yourself in the result',caption:`Build belief with a proof-shaped story: what the experience feels like, why it is easier, and what the audience gains. Do not invent testimonials or statistics.`,callToAction:cta,imageDirection:'Carousel/story concept featuring a human moment, service detail and outcome frame with consistent campaign art direction.'},{title:midweek?'Make Tuesday yours':'Take the next step while it is easy',caption:`Close the campaign by making the action unmistakable and connecting it directly to ${result}.`,callToAction:cta,imageDirection:'Decisive conversion creative with emotionally relevant photography, booking/action cue and generous negative space.'}];return{title,strategy:`A five-part conversion campaign for ${audience}: earn attention, make the problem familiar, present the reason to act, build belief, then convert.`,posts:assignPortfolioPosts(posts,architecture),architecture}}
function images(c:any){const layouts=['photo-hero','editorial-split','promotion-offer','story-proof','photo-action'];return{...c,posts:c.posts.map((p:CampaignPost,i:number)=>({...p,imageUrl:`/api/amplifi/post-image?title=${encodeURIComponent(p.title)}&subhead=${encodeURIComponent(p.caption.slice(0,120))}&objective=${encodeURIComponent(['Awareness','Problem','Offer','Proof','Conversion'][i])}&cta=${encodeURIComponent(i===4?p.callToAction:'')}&layout=${layouts[i]}&format=carousel&v=9`}))}}
export const dynamic='force-dynamic';export const maxDuration=120;
export async function POST(req:NextRequest){const auth=await guardPortalApi(req,{realm:'simplifi'});if(!auth.ok)return portalApiUnauthorized(auth);const tenant=portalTenant(auth.session);const b=await req.json().catch(()=>({}));const promotion=short(b.promotion,500),audience=short(b.audience,300),result=short(b.result||promotion,500),details=short(b.details,600),cta=short(b.callToAction||'Take the next step',100);if(!promotion||!audience)return NextResponse.json({ok:false,error:'Tell Amplifi the goal and who you want to reach.'},{status:400});const architecture=normalizeCampaignArchitecture(undefined,{title:promotion,objective:result,audience,platforms:['facebook','instagram'],ctaLabel:cta});const prompt=[`Create a premium five-piece social campaign, not five generic posts.`,`Return JSON only: {"campaignTitle":string,"strategy":string,"posts":[{"title":string,"caption":string,"callToAction":string,"imageDirection":string}]}.`,`Goal: ${promotion}`,`Audience: ${audience}`,`Useful context: ${details||'None supplied.'}`,`Required sequence: 1 awareness hook, 2 problem/insight, 3 offer/reason to act, 4 proof/belief without invented claims, 5 conversion.`,`Create one memorable campaign idea that unifies all five pieces while each piece has a visibly different creative job.`,`Headlines must be specific to this business goal. Never use generic productivity language unless the brief is actually about productivity.`,`Visual directions must use emotionally relevant people, environments, products or service moments where appropriate. Do not default to text-only graphics.`,`Write as a helpful guide. Never guarantee results.`].join('\n');try{const agent=getAgent('amplifi-content-director');if(!agent)throw new Error('agent unavailable');const ctx:AIRequestContext={requestId:crypto.randomUUID(),actor:{id:auth.session.sub||tenant.organizationId,type:'portal',email:auth.session.email,portalSlug:tenant.portalSlug,role:auth.session.role},route:'/api/portal/amplifi/create-campaign',metadata:{product:'amplifi',workflow:'preview'}};const r=await agent.execute({intent:'premium campaign preview',query:prompt,context:{organization:tenant.portalSlug}},ctx);return NextResponse.json({ok:true,campaign:images(parse(JSON.stringify(r.raw),promotion,architecture)),publishReady:false});}catch{const text=await callClaudeText(prompt,{maxTokens:3000});if(text)try{return NextResponse.json({ok:true,campaign:images(parse(text,promotion,architecture)),publishReady:false})}catch{}return NextResponse.json({ok:true,campaign:images(fallback(promotion,audience,details,cta,architecture)),fallback:true,publishReady:false})}}
