import type { Metadata } from 'next';
import Link from 'next/link';
import AmplifiBrand from '../AmplifiBrand';
import { AMPLIFI_PLANS, AMPLIFI_PLAN_ORDER } from '@/lib/amplifi-plans';
import '../amplifi-commerce.css';

export const metadata: Metadata = { title: 'Amplifi Plans | Choose your marketing operating level', description: 'Start with a real campaign preview, then choose how much of the marketing operation you want Amplifi to carry.' };

const display = {
 starter:{label:'Show me what Amplifi can do',action:'Create my sample',href:'/amplifi/create?mode=campaign',features:['3 individual posts each month','1 sample campaign','Premium graphics','Smartchitecture brand foundation','No publishing connection required']},
 social:{label:'Create and publish consistently',action:'Begin with Social',href:'/amplifi/register?plan=amplifi_social',features:['Up to 30 posts each month','Up to 4 coordinated series','Up to 4 campaigns','Graphics and short-form video','Approval, scheduling and publishing']},
 intelligence:{label:'Find the story and create it',action:'Begin with Intelligence',href:'/amplifi/register?plan=amplifi_intelligence',features:['Everything in Social','Up to 60 posts each month','Up to 8 series and campaigns','Research and opportunity monitoring','Three watched subjects']},
 complete:{label:'Run the complete content operation',action:'Begin with Complete',href:'/amplifi/register?plan=amplifi_complete',features:['Everything in Intelligence','Unlimited posts, series and campaigns','Ten watched subjects','Social, email and blog planning','Complete Smartchitecture learning loop']}
} as const;

export default function AmplifiPricingPage(){return <main className="am-commerce"><nav className="am-commerce-nav"><AmplifiBrand/><div><Link href="/amplifi">Product</Link><Link href="/portal/login?next=%2Famplifi%2Fworkspace">Sign in</Link></div></nav><section className="am-pricing-hero"><div><p className="am-commerce-kicker">FOUR LEVELS · ONE SYSTEM</p><h1>See the work first. Then choose how much of the operation Amplifi should carry.</h1></div><p>Every paid level uses the same creative foundation. The difference is capacity, research, monitoring and how broadly Amplifi can operate.</p></section><section className="am-plan-grid">{AMPLIFI_PLAN_ORDER.map((id,index)=>{const plan=AMPLIFI_PLANS[id],d=display[id];return <article className={`am-plan${index===1?' am-plan-featured':''}`} key={id}>{index===1?<span className="am-plan-ribbon">MOST USEFUL START</span>:null}<p className="am-plan-label">AMPLIFI {plan.name.toUpperCase()}</p><h2>{plan.name}</h2><p className="am-plan-promise">{d.label}</p><p className="am-plan-price"><strong>{plan.monthlyPrice===0?'Free':`$${plan.monthlyPrice}`}</strong>{plan.monthlyPrice>0?<span>/month</span>:null}</p><p className="am-plan-description">{plan.description}</p><ul>{d.features.map(f=><li key={f}>{f}</li>)}</ul><Link href={d.href} className="am-plan-button am-plan-button-live">{d.action}<span>→</span></Link><small>{plan.monthlyPrice===0?'No payment required.':'Secure subscription checkout powered by Stripe.'}</small></article>})}</section><section className="am-after-purchase"><p className="am-commerce-kicker">AFTER YOU CHOOSE</p><h2>Payment should open the product, not create an administrative task.</h2><ol><li><strong>Checkout confirms the plan.</strong><span>Stripe records the subscription and Amplifi receives the plan identity.</span></li><li><strong>Your workspace is provisioned.</strong><span>Account, organization and module entitlements are prepared automatically.</span></li><li><strong>Your plan controls access.</strong><span>Research, publishing, monitoring and creation limits follow the central plan registry.</span></li><li><strong>Billing stays synchronized.</strong><span>Cancellation, failed payment and subscription changes update entitlements through the Stripe lifecycle.</span></li></ol></section><footer className="am-commerce-footer"><AmplifiBrand/><nav><Link href="/legal/privacy">Privacy</Link><Link href="/legal/terms">Terms</Link><Link href="/contact">Contact</Link></nav></footer></main>}
