import Link from 'next/link';
import {sevenSportsBrief,sevenSportsDeckSlides,sevenSportsMasterReference} from '@/lib/studio/projects/seven-sports';
import {buildStudioPlan} from '@/lib/studio/production';
import {directions} from '@/lib/studio/design-system';

export default function SevenSportsStudioBrief(){
 const plan=buildStudioPlan(sevenSportsBrief);
 return <main className="min-h-screen bg-[#f7f4ee] text-[#111] font-sans"><style>{`.serif{font-family:Iowan Old Style,Palatino Linotype,Book Antiqua,Palatino,Georgia,serif}.slide{display:grid;grid-template-columns:90px 1fr 1.1fr .7fr;gap:24px;align-items:start;padding:28px 0;border-bottom:1px solid #0001}.pill{display:inline-flex;border:1px solid #0002;border-radius:999px;padding:9px 13px;font-size:10px;letter-spacing:.16em;text-transform:uppercase}.box{background:white;border:1px solid #0001;border-radius:30px;padding:30px;box-shadow:0 24px 80px #0000000a}@media(max-width:900px){.slide{grid-template-columns:1fr}.box{border-radius:22px}}`}</style>
  <header className="h-20 px-6 md:px-12 lg:px-20 border-b border-black/10 flex items-center justify-between"><Link href="/studio/create" className="text-[11px] uppercase tracking-[.2em] font-semibold">← Design Studio</Link><span className="text-[10px] uppercase tracking-[.2em] text-black/45">Seven Sports · active brief</span></header>
  <section className="px-6 md:px-12 lg:px-20 py-20 max-w-[1500px] mx-auto"><p className="text-[10px] uppercase tracking-[.28em] text-[#b89245] mb-7">Presentation blueprint</p><h1 className="serif text-[clamp(3.8rem,9vw,8.5rem)] leading-[.82] tracking-[-.065em] font-normal">{sevenSportsBrief.title}</h1><div className="grid lg:grid-cols-[.8fr_1fr] gap-12 mt-12"><p className="text-2xl md:text-3xl leading-tight">Use the approved full-homepage image as the source of truth. Recreate each section sharply, then explain why it belongs in the emotional journey.</p><div className="box"><p className="text-[10px] uppercase tracking-[.2em] text-black/45 mb-4">Master reference</p><h2 className="serif text-3xl tracking-[-.03em] mb-4">{sevenSportsMasterReference.label}</h2><p className="text-sm leading-relaxed text-black/55">{sevenSportsMasterReference.rule}</p><div className="mt-7 flex flex-wrap gap-3"><span className="pill">{plan.status.replaceAll('_',' ')}</span><span className="pill">{directions[plan.direction].name}</span><span className="pill">12 slides</span></div></div></div></section>
  <section className="px-6 md:px-12 lg:px-20 pb-20 max-w-[1500px] mx-auto"><div className="box"><p className="text-[10px] uppercase tracking-[.28em] text-black/40 mb-8">Slide contract</p>{sevenSportsDeckSlides.map(s=><article className="slide" key={s.number}><div><span className="text-[#b89245] font-semibold tabular-nums">{String(s.number).padStart(2,'0')}</span></div><div><h3 className="serif text-3xl tracking-[-.03em]">{s.title}</h3><p className="mt-2 text-sm uppercase tracking-[.14em] text-black/40">{s.section}</p><p className="mt-4 text-sm text-black/55 leading-relaxed"><b>Emotional role:</b> {s.emotionalRole}</p></div><div><h4 className="text-xs uppercase tracking-[.16em] mb-3 text-black/45">Left visual</h4><p className="text-sm leading-relaxed text-black/65">{s.leftVisual}</p></div><div><h4 className="text-xs uppercase tracking-[.16em] mb-3 text-black/45">Right explanation</h4><p className="text-sm leading-relaxed text-black/65">{s.rightExplanation}</p></div></article>)}</div></section>
  <section className="bg-[#111] text-white px-6 md:px-12 lg:px-20 py-20"><div className="max-w-[1500px] mx-auto grid lg:grid-cols-[.8fr_1fr] gap-14"><div><p className="text-[10px] uppercase tracking-[.28em] text-[#d9b76d] mb-6">Non-negotiables</p><h2 className="serif text-5xl md:text-7xl tracking-[-.045em]">No drift.</h2><p className="mt-7 text-white/55 leading-relaxed">This brief blocks Design Studio from inventing a different website. The approved master homepage is the visual contract.</p></div><div>{sevenSportsBrief.nonNegotiables?.map(item=><div key={item} className="py-4 border-b border-white/10 text-sm text-white/70">✓ {item}</div>)}</div></div></section>
 </main>;
}
