import Link from 'next/link';

const projectTypes=[
  ['01','Website','Flagship public experience','Story, structure, imagery, conversion and responsive design.'],
  ['02','Landing Page','One goal. No distraction.','Campaign, event, offer or launch experiences built around a single action.'],
  ['03','Portal','Useful enough to become a habit.','Member, client and operational experiences designed around what people need to do next.'],
  ['04','Event Creative','Make the first impression count.','Flyers, invitations, campaign systems, QR journeys and event-facing creative.'],
  ['05','Presentation','Make the room lean in.','Proposals, evaluations, decks and visual storytelling with executive-level polish.'],
];

export default function StudioCreate(){return <main className="min-h-screen bg-[#f4f1e9] text-[#111] font-sans">
<style>{`.serif{font-family:Iowan Old Style,Palatino Linotype,Book Antiqua,Palatino,Georgia,serif}.studio-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:rgba(17,17,17,.14);border:1px solid rgba(17,17,17,.14)}.studio-card{background:#f4f1e9;padding:36px;min-height:280px;display:flex;flex-direction:column;justify-content:space-between;transition:.35s}.studio-card:hover{background:#111;color:#fff}.studio-card:hover p,.studio-card:hover small{color:rgba(255,255,255,.55)}@media(max-width:760px){.studio-grid{grid-template-columns:1fr}.studio-card{min-height:235px}}`}</style>
<header className="px-6 md:px-12 lg:px-20 h-20 flex items-center justify-between border-b border-black/10"><Link href="/studio" className="text-[11px] tracking-[.2em] uppercase font-semibold">Efficiency Architects · Studio</Link><span className="text-[10px] tracking-[.2em] uppercase text-black/45">Create</span></header>
<section className="px-6 md:px-12 lg:px-20 py-20 md:py-28 max-w-[1500px] mx-auto"><p className="text-[10px] tracking-[.28em] uppercase text-black/45 mb-8">Creative operating system</p><h1 className="serif text-[clamp(4rem,10vw,9rem)] leading-[.78] tracking-[-.065em] font-normal">Start with the<br/><em>experience.</em></h1><div className="grid md:grid-cols-2 gap-10 md:gap-24 mt-14 md:mt-20 items-end"><p className="text-xl md:text-3xl leading-tight font-medium max-w-xl">Choose what we are building. Studio turns the brief into a connected creative direction, not a template.</p><p className="text-base leading-relaxed text-black/55 max-w-md md:justify-self-end">Every project moves through the same spine: brief → direction → concept → review → build → quality gate → launch. The output changes. The standard does not.</p></div></section>
<section className="px-6 md:px-12 lg:px-20 pb-24 md:pb-36 max-w-[1500px] mx-auto"><div className="studio-grid">{projectTypes.map(([n,title,kicker,copy],i)=><article key={title} className={`studio-card ${i===4?'md:col-span-2':''}`}><div><small className="text-[10px] tracking-[.2em] uppercase text-black/40">{n}</small><h2 className="serif text-4xl md:text-6xl tracking-[-.04em] mt-5">{title}</h2></div><div><strong className="block text-sm mb-2">{kicker}</strong><p className="text-sm leading-relaxed text-black/52 max-w-lg">{copy}</p></div></article>)}</div></section>
<section className="bg-[#111] text-white px-6 md:px-12 lg:px-20 py-20"><div className="max-w-[1500px] mx-auto grid lg:grid-cols-[1fr_.7fr] gap-16 items-end"><div><p className="text-[10px] tracking-[.28em] uppercase text-white/40 mb-7">Flagship project / Twin City Kappas</p><h2 className="serif text-5xl md:text-7xl tracking-[-.045em] leading-[.92]">Website + Portal + Event System</h2></div><div><p className="text-white/55 leading-relaxed">Twin City is our first full Studio case: premium public experience, BrotherHub portal, golf operations and event creative designed as one system.</p><p className="mt-5 text-xs tracking-[.16em] uppercase text-[#c7a65e]">Concept 01 is in build</p></div></div></section>
</main>}
