import Link from 'next/link';
import {studioAgents,premiumGate,directions} from '@/lib/studio/design-system';
import {buildStudioPlan} from '@/lib/studio/production';
import {twinCityGolfBrief} from '@/lib/studio/projects/twin-city-golf';
import {sevenSportsBrief,sevenSportsDeckSlides,sevenSportsMasterReference} from '@/lib/studio/projects/seven-sports';

const projectTypes=[['01','Website','Flagship public experience','Story, structure, imagery, conversion and responsive design.'],['02','Landing Page','One goal. No distraction.','Campaign, event, offer or launch experiences built around a single action.'],['03','Portal','Useful enough to become a habit.','Member, client and operational experiences designed around what people need to do next.'],['04','Event Creative','Make the first impression count.','Flyers, invitations, campaign systems, QR journeys and event-facing creative.'],['05','Presentation','Make the room lean in.','Proposals, evaluations, decks and visual storytelling with executive-level polish.']];
const agents=Object.values(studioAgents);

export default function StudioCreate(){
 const twinCityPlan=buildStudioPlan(twinCityGolfBrief);
 const sevenSportsPlan=buildStudioPlan(sevenSportsBrief);
 return <main className="min-h-screen bg-[#f4f1e9] text-[#111] font-sans"><style>{`.serif{font-family:Iowan Old Style,Palatino Linotype,Book Antiqua,Palatino,Georgia,serif}.grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:#0002;border:1px solid #0002}.card{background:#f4f1e9;padding:36px;min-height:260px;display:flex;flex-direction:column;justify-content:space-between}.agent{border-top:1px solid #ffffff25;padding:22px 0}.gate{display:flex;gap:16px;padding:15px 0;border-bottom:1px solid #0002}.gate:before{content:'✓';font-weight:700}.blocker{padding:12px 0;border-bottom:1px solid #ffffff25}.blocker:before{content:'×';margin-right:10px;color:#e7c06f}.slide{display:grid;grid-template-columns:56px 1fr;gap:18px;padding:18px 0;border-bottom:1px solid #0002}.pill{display:inline-flex;align-items:center;border:1px solid #0002;border-radius:999px;padding:9px 13px;font-size:10px;letter-spacing:.16em;text-transform:uppercase}@media(max-width:760px){.grid2{grid-template-columns:1fr}.card{min-height:220px}.slide{grid-template-columns:1fr}}`}</style>
  <header className="px-6 md:px-12 lg:px-20 h-20 flex items-center justify-between border-b border-black/10"><Link href="/studio" className="text-[11px] tracking-[.2em] uppercase font-semibold">Efficiency Architects · Design Studio</Link><span className="text-[10px] tracking-[.2em] uppercase text-black/45">One Studio · Specialist team underneath</span></header>
  <section className="px-6 md:px-12 lg:px-20 py-20 md:py-28 max-w-[1500px] mx-auto"><p className="text-[10px] tracking-[.28em] uppercase text-black/45 mb-8">Creative operating system</p><h1 className="serif text-[clamp(4rem,10vw,9rem)] leading-[.78] tracking-[-.065em] font-normal">Say what to build.<br/><em>Studio handles how.</em></h1><div className="grid md:grid-cols-2 gap-10 md:gap-24 mt-14"><p className="text-xl md:text-3xl leading-tight font-medium">Brief → art direction → approved assets → production → visual inspection → premium gate → outputs.</p><p className="text-base leading-relaxed text-black/55 max-w-md md:justify-self-end">Production tools stay behind the wall. Studio owns the quality standard, brand memory and final acceptance.</p></div></section>
  <section className="px-6 md:px-12 lg:px-20 pb-24 max-w-[1500px] mx-auto"><div className="grid2">{projectTypes.map(([n,title,kicker,copy],i)=><article key={title} className={`card ${i===4?'md:col-span-2':''}`}><div><small className="text-[10px] tracking-[.2em] uppercase text-black/40">{n}</small><h2 className="serif text-4xl md:text-6xl tracking-[-.04em] mt-5">{title}</h2></div><div><strong className="block text-sm mb-2">{kicker}</strong><p className="text-sm leading-relaxed text-black/52 max-w-lg">{copy}</p></div></article>)}</div></section>
  <section className="bg-white text-[#111] px-6 md:px-12 lg:px-20 py-24 border-y border-black/10"><div className="max-w-[1500px] mx-auto grid lg:grid-cols-[.82fr_1fr] gap-14"><div><p className="text-[10px] tracking-[.28em] uppercase text-[#b89245] mb-6">Active Design Studio Brief</p><h2 className="serif text-5xl md:text-7xl tracking-[-.045em]">{sevenSportsBrief.title}</h2><p className="mt-7 text-black/55 leading-relaxed max-w-xl">The approved full-homepage image is locked as the master visual reference. Design Studio will deconstruct it section by section into a 12-slide Apple-style client presentation: enlarged website section on the left, concise explanation on the right.</p><div className="mt-8 flex flex-wrap gap-3"><span className="pill">Status · {sevenSportsPlan.status.replaceAll('_',' ')}</span><span className="pill">Direction · {directions[sevenSportsPlan.direction].name}</span><span className="pill">Slides · {sevenSportsDeckSlides.length}</span></div><Link href="/studio/create/seven-sports" className="mt-9 inline-flex bg-[#111] text-white rounded-full px-6 py-3 text-xs tracking-[.16em] uppercase">Open 7 Sports Studio Brief</Link></div><div className="bg-[#f4f1e9] border border-black/10 rounded-[32px] p-7"><p className="text-[10px] tracking-[.2em] uppercase text-black/45 mb-4">Master reference locked</p><h3 className="serif text-3xl tracking-[-.03em] mb-4">{sevenSportsMasterReference.label}</h3><p className="text-sm text-black/55 leading-relaxed">{sevenSportsMasterReference.rule}</p><div className="mt-8">{sevenSportsDeckSlides.slice(0,6).map(s=><div className="slide" key={s.number}><strong className="text-[#b89245] tabular-nums">{String(s.number).padStart(2,'0')}</strong><span><b className="block text-sm">{s.title}</b><small className="text-black/45">{s.emotionalRole} · {s.section}</small></span></div>)}</div></div></div></section>
  <section className="bg-[#111] text-white px-6 md:px-12 lg:px-20 py-24"><div className="max-w-[1500px] mx-auto"><p className="text-[10px] tracking-[.28em] uppercase text-white/40 mb-8">Invisible specialist team</p><h2 className="serif text-5xl md:text-7xl tracking-[-.045em] mb-12">One Studio. Five disciplines.</h2><div className="grid md:grid-cols-2 lg:grid-cols-5 gap-7">{agents.map(a=><div className="agent" key={a.role}><h3 className="serif text-2xl mb-4">{a.role}</h3><p className="text-xs leading-relaxed text-white/50">{a.owns.join(' · ')}</p></div>)}</div></div></section>
  <section className="px-6 md:px-12 lg:px-20 py-24 max-w-[1500px] mx-auto"><p className="text-[10px] tracking-[.28em] uppercase text-black/45 mb-7">Hard quality gate</p><div className="grid lg:grid-cols-[.7fr_1fr] gap-16"><div><h2 className="serif text-5xl md:text-7xl tracking-[-.045em]">Weak work does not ship.</h2><p className="mt-7 text-black/55 leading-relaxed">A project remains blocked until every hard gate passes on the rendered output.</p></div><div>{premiumGate.map(g=><div className="gate" key={g.id}><span><strong className="block text-sm">{g.label}</strong><small className="text-black/45 uppercase tracking-[.12em]">{g.owner}</small></span></div>)}</div></div></section>
  <section className="bg-[#7c0d1b] text-white px-6 md:px-12 lg:px-20 py-24"><div className="max-w-[1500px] mx-auto grid lg:grid-cols-2 gap-14"><div><p className="text-[10px] tracking-[.28em] uppercase text-[#d9b76d] mb-6">Acceptance test 001</p><h2 className="serif text-5xl md:text-7xl tracking-[-.045em]">{twinCityGolfBrief.title}</h2><p className="mt-6 text-white/60">Direction: {directions[twinCityPlan.direction].name}</p><p className="mt-3 text-white/60">Renderer: {twinCityPlan.renderer}</p></div><div><p className="text-sm uppercase tracking-[.15em] text-[#d9b76d] mb-4">Live Studio decision</p><p className="text-xs tracking-[.15em] uppercase mb-6">Status · {twinCityPlan.status.replaceAll('_',' ')}</p>{twinCityPlan.blockers.length?twinCityPlan.blockers.map(b=><div className="blocker text-sm" key={b}>{b}</div>):<p className="text-sm">All required assets locked. Ready to render.</p>}</div></div></section>
 </main>;
}
