import React from 'react';
import './style.css';

type IconName='compass'|'eye'|'question'|'route'|'check'|'chart'|'building'|'wallet'|'credit'|'cash'|'document'|'debt'|'shield'|'target'|'portal'|'spark'|'lock'|'people';
const paths:Record<IconName,React.ReactNode>={
compass:<><circle cx="12" cy="12" r="8"/><path d="m15 9-2 4-4 2 2-4 4-2Z"/></>,eye:<><path d="M2.5 12s3.5-5 9.5-5 9.5 5 9.5 5-3.5 5-9.5 5-9.5-5-9.5-5Z"/><circle cx="12" cy="12" r="2"/></>,question:<><circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.4 2.4 0 1 1 3.7 2c-1 .7-1.5 1.1-1.5 2.2"/><path d="M12 17h.01"/></>,route:<><circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M8 18h3a3 3 0 0 0 3-3V9a3 3 0 0 1 3-3"/></>,check:<><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/></>,chart:<><path d="M4 19V9M10 19V5M16 19v-7M22 19H2"/></>,building:<><path d="M4 21V7l8-4 8 4v14M8 10h2M14 10h2M8 14h2M14 14h2M10 21v-3h4v3"/></>,wallet:<><path d="M3 7h15a2 2 0 0 1 2 2v10H5a2 2 0 0 1-2-2V7Z"/><path d="M3 7V5a2 2 0 0 1 2-2h12v4M16 12h4"/></>,credit:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M7 15h3"/></>,cash:<><path d="M4 18V8M10 18V4M16 18v-7M22 18H2"/><path d="m3 6 5-3 5 4 7-5"/></>,document:<><path d="M6 2h8l4 4v16H6Z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></>,debt:<><circle cx="12" cy="12" r="9"/><path d="M15 8.5c-.6-.7-1.5-1-2.7-1-1.5 0-2.5.7-2.5 1.8 0 2.8 5.4 1.3 5.4 4.2 0 1.2-1.1 2-2.7 2-1.3 0-2.4-.4-3.2-1.2M12 5.5v13"/></>,shield:<><path d="M12 2 20 5v6c0 5-3.4 8.5-8 11-4.6-2.5-8-6-8-11V5l8-3Z"/><path d="m9 12 2 2 4-5"/></>,target:<><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/></>,portal:<><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 3v18M12 8h5M12 12h5M12 16h3"/></>,spark:<><path d="m12 2 1.5 5.5L19 9l-5.5 1.5L12 16l-1.5-5.5L5 9l5.5-1.5L12 2ZM19 16l.7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7L19 16Z"/></>,lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>,people:<><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2"/><path d="M3 20c0-4 2.5-6 6-6s6 2 6 6M15 15c3 0 5 1.5 5 4"/></>};
const Icon=({name}:{name:IconName})=><span className="icon" aria-hidden><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg></span>;
const scores=[['Business proposition','8/10'],['Website execution','5/10'],['Differentiation','6/10'],['Conversion potential','6/10'],['EA opportunity','9/10']];
const dims:[IconName,string,string][]=[['building','Business stability','Is the business established and consistent?'],['wallet','Financials','Do the numbers tell a healthy story?'],['credit','Credit profile','What will a lender see?'],['cash','Cash flow','Can the business comfortably support capital?'],['document','Documentation','Are the records ready when requested?'],['debt','Debt capacity','How much additional obligation is realistic?'],['shield','Risk','What could make a lender hesitate?'],['target','Capital fit','Which funding options actually fit?']];
export default function Page(){return <main className="ayf">
<section className="cover"><div className="coverGrid"><div><div className="eyebrow">EFFICIENCY ARCHITECTS · DIGITAL DEEP DIVE</div><h1>ARE YOU<br/><i>FUNDABLE?</i></h1><p className="lead"><b>Know where your business stands.</b><br/>See what may be holding you back, then get a clear path for what to do next.</p></div><div className="heroPhoto"><div className="photoLabel">A CLEARER<br/>PATH TO CAPITAL</div></div></div></section>
<section className="finding"><Icon name="eye"/><span>WHAT WE SEE</span><h2>The idea is strong.<br/><i>The digital experience needs to help people feel that strength.</i></h2><div className="scoreRow">{scores.map(([a,b])=><div className="score" key={a}><strong>{b}</strong><small>{a}</small></div>)}</div><p className="statement">The opportunity is not to add more information. It is to help a business owner quickly answer three questions: <b>Where do I stand? What is hurting me? What should I do next?</b></p></section>
<section className="story photoStress"><div className="storyCopy"><Icon name="question"/><span>START WHERE THE OWNER IS</span><h2>“Can my business actually qualify?”</h2><p>That question usually comes with pressure. The owner may have already heard no, may not know what lenders are looking for, or may simply be tired of guessing. The experience should meet them there and immediately begin replacing uncertainty with direction.</p></div></section>
<section className="editorial"><div className="num">01</div><div><Icon name="compass"/><span>THE FIRST MOVE</span><h2>Answer the question before asking for the meeting.</h2><p>Let the visitor complete a focused assessment and see an initial readiness picture. That gives them useful value immediately and gives the consultation a better starting point. Instead of spending the meeting discovering the basics, the conversation can focus on what needs to change.</p></div></section>
<section className="split"><div className="dark"><Icon name="eye"/><span>TODAY</span><h2>Read.<br/>Wonder.<br/>Book.</h2><p>A visitor learns about the service, but still has to decide whether a consultation will help.</p></div><div className="light"><Icon name="route"/><span>THE BETTER JOURNEY</span><h2>Assess.<br/><i>Understand.</i><br/>Move.</h2><p>The visitor receives a useful result first, understands the gaps, and enters the conversation already knowing why the next step matters.</p></div></section>
<section className="story photoBuilder"><div className="storyCopy right"><Icon name="chart"/><span>MAKE THE INVISIBLE VISIBLE</span><h2>Give the owner something they can understand.</h2><p>“Fundability” can feel vague. A readiness score changes that. It shows what is working, where the weak spots are, and which areas deserve attention first. The score is not the finish line. It is the beginning of the guide.</p></div></section>
<section className="scoreExperience"><div><Icon name="chart"/><span>AN EXAMPLE RESULT</span><h2>YOUR CAPITAL READINESS</h2><div className="bigScore">72<span>/100</span></div><h3>You have a foundation. A few issues may be limiting your options.</h3><p>Instead of simply saying “not ready,” the result explains where the business is strong and where focused improvement could create better funding conversations.</p></div><div className="meter">{[['Business stability',88],['Revenue history',82],['Documentation',64],['Credit profile',59],['Debt capacity',48]].map(([x,v])=><div className="m" key={x as string}><div><b>{x}</b><span>{v}</span></div><i><em style={{width:`${v}%`}}/></i></div>)}</div></section>
<section className="architecture"><Icon name="compass"/><span>WHAT THE ASSESSMENT EXPLAINS</span><h2>Eight areas. One clear picture.</h2><p className="sectionIntro">A business owner should not need to understand lending jargon to understand their position. Organize the evaluation around the questions that actually affect readiness, then explain each one in plain language.</p><div className="dimGrid">{dims.map(([ic,d,desc],i)=><div className="dim" key={d}><Icon name={ic}/><b>0{i+1}</b><span>{d}</span><small>{desc}</small></div>)}</div></section>
<section className="portal"><div className="portalIntro"><Icon name="portal"/><span>AFTER THE ASSESSMENT</span><h2>Do not hand them a score<br/>and send them away.</h2><p>The score should open a private workspace where the owner can see the plan, gather documents, track improvements and know what deserves attention next. Their progress stays visible instead of disappearing into emails and notes.</p></div><div className="ui"><aside><b>AYF</b><a>Readiness</a><a>Roadmap</a><a>Documents</a><a>Opportunities</a></aside><article><div className="uiTop">Your Capital Readiness</div><div className="uiScore"><b>72</b><span>Current Score</span><em>+11 since your first assessment</em></div><div className="tasks"><h4>YOUR NEXT STEP</h4><p>Upload your 2025 business tax return <b>DO THIS NEXT</b></p><p>Why it matters: complete financial records help determine which capital options are realistic for your business.</p></div></article></div></section>
<section className="eva"><div className="evaMark"><div className="evaHalo">E</div><small>EVA · YOUR DIGITAL GUIDE</small></div><div><Icon name="spark"/><span>AVAILABLE WHEN THE OWNER NEEDS HELP</span><h2>Eva keeps the owner from asking,<br/><i>“What am I supposed to do now?”</i></h2><p>Eva uses the owner’s readiness picture and roadmap to keep the experience moving. She explains why a step matters, points to the next action, reminds the owner when something is unfinished, and helps them prepare for the next funding conversation.</p><div className="evaActions"><b>01 <small>EXPLAINS THE SCORE</small></b><b>02 <small>GUIDES THE NEXT STEP</small></b><b>03 <small>KEEPS PROGRESS MOVING</small></b></div></div></section>
<section className="story photoRelief"><div className="storyCopy"><Icon name="check"/><span>THE FEELING WE WANT</span><h2>“Now I understand what to do.”</h2><p>The best outcome is not simply a better website. It is the moment the owner stops guessing. They can see their position, understand the priorities, and move forward one manageable step at a time.</p></div></section>
<section className="smart"><Icon name="route"/><span>SMARTCHITECTURE</span><h2>The pieces work together<br/>so the owner does not have to.</h2><p className="sectionIntro">The assessment, score, roadmap, portal and Eva should feel like one connected journey. Information entered once follows the owner forward, each step informs the next, and the system keeps the right action visible.</p><div className="flow">{['ASSESS','SEE YOUR SCORE','UNDERSTAND THE GAPS','FOLLOW YOUR ROADMAP','PREPARE','FIND THE RIGHT FIT'].map(x=><b key={x}>{x}</b>)}</div></section>
<section className="security"><Icon name="shield"/><span>TRUST MATTERS</span><h2>If people are sharing financial information, the experience must feel safe.</h2><p className="sectionIntro">Trust is not a footnote here. From sign-in to document handling, the owner should understand what is being requested, why it is needed and who can see it.</p><div className="securityGrid"><div><Icon name="lock"/><h3>Private access</h3><p>Each owner enters a protected workspace built around their business and their plan.</p></div><div><Icon name="document"/><h3>Purposeful documents</h3><p>Ask for records when they are needed and explain how each one helps move the process forward.</p></div><div><Icon name="shield"/><h3>Clear permissions</h3><p>Make access, authorization and activity easy to understand and easy to trace.</p></div></div></section>
<section className="story photoSuccess"><div className="storyCopy right"><Icon name="people"/><span>THE BETTER CONVERSATION</span><h2>Preparation changes what happens next.</h2><p>The owner arrives knowing their strengths, their gaps and the work already completed. The advisor does not have to start from zero. Together they can focus on the funding path that fits the business now, or the specific steps needed to become ready.</p></div></section>
<section className="close"><Icon name="compass"/><div className="eyebrow">EFFICIENCY ARCHITECTS</div><h2>The opportunity is bigger than a redesign.</h2><h1>Turn “Am I fundable?” into<br/><i>“Here is what I do next.”</i></h1><div className="closeFlow">UNDERSTAND YOUR POSITION → FIX THE GAPS → PREPARE → FIND THE RIGHT FIT</div><p>Guided by Eva + Smartchitecture™</p></section>
</main>}
