import React from 'react';
import './style.css';

const Icon=({children}:{children:string})=><span className="icon" aria-hidden>{children}</span>;
const scores=[['Business proposition','8/10'],['Website execution','5/10'],['Differentiation','6/10'],['Conversion potential','6/10'],['EA opportunity','9/10']];
const dims=[['◈','Business stability'],['▥','Financials'],['◎','Credit profile'],['↗','Cash flow'],['▤','Documentation'],['◒','Debt capacity'],['△','Risk'],['⌁','Capital fit']];
export default function Page(){return <main className="ayf">
<section className="cover"><div className="coverGrid"><div><div className="eyebrow">EFFICIENCY ARCHITECTS · DIGITAL DEEP DIVE</div><h1>ARE YOU<br/><i>FUNDABLE?</i></h1><p className="lead">Turn uncertainty about capital into a clear path forward.</p></div><div className="heroPhoto"><div className="photoLabel">CAPITAL<br/>READINESS</div></div></div></section>
<section className="finding"><Icon>◆</Icon><span>EXECUTIVE FINDING</span><h2>Strong proposition.<br/><i>The experience should make it undeniable.</i></h2><div className="scoreRow">{scores.map(([a,b])=><div className="score" key={a}><strong>{b}</strong><small>{a}</small></div>)}</div><p className="statement">See what a funder is likely to see <b>before asking for money.</b></p></section>
<section className="story photoStress"><div className="storyCopy"><Icon>?</Icon><span>THE REAL MOMENT</span><h2>Capital pressure feels personal.</h2><p>Owners do not need more information. They need to know what is standing between the business they built and the capital it needs.</p></div></section>
<section className="editorial"><div className="num">01</div><div><Icon>◎</Icon><span>THE FINDING</span><h2>The question is powerful. Make the answer immediate.</h2><p>Assess readiness first. Let the value be experienced before the consultation.</p></div></section>
<section className="split"><div className="dark"><Icon>→</Icon><span>CURRENT</span><h2>Read.<br/>Trust.<br/>Book.</h2></div><div className="light"><Icon>✓</Icon><span>CONNECTED</span><h2>Assess.<br/><i>Understand.</i><br/>Act.</h2></div></section>
<section className="story photoBuilder"><div className="storyCopy right"><Icon>↗</Icon><span>THE OPPORTUNITY</span><h2>Make progress visible.</h2><p>A score turns an abstract financial conversation into something an owner can understand, improve and believe in.</p></div></section>
<section className="scoreExperience"><div><Icon>72</Icon><span>THE PRODUCT MOMENT</span><h2>CAPITAL READINESS</h2><div className="bigScore">72<span>/100</span></div><h3>Promising. Not lender-ready yet.</h3></div><div className="meter">{[['Stability',88],['Revenue',82],['Documents',64],['Credit',59],['Debt',48]].map(([x,v])=><div className="m" key={x as string}><div><b>{x}</b><span>{v}</span></div><i><em style={{width:`${v}%`}}/></i></div>)}</div></section>
<section className="architecture"><Icon>▦</Icon><span>THE METHODOLOGY</span><h2>Make fundability understandable.</h2><div className="dimGrid">{dims.map(([ic,d],i)=><div className="dim" key={d}><Icon>{ic}</Icon><b>0{i+1}</b><span>{d}</span></div>)}</div></section>
<section className="portal"><div className="portalIntro"><Icon>▣</Icon><span>THE CAPITAL PORTAL</span><h2>Your score becomes<br/>your operating system.</h2></div><div className="ui"><aside><b>AYF</b><a>● Readiness</a><a>↗ Roadmap</a><a>▤ Documents</a><a>◇ Opportunities</a></aside><article><div className="uiTop">Capital Readiness</div><div className="uiScore"><b>72</b><span>Readiness Score</span><em>+11 since assessment</em></div><div className="tasks"><h4>NEXT BEST ACTION</h4><p>Upload 2025 business tax return <b>DO NOW</b></p></div></article></div></section>
<section className="eva"><div className="evaMark"><div className="evaHalo">E</div><small>EA DIGITAL INTELLIGENCE</small></div><div><Icon>✦</Icon><span>EVA · 24/7 DIGITAL ASSISTANT</span><h2>Not a chatbot.<br/><i>A guide that keeps the plan moving.</i></h2><div className="evaActions"><b>01 <small>KNOWS YOUR SCORE</small></b><b>02 <small>SEES THE NEXT ACTION</small></b><b>03 <small>FOLLOWS THROUGH</small></b></div></div></section>
<section className="story photoRelief"><div className="storyCopy"><Icon>✓</Icon><span>THE EMOTIONAL SHIFT</span><h2>From “What now?”<br/>to “I know what’s next.”</h2></div></section>
<section className="smart"><Icon>⌘</Icon><span>SMARTCHITECTURE</span><h2>Simple on the surface.<br/><i>Powerful underneath.</i></h2><div className="flow">{['ASSESS','SCORE','ROADMAP','PORTAL','EVA','MATCH'].map(x=><b key={x}>{x}</b>)}</div></section>
<section className="security"><Icon>⌾</Icon><span>TRUST ARCHITECTURE</span><h2>Financial-grade confidence.</h2><div className="securityGrid"><div><Icon>⌁</Icon><h3>Secure access</h3><p>Private, role-based workspaces.</p></div><div><Icon>▤</Icon><h3>Protected documents</h3><p>Sensitive records handled with purpose.</p></div><div><Icon>✓</Icon><h3>Clear consent</h3><p>Authorization and activity are traceable.</p></div></div></section>
<section className="story photoSuccess"><div className="storyCopy right"><Icon>↗</Icon><span>THE OUTCOME</span><h2>Prepared changes the conversation.</h2><p>Instead of another rejection, the owner understands what changed, why it mattered and which opportunity fits.</p></div></section>
<section className="close"><Icon>✦</Icon><div className="eyebrow">EFFICIENCY ARCHITECTS</div><h2>Don’t just answer the question.</h2><h1>Build the system that<br/><i>helps businesses become fundable.</i></h1><div className="closeFlow">ASSESS → UNDERSTAND → PREPARE → MATCH → FUND</div><p>Eva + Smartchitecture™</p></section>
</main>}
