import React from 'react';
import './style.css';

const sections = [
  {n:'01',k:'THE FINDING',title:'The idea is stronger than the digital experience delivering it.',body:'“Are You Actually Fundable?” creates immediate tension. But the current experience asks visitors to learn about a consultation before they can experience the central promise: understanding how fundable they are, why, and what to do next.'},
  {n:'02',k:'WHAT IS WORKING',title:'A powerful question. A real financial consequence.',body:'The Capital Readiness Consultation addresses a genuine problem: businesses often seek capital before understanding how a funder will evaluate them. The opportunity is to make that expertise visible, tangible and interactive before the first appointment.'},
];
const scores=[['Business proposition','8/10'],['Website execution','5/10'],['Differentiation','6/10'],['Conversion potential','6/10'],['EA opportunity','9/10']];
const dims=['Business stability','Financials','Credit profile','Cash flow','Documentation','Debt capacity','Risk','Capital fit'];
export default function Page(){return <main className="ayf">
<section className="cover"><div className="eyebrow">EFFICIENCY ARCHITECTS · DIGITAL DEEP DIVE</div><div className="coverGrid"><div><h1>ARE YOU<br/><i>FUNDABLE?</i></h1><p className="lead">A digital growth evaluation for a business with a powerful question at its center.</p><div className="line"/><p className="small">CAPITAL READINESS · DIGITAL EXPERIENCE · SMARTCHITECTURE</p></div><div className="heroPhoto"><div className="photoLabel">CAPITAL<br/>READINESS</div></div></div></section>
<section className="finding"><span>EXECUTIVE FINDING</span><h2>The business proposition is compelling.<br/><i>The digital experience should make it undeniable.</i></h2><div className="scoreRow">{scores.map(([a,b])=><div className="score" key={a}><strong>{b}</strong><small>{a}</small></div>)}</div><p className="statement">The strongest position is not “we help you get funding.” It is: <b>we help you see what a funder is likely to see before you ask them for money.</b></p></section>
{sections.map(s=><section className="editorial" key={s.n}><div className="num">{s.n}</div><div><span>{s.k}</span><h2>{s.title}</h2><p>{s.body}</p></div></section>)}
<section className="split"><div className="dark"><span>THE CURRENT JOURNEY</span><h2>Information first.<br/>Insight later.</h2><div className="journey muted">VISIT <b>→</b> READ <b>→</b> LEARN ABOUT CRC <b>→</b> BOOK</div><p>The visitor has to trust the process before experiencing the value.</p></div><div className="light"><span>THE CONNECTED JOURNEY</span><h2>Let the prospect<br/><i>experience fundability.</i></h2><div className="journey">ASSESS <b>→</b> DIAGNOSE <b>→</b> PREPARE <b>→</b> MATCH <b>→</b> FUND</div><p>The assessment becomes the beginning of the relationship, not simply a lead form.</p></div></section>
<section className="scoreExperience"><div><span>THE PRODUCT MOMENT</span><h2>YOUR CAPITAL<br/>READINESS SCORE</h2><div className="bigScore">72<span>/100</span></div><h3>Promising, but not lender-ready.</h3><p>Three issues are suppressing your readiness. Your roadmap shows exactly what to address next.</p></div><div className="meter">{[['Business Stability',88],['Revenue History',82],['Documentation',64],['Credit Profile',59],['Debt Capacity',48]].map(([x,v])=><div className="m" key={x as string}><div><b>{x}</b><span>{v}</span></div><i><em style={{width:`${v}%`}}/></i></div>)}</div></section>
<section className="architecture"><span>THE INTELLECTUAL PROPERTY</span><h2>Make the methodology visible.</h2><p>Fundability becomes understandable when the evaluation is organized into a clear architecture.</p><div className="dimGrid">{dims.map((d,i)=><div className="dim" key={d}><b>0{i+1}</b><span>{d}</span></div>)}</div></section>
<section className="portal"><div className="portalIntro"><span>THE CAPITAL PORTAL</span><h2>From consultation<br/>to operating system.</h2><p>The score should not disappear after the assessment. It becomes the center of a private workspace that guides the business toward capital readiness.</p></div><div className="ui"><aside><b>AYF</b><small>OVERVIEW</small><a>Readiness</a><a>Roadmap</a><a>Documents</a><a>Opportunities</a><a>Applications</a><a>Messages</a></aside><article><div className="uiTop">Capital Readiness <span>Marcus Hospitality Group</span></div><div className="uiScore"><b>72</b><span>Capital Readiness Score</span><em>+11 points since assessment</em></div><div className="tasks"><h4>NEXT BEST ACTIONS</h4><p>Upload 2025 business tax return <b>Required</b></p><p>Connect business bank statements <b>Required</b></p><p>Verify current debt balance <b>Review</b></p></div></article></div></section>
<section className="eva"><div className="orb">EVA</div><div><span>24/7 DIGITAL ASSISTANT</span><h2>Eva turns the roadmap<br/>into action.</h2><blockquote>“Your Capital Readiness Score is 72. Three items are preventing lender-ready status. Upload your latest tax return, connect your business bank statements and verify your current debt balance.”</blockquote><p>Reminders. Document requests. Status updates. Preparation. Follow-up. One next best action at a time.</p></div></section>
<section className="smart"><span>SMARTCHITECTURE</span><h2>The prospect sees simplicity.<br/><i>The system handles complexity.</i></h2><div className="flow">{['WEBSITE','ASSESSMENT','SCORE','CRM','PORTAL','DOCUMENTS','EVA','FUNDING WORKFLOW','FOLLOW-UP'].map(x=><b key={x}>{x}</b>)}</div></section>
<section className="security"><span>TRUST ARCHITECTURE</span><h2>Financial information deserves<br/>a financial-grade experience.</h2><div className="securityGrid"><div><b>01</b><h3>Secure access</h3><p>Authenticated private workspaces and role-based permissions.</p></div><div><b>02</b><h3>Protected documents</h3><p>Purpose-built handling for sensitive business and financial records.</p></div><div><b>03</b><h3>Consent + auditability</h3><p>Clear authorization, data minimization and traceable activity.</p></div></div></section>
<section className="marcus"><span>A HUMAN JOURNEY</span><h2>Meet Marcus.</h2><p>Marcus owns a growing restaurant group. Revenue is strong, but expansion capital has been declined.</p><div className="marcusFlow"><b>BUSINESS OWNER</b><i>→</i><b>61 SCORE</b><i>→</i><b>DIAGNOSIS</b><i>→</i><b>ROADMAP</b><i>→</i><b>84 SCORE</b><i>→</i><b>CAPITAL READY</b><i>→</i><b>OPPORTUNITY</b></div><p className="result">Instead of another rejection, Marcus knows what changed, why it mattered and what opportunity now fits.</p></section>
<section className="questions"><span>DISCOVERY BEFORE PRESCRIPTION</span><h2>What we would validate next.</h2><div className="qgrid"><p>How is the CRC currently scored?</p><p>Which readiness factors most often block funding?</p><p>What happens after a client receives the consultation?</p><p>How are documents collected and reviewed today?</p><p>How are funding partners selected and matched?</p><p>Which outcomes should the system measure?</p></div></section>
<section className="close"><div className="eyebrow">EFFICIENCY ARCHITECTS</div><h2>Don’t just tell businesses<br/>whether they’re fundable.</h2><h1>Build the system that<br/><i>helps them become fundable.</i></h1><div className="closeFlow">UNCERTAIN → ASSESSED → INFORMED → PREPARED → CAPITAL READY → MATCHED → FUNDED</div><p>Eva + Smartchitecture™</p></section>
</main>}
