import assert from 'node:assert/strict'; import { readFileSync } from 'node:fs'; import { requireClientFactoryAssembly } from '../lib/modules/client-factory-assembly';
const packagePurchased='Website + Portal Starter';
const plan=requireClientFactoryAssembly({packagePurchased}); assert.equal(plan.blocked,false);
const foundationSource=readFileSync('lib/tenant-foundation.ts','utf8');
assert.match(foundationSource,/Website \+ Portal Starter' \? 'certified' : 'legacy'/);
assert.match(foundationSource,/persistAssemblyEvidenceReceipt/);
assert.match(foundationSource,/if \(assemblyMode === 'certified'\) throw err/);
console.log('EA Modular Assembly Run 5 prerequisite OK');
console.log(' - Starter provisioning now fails closed until exact module certificates exist');
console.log(' - durable evidence receipt plumbing remains present for certified assemblies');
