"use client";
import { useRef, useState, type FormEvent } from 'react';
import { opportunityTypes, budgetRanges } from '@/lib/tb3/contracts';
export default function BookingForm({manual=false,onSaved}:{manual?:boolean;onSaved?:()=>void}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
  const request=useRef<string|null>(null);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setBusy(true);const form=new FormData(event.currentTarget);request.current ||= crypto.randomUUID();
    const record={contact_name:String(form.get('name')),company_name:String(form.get('company')),contact_email:String(form.get('email')),phone:String(form.get('phone')||''),type:String(form.get('type')),budget_range:String(form.get('budget')),date_requested:String(form.get('date')||'')||null,vision_answer:String(form.get('vision')),message:String(form.get('message')||''),request_id:request.current};
    try {const res=await fetch('/api/opportunities/create'+(manual?'?manual=true':''),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});const result=await res.json();if(!res.ok||!result.ok)throw new Error(result.error||'Inquiry could not be saved.');setSaved(true);onSaved?.();}catch(err){setError(err instanceof Error?err.message:'Inquiry could not be saved. Please try again.');}finally{setBusy(false);}}
  const input='mt-2 block w-full rounded-lg border border-black/20 bg-white p-3 text-sm text-black';
  return <section id={manual?'manual-opportunity-form':'book-tarris-form'} className="scroll-mt-24 rounded-2xl border border-black/10 bg-[#F5F5F0] p-5 text-black sm:p-8"><p className="text-xs font-bold tracking-widest text-[#C41E3A]">SAME VISION. BIGGER PURPOSE.</p><h2 className="mt-3 text-3xl font-black">{manual?'Track Opportunity':'BOOK TARRIS / PARTNER WITH TB3'}</h2>{saved?<p role="status" className="mt-5 leading-7">Thank you. Your inquiry has been received. The team will review your Same Vision alignment and respond within 24 hours.</p>:<form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2">
    <label className="text-xs font-bold">Name *<input name="name" required maxLength={200} autoComplete="name" className={input}/></label><label className="text-xs font-bold">Company *<input name="company" required maxLength={200} autoComplete="organization" className={input}/></label><label className="text-xs font-bold">Email *<input name="email" type="email" required maxLength={320} autoComplete="email" className={input}/></label><label className="text-xs font-bold">Phone<input name="phone" type="tel" maxLength={60} autoComplete="tel" className={input}/></label><label className="text-xs font-bold">Type *<select name="type" required className={input}><option value="">Select type</option>{opportunityTypes.map(t=><option key={t}>{t}</option>)}</select></label><label className="text-xs font-bold">Budget<select name="budget" className={input}>{budgetRanges.map(b=><option key={b}>{b}</option>)}</select></label><label className="text-xs font-bold sm:col-span-2">Date Requested<input name="date" type="date" className={input}/></label><label className="text-xs font-bold sm:col-span-2">Vision Alignment *<span className="mt-2 block font-normal leading-6">What does Same Vision, Bigger Purpose mean to you? How does this align with Discipline, Determination, Development and Destiny?</span><textarea name="vision" required maxLength={5000} rows={4} className={input}/></label><label className="text-xs font-bold sm:col-span-2">Message<textarea name="message" maxLength={10000} rows={3} className={input}/></label>{error&&<p role="alert" className="text-sm text-red-700 sm:col-span-2">{error}</p>}<button disabled={busy} type="submit" className="rounded-lg bg-[#C41E3A] px-5 py-4 text-sm font-bold text-white sm:col-span-2">{busy?'Submitting…':'Submit Inquiry →'}</button>
  </form>}</section>;
}
