import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import AmplifiBrand from './AmplifiBrand';
import './amplifi-v3.css';

export const metadata: Metadata={title:'Amplifi | Focus on your craft.',description:'Focus on your craft. Let Amplifi handle the social media. Find relevant ideas, create premium content, review it and keep moving.'};
const preview='/api/amplifi/trial?next=%2Famplifi%2Fcreate%3Fmode%3Dcampaign';
const people=[
  {src:'/amplifi/amplifi-person-phone-v2.jpg',alt:'Professional showing Amplifi on a phone'},
  {src:'/home/ch7-consultant.jpg',alt:'Professional discussing an idea'},
  {src:'/home/ch7-healthcare.jpg',alt:'Professional focused on their craft'},
  {src:'/home/ch7-school.jpg',alt:'Community leader working with people'}
];
const posts=[
  {image:'/home/ch7-consultant.jpg',eyebrow:'PROFESSIONAL SERVICES',headline:'Your biggest competitor might be “I’ll do it later.”',caption:'Your clients do not always need more information. Sometimes they need a clear reason to move. This post turns hesitation into a next step without sounding like a sales pitch.',reason:'Timely, useful, and tied to a real customer behavior.'},
  {image:'/home/ch7-healthcare.jpg',eyebrow:'HEALTH + WELLNESS',headline:'Feeling fine is not the same as staying ahead.',caption:'A calm, confident reminder that prevention is easier than recovery. Built to educate first, then invite the right next action.',reason:'Educational content that earns attention before asking for it.'},
  {image:'/home/ch7-school.jpg',eyebrow:'COMMUNITY + NONPROFIT',headline:'The work changes lives. The story helps more people find it.',caption:'Turn a real moment from the work into a post that shows impact, builds trust, and gives supporters a reason to lean in.',reason:'Mission-led storytelling with a clear purpose.'}
];
const Icon=({type}:{type:'eva'|'idea'|'search'})=> type==='eva'?<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M9 11h30v22H22l-8 7v-7H9z"/><circle cx="18" cy="22" r="2"/><circle cx="24" cy="22" r="2"/><circle cx="30" cy="22" r="2"/></svg>:type==='idea'?<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M17 31h14M19 36h10M16 27c-3-2-5-6-5-10a13 13 0 0 1 26 0c0 4-2 8-5 10-2 2-2 3-2 4H18c0-1 0-2-2-4Z"/><path d="M24 4v4M8 10l4 3M40 10l-4 3"/></svg>:<svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="21" cy="21" r="12"/><path d="m30 30 10 10M17 21h8M21 17v8"/></svg>;

export default function Page(){return <main className="ampx-page ampx-craft">
  <nav className="ampx-nav"><AmplifiBrand/><div className="ampx-navlinks"><Link href="/amplifi/pricing">Plans</Link><Link href="/portal/login?next=%2Famplifi%2Fworkspace">Sign in</Link></div></nav>

  <section className="ampx-hero craft-hero">
    <div className="ampx-hero-copy"><span className="ampx-kicker">AMPLIFI</span><h1>Focus on your craft.<br/><em>Let Amplifi handle the social media.</em></h1><p>You have better things to do than constantly figure out what to post. Amplifi helps find relevant ideas, create polished content, organize it for approval, and keep your social media moving.</p><div className="ampx-hero-actions"><a className="ampx-primary" href={preview}>Try Amplifi Free</a></div><small>No payment. No social connection. Nothing publishes.</small></div>
    <div className="ampx-hero-media craft-group-media"><div className="craft-group-grid">{people.map((p,i)=><div key={p.src} className={i===0?'is-phone':''}><Image src={p.src} alt={p.alt} fill priority={i===0} sizes="(max-width:900px) 50vw,25vw"/></div>)}</div><div className="craft-phone-demo"><span>AMPLIFI</span><strong>“Here. It already built the post.”</strong><p>Ideas, content and approvals in one place.</p></div></div>
  </section>

  <section className="craft-pain"><span className="ampx-kicker">THE PROBLEM</span><h2>Social media keeps asking for more.</h2><p>You post today. Tomorrow it needs another idea, another caption, another graphic, another video. And it still has to feel relevant, polished, and worth someone’s attention.</p><div className="craft-demand-row"><span>What should I post?</span><span>I need another idea.</span><span>I haven’t posted this week.</span><span>I need a graphic.</span><span>What should I say?</span><span>I don’t have time for this.</span></div><h3>Meanwhile, you have actual work to do.</h3></section>

  <section className="craft-people"><div className="craft-section-head"><span className="ampx-kicker">FOUR PEOPLE. SAME PROBLEM.</span><h2>The work changes. The social media demand doesn’t.</h2><p>Different crafts. Same pressure to keep showing up online.</p></div><div className="craft-people-grid">{people.map(p=><article key={'work-'+p.src}><div className="craft-person-img"><Image src={p.src} alt={p.alt} fill sizes="(max-width:700px) 50vw,25vw"/></div><div className="craft-person-demand"><span>What should I post next?</span><b>AMPLIFI IS HANDLING IT →</b></div></article>)}</div><h3 className="craft-center-line">Your attention stays on the work that matters.</h3></section>

  <section className="craft-try craft-try-major"><div><span className="ampx-kicker">TRY AMPLIFI FREE</span><h2>See what Amplifi can do for you.</h2><p>Three simple answers are enough to start. Amplifi turns them into a real campaign preview built around your business.</p></div><div className="craft-try-card"><span>YOUR FIRST CAMPAIGN</span><h3>Three answers. One real campaign. Free.</h3><div className="craft-try-steps"><b>01</b><p>What do you do?</p><b>02</b><p>What are you trying to accomplish?</p><b>03</b><p>What do you want people to do next?</p></div><a className="ampx-primary" href={preview}>Try Amplifi Free →</a><small>No account required to start.</small></div></section>

  <section className="craft-brains"><div className="craft-section-head"><span className="ampx-kicker">THE THINKING IS BUILT IN</span><h2>Smartchitecture + Eva</h2></div><div className="craft-brain-grid"><article><span>SMARTCHITECTURE</span><h3>The thinking behind Amplifi.</h3><p>Smartchitecture connects what Amplifi knows about your business with what you are trying to accomplish.</p><ul><li>What should we focus on?</li><li>What is relevant?</li><li>What should we say?</li><li>What should we create?</li><li>What should we try next?</li></ul></article><article><span>EVA</span><h3>Your guide inside Amplifi.</h3><p>Tell Eva what you are trying to accomplish. Ask what you should post. Talk through an idea. Ask what is working and what should happen next.</p><div className="craft-eva-chat"><small>YOU</small><b>Eva, what should we talk about this week?</b><small>EVA</small><b>I found three ideas that fit your audience. Let’s start with the strongest one.</b></div></article></div><h3 className="craft-center-line">Smartchitecture does the thinking. Eva guides you through it. Amplifi helps get it done.</h3></section>

  <section className="craft-three"><span className="ampx-kicker">NO MORE BLANK SCREEN</span><h2>Bring an idea. Save an idea. Or let Amplifi find one.</h2><div className="craft-three-grid"><article><div className="craft-feature-icon"><Icon type="eva"/></div><h3>Ask Eva</h3><p>Have something in mind? Tell Eva. A simple thought can become usable content.</p></article><article><div className="craft-feature-icon"><Icon type="idea"/></div><h3>Idea Box</h3><p>Drop in a thought, event, inspiration, image, file, or link. Amplifi helps find the opportunity inside it.</p></article><article><div className="craft-feature-icon"><Icon type="search"/></div><h3>Custom Search + Build</h3><p>Tell Amplifi what to look for. It can find relevant information and turn the strongest opportunity into content.</p></article></div></section>

  <section className="craft-search"><div className="craft-search-copy"><span className="ampx-kicker">CUSTOM SEARCH + BUILD</span><h2>Tell Amplifi what to watch. It can turn what matters into a post.</h2><p>Choose a topic, issue, audience, event, or trend. Amplifi searches for relevant developments, shows you exactly what it found and why it matters, then offers a usable content angle.</p></div><div className="craft-search-ui"><small>WHAT SHOULD AMPLIFI LOOK FOR?</small><div className="craft-search-input"><span>New developments affecting small-business owners</span><b>Search + Build</b></div><div className="craft-found"><span>FOUND TODAY · RELEVANT TO YOUR AUDIENCE</span><strong>New small-business filing requirement takes effect next month.</strong><p><b>Why it matters:</b> Your audience may need to act before the deadline, making this useful and timely rather than filler.</p><small>AMPLIFI’S RECOMMENDED ANGLE</small><p>Explain the change in plain language, give people the three things to check now, and end with a simple next step.</p><button>Build This Post →</button></div></div></section>

  <section className="craft-premium craft-proof-approval"><div className="craft-section-head"><span className="ampx-kicker">YOUR APPROVAL FOLDER</span><h2>The content is the proof. You make the call.</h2><p>Amplifi can find the idea, build the finished creative, write the caption, explain why it recommends the post, and place everything here for you to approve, edit, or skip.</p></div><div className="premium-post-grid">{posts.map(post=><article className="premium-post" key={post.headline}><div className="premium-post-creative"><Image src={post.image} alt="Premium social post ready for approval" fill sizes="(max-width:800px) 100vw,33vw"/><div className="premium-post-shade"/><div className="premium-post-copy"><span>{post.eyebrow}</span><h3>{post.headline}</h3></div></div><div className="premium-post-meta"><small>AMPLIFI CAPTION</small><p>{post.caption}</p><b>WHY AMPLIFI CREATED THIS · {post.reason}</b><div className="craft-actions"><button>Approve</button><button>Edit</button><button>Skip</button></div></div></article>)}</div><div className="craft-approval-summary"><span>READY FOR APPROVAL</span><strong>3 premium posts waiting for you.</strong><p>One folder. Finished creative. Your final say.</p></div></section>

  <section className="craft-learns"><div><span className="ampx-kicker">AMPLIFI GETS SMARTER</span><h2>The more Amplifi understands, the less you have to explain.</h2><p>Amplifi remembers important context about your business, audience, goals, previous campaigns, ideas, and available results. So every conversation does not start from zero.</p></div><div className="craft-truth"><article><b>KNOWS</b><p>What you told Amplifi.</p></article><article><b>OBSERVES</b><p>What the evidence shows.</p></article><article><b>INFERS</b><p>What may be happening.</p></article><article><b>RECOMMENDS</b><p>What makes sense to try next.</p></article></div></section>

  <section className="craft-trial"><span className="ampx-kicker">10-DAY TRIAL</span><h2>Put Amplifi to work.</h2><p>Start with your free campaign. Then bring your own ideas, use the Idea Box, let Amplifi search for relevant content, create posts, and review the work in your Approval Folder.</p><div className="craft-trial-points"><span>No developer accounts.</span><span>No complicated setup.</span><span>No social-media expertise required.</span></div><a className="ampx-primary" href={preview}>Try Amplifi Free</a></section>

  <section className="ampx-final craft-final"><span className="ampx-kicker">AMPLIFI</span><h2>Focus on your craft.<br/><em>Let Amplifi handle the social media.</em></h2><a className="ampx-primary" href={preview}>Try Amplifi Free</a></section>
</main>}
