import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import AmplifiBrand from './AmplifiBrand';
import './amplifi-v3.css';
import './amplifi-story-upgrade.css';

export const metadata: Metadata={title:'Amplifi | Focus on your craft.',description:'Focus on your craft. Let Amplifi handle the social media. Find relevant ideas, create premium content, review it and keep moving.'};
const preview='/api/amplifi/trial?next=%2Famplifi%2Fcreate%3Fmode%3Dcampaign';
const people=[
 {src:'/amplifi/amplifi-person-phone-v2.jpg',label:'CREATOR / INFLUENCER',problem:'I have the audience. What should I post next?',alt:'Creator using Amplifi on a phone'},
 {src:'/home/ch7-consultant.jpg',label:'BUSINESS OWNER',problem:'I need content that helps people choose us.',alt:'Business owner meeting with clients'},
 {src:'/home/ch7-healthcare.jpg',label:'COACH / PROFESSIONAL',problem:'I know my craft. I do not have time to be a content team.',alt:'Professional focused on their work'},
 {src:'/home/ch7-school.jpg',label:'COMMUNITY LEADER',problem:'How do I turn the work we do into a story people notice?',alt:'Community leader working with people'}
];
const posts=[
 {image:'/home/ch7-consultant.jpg',eyebrow:'BUSINESS OWNER',headline:'Three questions customers ask before they choose you.',caption:'Turn the questions you already answer every week into useful content. This post gives prospective customers clarity before they ever contact you.',reason:'Uses real customer questions to create useful, decision-making content.'},
 {image:'/home/ch7-healthcare.jpg',eyebrow:'COACH / PROFESSIONAL',headline:'The small habit your clients keep overlooking.',caption:'Teach one useful idea from your expertise, make it immediately actionable, then invite people to take the next sensible step.',reason:'Shows expertise by helping first instead of leading with a sales pitch.'},
 {image:'/home/ch7-school.jpg',eyebrow:'COMMUNITY LEADER',headline:'One afternoon. Twenty-five young people. A story worth sharing.',caption:'Turn a real moment from the work into a post that shows impact, builds trust, and gives supporters a reason to lean in.',reason:'Turns real-world impact into mission-led storytelling.'}
];
const Icon=({type}:{type:'eva'|'idea'|'search'})=> type==='eva'?<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M9 11h30v22H22l-8 7v-7H9z"/><circle cx="18" cy="22" r="2"/><circle cx="24" cy="22" r="2"/><circle cx="30" cy="22" r="2"/></svg>:type==='idea'?<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M17 31h14M19 36h10M16 27c-3-2-5-6-5-10a13 13 0 0 1 26 0c0 4-2 8-5 10-2 2-2 3-2 4H18c0-1 0-2-2-4Z"/><path d="M24 4v4M8 10l4 3M40 10l-4 3"/></svg>:<svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="21" cy="21" r="12"/><path d="m30 30 10 10M17 21h8M21 17v8"/></svg>;

export default function Page(){return <main className="ampx-page ampx-craft">
<nav className="ampx-nav"><AmplifiBrand/><div className="ampx-navlinks"><Link href="/amplifi/pricing">Plans</Link><Link href="/portal/login?next=%2Famplifi%2Fworkspace">Sign in</Link></div></nav>
<section className="ampx-hero craft-hero"><div className="ampx-hero-copy"><span className="ampx-kicker">AMPLIFI</span><h1>Focus on your craft.<br/><em>Let Amplifi handle the social media.</em></h1><p>You have better things to do than constantly figure out what to post. Amplifi helps find relevant ideas, create polished content, organize it for approval, and keep your social media moving.</p><div className="ampx-hero-actions"><a className="ampx-primary" href={preview}>Try Amplifi Free</a></div><small>No payment. No social connection. Nothing publishes.</small></div><div className="ampx-hero-media craft-group-media"><div className="craft-group-grid">{people.map((p,i)=><div key={p.src} className={i===0?'is-phone':''}><Image src={p.src} alt={p.alt} fill priority={i===0} sizes="(max-width:900px) 50vw,25vw"/></div>)}</div><div className="craft-phone-demo"><span>AMPLIFI WORKSPACE</span><strong>Idea → finished post → your approval.</strong><p>Amplifi does the content work. You decide what goes out.</p></div></div></section>
<section className="craft-pain"><span className="ampx-kicker">THE PROBLEM</span><h2>Social media keeps asking for more.</h2><p>You post today. Tomorrow it needs another idea, another caption, another graphic, another video. And it still has to feel relevant, polished, and worth someone’s attention.</p><div className="craft-demand-row"><span>What should I post?</span><span>I need another idea.</span><span>I haven’t posted this week.</span><span>I need a graphic.</span><span>What should I say?</span><span>I don’t have time for this.</span></div><h3>Meanwhile, you have actual work to do.</h3></section>
<section className="craft-people"><div className="craft-section-head"><span className="ampx-kicker">DIFFERENT CRAFTS. SAME PRESSURE.</span><h2>You should recognize yourself here.</h2><p>The job changes. The demand to keep showing up online does not.</p></div><div className="craft-people-grid">{people.map(p=><article key={'work-'+p.src}><div className="craft-person-img"><Image src={p.src} alt={p.alt} fill sizes="(max-width:700px) 100vw,25vw"/><b className="craft-person-label">{p.label}</b></div><div className="craft-person-demand"><span>{p.problem}</span><b>AMPLIFI CAN HANDLE IT →</b></div></article>)}</div><h3 className="craft-center-line">Your attention stays on the work that matters.</h3></section>
<section className="craft-three"><span className="ampx-kicker">NO MORE BLANK SCREEN</span><h2>Bring an idea. Save an idea. Or let Amplifi find one.</h2><div className="craft-three-grid"><article><div className="craft-feature-icon"><Icon type="eva"/></div><h3>Ask Eva</h3><p>Have something in mind? Tell Eva. A simple thought can become usable content.</p></article><article><div className="craft-feature-icon"><Icon type="idea"/></div><h3>Idea Box</h3><p>Drop in a thought, event, inspiration, image, file, or link. Amplifi helps find the opportunity inside it.</p></article><article><div className="craft-feature-icon"><Icon type="search"/></div><h3>Custom Search + Build</h3><p>Tell Amplifi what to look for. It can find relevant information and turn the strongest opportunity into content.</p></article></div></section>
<section className="craft-search craft-search-upgraded"><div className="craft-search-copy"><span className="ampx-kicker">WATCH AMPLIFI WORK</span><h2>From something worth knowing to something worth posting.</h2><p>Instead of handing you a pile of search results, Amplifi connects the dots and moves the useful idea toward finished content.</p></div><div className="craft-search-ui"><div className="craft-flow-stage"><b>1 · SEARCH</b><p>“Find changes that affect local small-business owners.”</p></div><div className="craft-flow-arrow">↓</div><div className="craft-flow-stage"><b>2 · FOUND</b><p><strong>A new local grant application window opens Monday.</strong></p><small>WHY IT MATTERS · Your audience has a short window to act.</small></div><div className="craft-flow-arrow">↓</div><div className="craft-flow-stage is-built"><b>3 · BUILT</b><p><strong>“Local business owners: put Monday on your calendar.”</strong></p><p>Amplifi creates the visual, caption, useful details and next step.</p></div><div className="craft-flow-arrow">↓</div><div className="craft-flow-stage is-ready"><b>4 · READY FOR YOU</b><p>Finished post placed in your Approval Folder.</p><span>Approve · Edit · Skip</span></div></div></section>
<section className="craft-premium craft-proof-approval"><div className="craft-section-head"><span className="ampx-kicker">YOUR APPROVAL FOLDER</span><h2>The content is the proof. You make the call.</h2><p>Amplifi can find the idea, build the finished creative, write the caption, explain why it recommends the post, and place everything here for you to approve, edit, or skip.</p></div><div className="premium-post-grid">{posts.map(post=><article className="premium-post" key={post.headline}><div className="premium-post-creative"><Image src={post.image} alt={`${post.eyebrow} social post ready for approval`} fill sizes="(max-width:800px) 100vw,33vw"/><div className="premium-post-shade"/><div className="premium-post-copy"><span>{post.eyebrow}</span><h3>{post.headline}</h3></div></div><div className="premium-post-meta"><small>AMPLIFI CAPTION</small><p>{post.caption}</p><b>WHY AMPLIFI CREATED THIS · {post.reason}</b><div className="craft-actions"><button>Approve</button><button>Edit</button><button>Skip</button></div></div></article>)}</div><div className="craft-approval-summary"><span>READY FOR APPROVAL</span><strong>3 premium posts waiting for you.</strong><p>One folder. Finished creative. Your final say.</p></div></section>
<section className="craft-try craft-try-major craft-try-upgraded"><div><span className="ampx-kicker">YOUR FIRST CAMPAIGN IS ON US</span><h2>Give Amplifi three answers. Get something real back.</h2><p>No generic demo and no blank dashboard. Tell Amplifi what you do, what you want to accomplish, and what you want people to do next.</p><div className="craft-free-proof"><span>✦</span><strong>AMPLIFI BUILDS YOUR CAMPAIGN PREVIEW</strong><p>See the idea, messaging direction and campaign structure before creating an account.</p></div></div><div className="craft-try-card"><span>YOUR FIRST CAMPAIGN</span><h3>Three answers.<br/>One real campaign.<br/><em>Free.</em></h3><div className="craft-try-steps"><b>01</b><p>What do you do?</p><b>02</b><p>What are you trying to accomplish?</p><b>03</b><p>What do you want people to do next?</p></div><a className="ampx-primary" href={preview}>Build My Free Campaign →</a><small>No account required to start.</small></div></section>
<section className="craft-brains"><div className="craft-section-head"><span className="ampx-kicker">THE THINKING IS BUILT IN</span><h2>Smartchitecture + Eva</h2></div><div className="craft-brain-grid"><article><span>SMARTCHITECTURE</span><h3>The thinking behind Amplifi.</h3><p>Smartchitecture connects what Amplifi knows about your business with what you are trying to accomplish.</p><ul><li>What should we focus on?</li><li>What is relevant?</li><li>What should we say?</li><li>What should we create?</li><li>What should we try next?</li></ul></article><article><span>EVA</span><h3>Your guide inside Amplifi.</h3><p>Tell Eva what you are trying to accomplish. Ask what you should post. Talk through an idea. Ask what is working and what should happen next.</p><div className="craft-eva-chat"><small>YOU</small><b>Eva, what should we talk about this week?</b><small>EVA</small><b>I found three ideas that fit your audience. Let’s start with the strongest one.</b></div></article></div><h3 className="craft-center-line">Smartchitecture does the thinking. Eva guides you through it. Amplifi helps get it done.</h3></section>
<section className="craft-learns"><div><span className="ampx-kicker">AMPLIFI GETS SMARTER</span><h2>The more Amplifi understands, the less you have to explain.</h2><p>Amplifi remembers important context about your business, audience, goals, previous campaigns, ideas, and available results. So every conversation does not start from zero.</p></div><div className="craft-truth"><article><b>KNOWS</b><p>What you told Amplifi.</p></article><article><b>OBSERVES</b><p>What the evidence shows.</p></article><article><b>INFERS</b><p>What may be happening.</p></article><article><b>RECOMMENDS</b><p>What makes sense to try next.</p></article></div></section>
<section className="craft-trial"><span className="ampx-kicker">10-DAY TRIAL</span><h2>Put Amplifi to work.</h2><p>Start with your free campaign. Then bring your own ideas, use the Idea Box, let Amplifi search for relevant content, create posts, and review the work in your Approval Folder.</p><div className="craft-trial-points"><span>No developer accounts.</span><span>No complicated setup.</span><span>No social-media expertise required.</span></div><a className="ampx-primary" href={preview}>Try Amplifi Free</a></section>
<section className="ampx-final craft-final"><span className="ampx-kicker">AMPLIFI</span><h2>Focus on your craft.<br/><em>Let Amplifi handle the social media.</em></h2><a className="ampx-primary" href={preview}>Try Amplifi Free</a></section>
<footer className="craft-legal"><div><AmplifiBrand/><p>Amplifi is an Efficiency Architects product. You remain responsible for reviewing and approving content before publication.</p></div><nav aria-label="Legal"><Link href="/amplifi/terms">Terms of Service</Link><Link href="/amplifi/privacy">Privacy Policy</Link><Link href="/amplifi/acceptable-use">Acceptable Use</Link></nav><small>AI-assisted content may contain errors and should be reviewed before use. Third-party social platforms operate under their own terms and policies.</small></footer>
</main>}
