import Link from 'next/link';
import './reference.css';

const A='/assets/tarris/authentic/';
const cards=[
 ['athlete','ATHLETE','Game. Skills. Growth.\nA higher level.','LEARN MORE','03-spire-drive-horizontal.jpg'],
 ['story','STORY','The journey.\nThe mindset.\nThe why.','READ HIS STORY','verified-tarris-hoodie-front.jpg'],
 ['brand','BRAND','TB3 is bigger\nthan basketball.','EXPLORE THE BRAND','07-spire-closeup.jpg'],
 ['nil','NIL','Opportunities.\nPartnerships.\nImpact.','NIL INQUIRIES','02-alabama-signed-graphic.jpg'],
 ['community','COMMUNITY','Investing in the next\ngeneration.','SEE THE IMPACT','04-basketball-camp-community.png']
] as const;
const portal='/portal/login?next=/portal/tarris-bouie';
export default function TB3ReferenceSite(){return <main className="r3">
<header className="r3nav"><a href="#home" className="r3logo"><b>TB<span>3</span></b><em>TARRIS BOUIE</em></a><nav>{['HOME','ATHLETE','STORY','BRAND','NIL','COMMUNITY','MEDIA','MERCH','FUTURE'].map(x=><a key={x} href={'#'+x.toLowerCase()}>{x}</a>)}</nav><Link href={portal} className="r3red">ENTER TB3 HQ →</Link></header>
<section id="home" className="r3hero"><div className="r3herocopy"><small>MORE<br/>THAN<br/>A GAME</small><h1>BUILT<br/>DIFFERENT.</h1><div className="r3script">On Purpose.</div><p>STUDENT. ATHLETE. BRAND. IMPACT.</p><div className="r3actions"><a href="#media">● &nbsp; WATCH THE STORY</a><Link href={portal}>ENTER TB3 HQ &nbsp;→</Link></div></div><img className="r3heroimg" src={A+'03-spire-drive-horizontal.jpg'} alt="Tarris Bouie"/><div className="r3discipline">Discipline<br/>Determination<br/>Development<br/>Destiny<i/></div><div className="r3portrait"><img src={A+'07-spire-closeup.jpg'} alt="Tarris Bouie portrait"/><span>Tarris<br/>Bouie <b>TB3</b></span></div><div className="r3back"><img src={A+'verified-tarris-hoodie-front.jpg'} alt="Tarris Bouie"/></div><div className="r3vision">SAME<br/>VISION<br/>HIGHER<br/>PURPOSE</div></section>
<div className="r3roles"><b>𝒜</b><i/> ATHLETE <i/> STUDENT <i/> LEADER <i/> ENTREPRENEUR <i/> ROLE MODEL</div>
<section className="r3cards">{cards.map(([id,title,copy,cta,img])=><article id={id} key={id}><img src={A+img} alt={title}/><div><h2>{title}</h2><p>{copy}</p><Link href={'/portal/tarris-bouie/'+(id==='brand'?'nil-brand':id==='nil'?'opportunities':id)}>{cta} →</Link></div></article>)}</section>
<section id="media" className="r3media"><div className="r3mediatext"><small>│ MEDIA</small><h2>HIGHLIGHTS.<br/>INTERVIEWS.<br/>MORE TO COME.</h2><p>Get an inside look at Tarris on and off the court. Game highlights, interviews, training, community, and exclusive content.</p><Link className="r3red" href="/portal/tarris-bouie/media">WATCH NOW →</Link></div><Link href="/portal/tarris-bouie/media" className="r3feature"><img src={A+'09-alabama-next-chapter.png'} alt="The Journey Continues"/><b>▶</b><em>The Journey<br/>Continues</em></Link><div className="r3playlist">{['Game Highlights|3:12','Interview: The Mindset|5:24','Training Day|4:08','Community Impact|2:37'].map((x,i)=>{const [t,d]=x.split('|');return <Link href="/portal/tarris-bouie/media" key={t}><img src={A+['03-spire-drive-horizontal.jpg','07-spire-closeup.jpg','verified-tarris-hoodie-front.jpg','04-basketball-camp-community.png'][i]} alt=""/><span>{t}<small>{d}</small></span></Link>})}<Link className="r3all" href="/portal/tarris-bouie/media">VIEW ALL VIDEOS →</Link></div></section>
<section id="merch" className="r3store"><div className="r3merch"><img src={A+'verified-tarris-hoodie-front.jpg'} alt="TB3 hoodie"/><img src={A+'03-spire-drive-horizontal.jpg'} alt="TB3 merchandise"/></div><div><h2>TB3 <span>STORE</span></h2><b>WEAR THE VISION</b><p>Premium gear for a bigger purpose.<br/>Rep TB3 and be part of the journey.</p><Link className="r3red" href="/portal/tarris-bouie/store">SHOP TB3 →</Link></div><aside>HOODIES<br/>TEES<br/>HATS<br/>AND MORE</aside></section>
<section className="r3bottom"><article id="enterprise"><div><h2>ENTERPRISE</h2><p>Business. Education.<br/>Long-term opportunities.</p><Link href="/portal/tarris-bouie/opportunities">LEARN MORE →</Link></div><img src={A+'verified-tarris-hoodie-front.jpg'} alt="Enterprise"/></article><article id="future"><div><h2>THE FUTURE</h2><p>More than a player.<br/>A platform for what’s next.</p><Link href="/portal/tarris-bouie/journey">SEE THE VISION →</Link></div><img src={A+'07-spire-closeup.jpg'} alt="Future"/></article><article className="r3player"><h2>PLAYER ONE</h2><p>A student. An athlete. A brand.<br/>A platform. The next chapter<br/>starts now.</p><Link href={portal}>ENTER TB3 HQ →</Link></article></section>
<footer className="r3footer"><div className="r3logo"><b>TB<span>3</span></b><em>TARRIS BOUIE<small>MORE THAN A GAME</small></em></div><nav><a href="#home">HOME</a><a href="#story">ABOUT</a><Link href="/portal/tarris-bouie/messages">CONTACT</Link><Link href="/legal/privacy">PRIVACY</Link><Link href="/legal/terms">TERMS</Link></nav><div className="r3social">◎ 𝕏 ▶ ♪</div><div className="r3script">Different<br/>On Purpose.</div></footer>
</main>}