import type{CompositionCandidate,StudioBriefV2,StudioReview,ReviewScores}from'./schema';
import{passesFirstRenderGate}from'./schema';

export const dimensionKeys:(keyof ReviewScores)[]=['visualImpact','artifactFit','brandIntegrity','referenceMatch','hierarchy','readability','conversionClarity','technicalIntegrity'];

export function preflight(brief:StudioBriefV2){const blockers:string[]=[];if(!brief.audience.trim())blockers.push('Audience missing');if(!brief.viewingContext.trim())blockers.push('Viewing context missing');if(!brief.referenceSignals.length)blockers.push('Reference signals missing');if(!brief.targetSizes.length)blockers.push('Target sizes missing');if(!brief.assets.some(a=>a.approved&&a.kind==='logo'))blockers.push('Approved brand mark missing');if(brief.artifactType==='poster'&&!brief.assets.some(a=>a.approved&&a.kind==='photo'))blockers.push('Approved hero photography missing');if(['poster','landing-page'].includes(brief.artifactType)&&!brief.assets.some(a=>a.approved&&a.kind==='qr'))blockers.push('Approved QR missing');return{pass:blockers.length===0,blockers};}

export function chooseCandidate(candidates:CompositionCandidate[],reviews:Record<string,StudioReview>){const ranked=candidates.map(c=>({candidate:c,review:reviews[c.id],score:reviews[c.id]?Math.min(...dimensionKeys.map(k=>reviews[c.id].scores[k])):-1})).filter(x=>x.review&&!x.review.hardFailures.length).sort((a,b)=>b.score-a.score);return ranked[0]??null;}

export function applyQualityRatchet(previous:Partial<ReviewScores>|undefined,current:StudioReview){const regressions:string[]=[];for(const key of dimensionKeys){const floor=previous?.[key];if(typeof floor==='number'&&current.scores[key]<floor)regressions.push(`${key} regressed from ${floor} to ${current.scores[key]}`)}return{pass:regressions.length===0,regressions,nextFloor:Object.fromEntries(dimensionKeys.map(k=>[k,Math.max(previous?.[k]??0,current.scores[k])]))as ReviewScores};}

export function releaseDecision(brief:StudioBriefV2,review:StudioReview,previous?:Partial<ReviewScores>){const pf=preflight(brief);if(!pf.pass)return{release:false,reason:'PREFLIGHT_BLOCKED',failures:pf.blockers};const gate=passesFirstRenderGate(review,9);if(!gate)return{release:false,reason:'FIRST_RENDER_GATE_BLOCKED',failures:[...review.hardFailures,'One or more review dimensions are below 9/10']};const ratchet=applyQualityRatchet(previous,review);if(!ratchet.pass)return{release:false,reason:'QUALITY_REGRESSION',failures:ratchet.regressions};return{release:true,reason:'APPROVED',failures:[],nextFloor:ratchet.nextFloor};}

export const posterCandidateRules=['Candidates must differ structurally, not only by colors or spacing','Candidate A: subject-dominant cinematic composition','Candidate B: event-data-driven sports graphic composition','Candidate C: heritage-led collage with modern sports interruption','Do not show candidates to user until internally reviewed','Never select a candidate with a hard failure even if its average score is highest'];
