import {CreativeDirection,StudioProjectType,directions,premiumGate} from './design-system';

export type StudioAsset={id:string;kind:'logo'|'photo'|'heritage'|'qr'|'icon';url?:string;approved:boolean;label:string};
export type StudioBrief={title:string;projectType:StudioProjectType;industry?:string;keywords?:string[];facts:string[];assets:StudioAsset[];outputs:string[];requestedDirection?:CreativeDirection;audience?:string;referenceSignals?:string[];nonNegotiables?:string[]};
export type StudioPlan={direction:CreativeDirection;directionName:string;agents:string[];renderer:string;productionSteps:string[];requiredChecks:string[];status:'READY_TO_RENDER'|'BLOCKED';blockers:string[];firstRenderTarget:number;artifactContract:string[]};

export function chooseDirection(brief:StudioBrief):CreativeDirection{if(brief.requestedDirection)return brief.requestedDirection;const hay=[brief.industry,...(brief.keywords||[]),brief.title].filter(Boolean).join(' ').toLowerCase();if(/sport|golf|basketball|football|athlete|tournament/.test(hay)&&/heritage|fraternity|chapter|alumni|kappa/.test(hay))return 'sports-editorial-heritage';if(/sport|event|concert|festival|tournament/.test(hay))return 'cinematic-event';if(/heritage|fraternity|chapter|alumni|institution/.test(hay))return 'heritage-institutional';if(/executive|corporate|business|professional/.test(hay))return 'corporate-modern';return 'luxury-editorial';}
function requiredAssetKinds(direction:CreativeDirection,projectType:StudioProjectType){const base:StudioAsset['kind'][]=['logo'];if(direction==='sports-editorial-heritage')base.push('photo','heritage');if(projectType==='event-creative'||projectType==='landing-page')base.push('qr');return [...new Set(base)];}
function artifactContract(brief:StudioBrief){switch(brief.projectType){case'event-creative':return['Poster/flyer, not webpage','3-second comprehension','One dominant hero image','Event identity + date/time + price/format/location visible without scrolling','One dominant CTA with scannable QR','Graphic energy appropriate to promotion','No long-form landing-page copy'];case'landing-page':return['Narrative scroll permitted','Hero establishes value and event identity','Progressive disclosure','CTA repeated at logical decision points'];case'website':return['Multi-section narrative','Clear navigation','Responsive conversion journey'];case'portal':return['Task-first interface','Persistent orientation','Next action obvious'];default:return['Presentation hierarchy','One idea per visual beat','Executive readability'];}}
export function buildStudioPlan(brief:StudioBrief):StudioPlan{const direction=chooseDirection(brief),required=requiredAssetKinds(direction,brief.projectType),blockers:string[]=[];for(const kind of required){if(!brief.assets.some(a=>a.kind===kind&&a.approved))blockers.push(`Missing approved ${kind} asset`)}if(!brief.facts.length)blockers.push('No verified facts supplied');if(!brief.outputs.length)blockers.push('No output formats supplied');if(!brief.audience)blockers.push('Audience not defined');if(!brief.referenceSignals?.length)blockers.push('Reference/style signals not defined');return{direction,directionName:directions[direction].name,agents:['Creative Director','Brand Guardian','Production','Visual QA','Conversion'],renderer:'EA Design Studio Orchestrator',productionSteps:['Classify artifact before styling','Extract reference signals and audience expectations','Lock verified facts and non-negotiables','Lock approved assets and subject requirements','Create three internal composition candidates','Creative Director selects strongest candidate','Brand Guardian rejects identity/subject violations','Render exact target dimensions','Visual QA inspects actual render','Conversion agent runs 3-second comprehension test','Internally revise until score >=9.0','Deploy only approved render','Verify live route matches approved render'],requiredChecks:premiumGate.map(g=>g.label),status:blockers.length?'BLOCKED':'READY_TO_RENDER',blockers,firstRenderTarget:9,artifactContract:artifactContract(brief)};}

export type RenderEvidence={approvedAssetIds:string[];hasPrimaryImage:boolean;hasHeritageImage:boolean;hasRequiredQr:boolean;overflowCount:number;collisionCount:number;brokenImageCount:number;contrastFailures:number;mobileReviewed:boolean;desktopReviewed:boolean;printReviewed:boolean;purposeClear:boolean;creativeScore:number;brandScore:number;artifactClassCorrect?:boolean;threeSecondComprehension?:boolean;referenceMatchScore?:number;subjectRequirementsMet?:boolean;liveVerified?:boolean};
export function evaluatePremiumGate(brief:StudioBrief,e:RenderEvidence){const direction=chooseDirection(brief),failures:string[]=[];if(brief.assets.filter(a=>a.approved).some(a=>!e.approvedAssetIds.includes(a.id)))failures.push('Not all approved assets are represented in the render');if(direction==='sports-editorial-heritage'&&!e.hasPrimaryImage)failures.push('Primary sports photography missing');if(direction==='sports-editorial-heritage'&&!e.hasHeritageImage)failures.push('Heritage imagery missing');if((brief.projectType==='event-creative'||brief.projectType==='landing-page')&&!e.hasRequiredQr)failures.push('Required QR code missing');if(e.overflowCount||e.collisionCount)failures.push('Clipping, overflow or collisions detected');if(e.brokenImageCount)failures.push('Broken images detected');if(e.contrastFailures)failures.push('Contrast failures detected');if(!(e.mobileReviewed&&e.desktopReviewed&&e.printReviewed))failures.push('All target formats have not been visually reviewed');if(!e.purposeClear)failures.push('Purpose or next action is unclear');if(e.artifactClassCorrect===false)failures.push('Wrong artifact class: output behaves like a different medium');if(e.threeSecondComprehension===false)failures.push('Fails 3-second comprehension test');if((e.referenceMatchScore??10)<9)failures.push('Reference/style match below 9/10');if(e.subjectRequirementsMet===false)failures.push('Subject/representation requirements not met');if(e.creativeScore<9)failures.push('Creative score below first-render threshold (9/10)');if(e.brandScore<9)failures.push('Brand integrity score below threshold (9/10)');if(e.liveVerified===false)failures.push('Live route does not match approved render');return{pass:failures.length===0,status:failures.length?'BLOCKED':'APPROVED',failures,creativeScore:e.creativeScore,brandScore:e.brandScore};}
