import { notFound } from 'next/navigation';
import { getProposalByProposalId } from '@/lib/airtable';
import { proposalDeposit } from '@/lib/proposal-deposit';
import PaymentConfirmationEmail from './PaymentConfirmationEmail';

export const dynamic='force-dynamic';
const NAVY='#17233B'; const GOLD='#C9A844'; const CREAM='#F6F4EF';
function fmt(n:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:0}).format(n);}

export default async function ProjectSecuredPage({params,searchParams}:{params:Promise<{proposalId:string}>;searchParams:Promise<{stage?:string;session_id?:string}>}){
 const {proposalId}=await params;const {stage,session_id}=await searchParams;const proposal=await getProposalByProposalId(proposalId);if(!proposal||proposal.recommendedProjectType!=='Quick Quote')notFound();
 const deposit=Math.min(Math.max(proposal.rawFee||proposalDeposit(proposal.recommendedFee),0),proposal.recommendedFee);const final=stage==='final';const paid=final?proposal.recommendedFee:deposit;const balance=final?0:Math.max(0,proposal.recommendedFee-deposit);
 const next=[['01','Confirmation','Your payment and project agreement are recorded.'],['02','Project Setup','We organize the information, access and assets needed for your build.'],['03','Discovery','EA confirms priorities, content and the client journey before production.'],['04','Build Begins','Your project moves into the agreed production timeline.']];
 return <main className="min-h-screen px-3 py-4 sm:px-6 sm:py-8" style={{backgroundColor:CREAM,color:NAVY}}><div className="mx-auto max-w-3xl overflow-hidden rounded-[32px] border border-[#E5E0D5] bg-white shadow-[0_20px_70px_rgba(23,35,59,.10)]">
 <header className="relative overflow-hidden px-6 py-8 text-white sm:px-10 sm:py-10" style={{backgroundColor:NAVY}}><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full border border-white/10"/><div className="relative"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full border border-white/25 text-xs font-black">EA</div><span className="text-[10px] font-black uppercase tracking-[.18em] text-white/80">Efficiency Architects</span></div><span className="rounded-full border border-white/15 px-3 py-2 text-[10px] font-bold uppercase tracking-[.14em] text-white/60">Project Secured</span></div><div className="mt-9 flex h-14 w-14 items-center justify-center rounded-full text-2xl font-black" style={{backgroundColor:GOLD,color:NAVY}}>✓</div><p className="mt-5 text-xs font-black uppercase tracking-[.2em]" style={{color:GOLD}}>{final?'Payment complete':'You’re officially underway'}</p><h1 className="mt-3 text-4xl font-black leading-tight">Your project is secured.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/65">Thank you, {proposal.contactName}. {proposal.businessName} is moving from agreement into project setup.</p></div></header>
 <section className="border-b border-[#ECE8DF] bg-[#FAF9F6] px-6 py-6 sm:px-10"><div className="grid grid-cols-3 gap-3 text-center"><div><p className="text-[9px] font-black uppercase tracking-wider text-neutral-400">Received</p><p className="mt-1 text-lg font-black" style={{color:GOLD}}>{fmt(paid)}</p></div><div className="border-x border-[#E4DED2]"><p className="text-[9px] font-black uppercase tracking-wider text-neutral-400">Project</p><p className="mt-1 text-lg font-black">{fmt(proposal.recommendedFee)}</p></div><div><p className="text-[9px] font-black uppercase tracking-wider text-neutral-400">Balance</p><p className="mt-1 text-lg font-black">{fmt(balance)}</p></div></div><PaymentConfirmationEmail proposalId={proposalId} sessionId={session_id}/></section>
 <section className="px-6 py-8 sm:px-10"><p className="text-xs font-black uppercase tracking-[.2em]" style={{color:GOLD}}>What happens now</p><h2 className="mt-2 text-2xl font-black">No guessing about the next step.</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{next.map(([n,title,text])=><div key={n} className="rounded-[22px] border border-[#E8E3D9] bg-[#FAF9F6] p-5"><div className="text-xl font-black text-[#D8D0C0]">{n}</div><h3 className="mt-2 text-sm font-black">{title}</h3><p className="mt-2 text-xs leading-5 text-neutral-500">{text}</p></div>)}</div></section>
 <section className="mx-6 mb-8 rounded-[26px] p-6 text-white sm:mx-10 sm:p-8" style={{backgroundColor:NAVY}}><p className="text-xs font-black uppercase tracking-[.18em]" style={{color:GOLD}}>Your next action</p><h2 className="mt-3 text-xl font-black">Watch for your project setup instructions.</h2><p className="mt-3 text-sm leading-6 text-white/65">EA will use the project information already captured and guide you through anything else needed for production. Your project is now in the setup queue.</p></section>
 <footer className="border-t border-[#ECE8DF] px-6 py-6 text-center text-[10px] font-bold uppercase tracking-[.15em] text-neutral-400">Efficiency Architects · From decision to delivery.</footer></div></main>;
}
