'use client';
import { useEffect, useState } from 'react';
import type { AmandaCourseProgress } from '@/lib/amanda-catherine/progress-store';
import { AMANDA_COURSES } from '@/lib/amanda-catherine/config';
type Row = AmandaCourseProgress & { evidenceVersion: string };
export default function CertificationQueue() {
  const [rows, setRows] = useState<Row[]>([]); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { const res = await fetch('/api/portal/amanda/certifications'); const data = await res.json(); if (!res.ok) setStatus(data.error); else setRows(data.rows); }
  useEffect(() => { let active = true; void fetch('/api/portal/amanda/certifications').then(async res => ({ ok: res.ok, data: await res.json() })).then(({ ok, data }) => { if (active) { if (ok) setRows(data.rows); else setStatus(data.error); } }).catch(() => { if (active) setStatus('Unable to load certification reviews.'); }); return () => { active = false; }; }, []);
  async function save(row: Row, action: string, fields: Record<string, unknown>) {
    setBusy(true); setStatus('');
    try { const res = await fetch('/api/portal/amanda/certifications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: row.email, courseId: row.courseId, action, evidenceVersion: row.evidenceVersion, ...fields }) }); const data = await res.json(); setStatus(res.ok ? 'Review saved.' : data.error); if (res.ok) await load(); } catch { setStatus('Unable to save review.'); } finally { setBusy(false); }
  }
  return <section><h2>Certification review queue</h2><p>Review the case study, quiz and practical evidence. Final certification requires your approval.</p><p role="status">{status}</p>{rows.map(row => <article className="ac-card" key={`${row.email}:${row.courseId}`}><h3>{AMANDA_COURSES.find(course => course.id === row.courseId)?.title}</h3><p>{row.email}</p><form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); void save(row, 'training-date', { trainingDate: fields.get('trainingDate') }); }}><label>Class/training date<input type="date" name="trainingDate" required defaultValue={row.trainingDate} /></label><button disabled={busy}>Save class/training date</button></form>
    {row.evidence ? <><p><a href={row.evidence.caseStudyUrl} target="_blank" rel="noopener noreferrer">Review case study</a></p><p><a href={row.evidence.quizEvidenceUrl} target="_blank" rel="noopener noreferrer">Review quiz result</a></p><p><a href={row.evidence.practicalEvidenceUrl} target="_blank" rel="noopener noreferrer">Review practical evidence</a></p><p>{row.evidence.practicalMedia ? row.evidence.clientConsent ? 'Client consent confirmed.' : 'Client consent missing.' : 'Practical demonstration evidence.'}</p><form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); void save(row, 'approve', { quizPassed: fields.get('quizPassed') === 'on' }); }}><label><input name="quizPassed" type="checkbox" required /> I reviewed the submitted evidence and verified that the quiz was passed.</label><button disabled={busy || Boolean(row.certificateApprovedBy)}>Approve final certification</button></form></> : <p>Awaiting case study, quiz and practical evidence.</p>}{row.certificateApprovedBy ? <p>Approved by {row.certificateApprovedBy} on {row.certificateIssuedAt}.</p> : null}</article>)}</section>;
}
