import Link from 'next/link';
import { listPortalFormSubmissions } from '@/lib/portal-forms/store';
import { amandaApplicationRoute } from '@/lib/amanda-catherine/application-routing';
const actions=[['Appointments / Jane','appointments'],['AesthetiKine Academy','academy'],['Practitioner Starter Kit','practitioner-kit'],['LIFELINE','lifeline'],['Empower Art Collective','empower-art'],['Founder Advisory','advisory'],['Founder Clarity','clarity'],['Speaking & Media','speaking'],['The Entrepreneurial Artist','book'],['RIMAN Canada','riman'],['Reviews & Testimonials','reviews'],['Update Website','updates'],['Ask Eva','eva']] as const;
export const metadata={title:'Amanda Catherine · Owner Portal V2'};
export default async function Page(){
  const applications=(await listPortalFormSubmissions('amanda-catherine',{kind:'application'}))
    .filter((item)=>['founder-advisory','speaking-media','lifeline-media-guest','partner-vendor-application'].includes(String(item.payload?.formId)))
    .filter((item)=>item.payload?.formId!=='partner-vendor-application'||item.payload?.program==='lifeline');
  const active=applications.filter((item)=>item.status==='submitted'||item.status==='reviewed');
  const queueCounts=new Map<string,{label:string;href:string;count:number}>();
  for(const item of active){const route=amandaApplicationRoute(item.payload?.formId,item.payload?.program);const current=queueCounts.get(route.queueHref);queueCounts.set(route.queueHref,{label:route.queueLabel,href:route.queueHref,count:(current?.count||0)+1});}
  return <div className="ac-dashboard"><header className="ac-topbar"><div><small>AESTHETIKINE STUDIO LAB · OWNER PORTAL</small><h1>Welcome, Amanda.</h1><p>Your care, academy, founder work, media and creative business in one calm place.</p></div><div className="ac-status">Studio Lab · V2</div></header><section className="ac-hero"><div className="ac-hero-copy"><span className="ac-kicker">AESTHETIKINE STUDIO LAB</span><h2>Make space for the work that matters.</h2><p>The public experience and owner portal now share the same business map.</p></div><div className="ac-hero-art"><span>restore · learn · create</span></div></section><section><div className="ac-section-title"><div><span>APPLICATION ACTIVITY</span><h2>Requests needing attention</h2></div><p>{active.length} active</p></div>{active.length?<div className="ac-actions">{Array.from(queueCounts.values()).map((queue)=><Link href={queue.href} key={queue.href}>{queue.label}<b>{queue.count} active →</b></Link>)}</div>:<article className="ac-card"><span className="ac-eyebrow">ALL CAUGHT UP</span><h3>No active applications.</h3><p>New Founder Advisory, Speaking and LIFELINE requests will appear here automatically.</p></article>}</section><section><div className="ac-section-title"><div><span>OPERATE</span><h2>Quick Actions</h2></div><p>Public offerings mirrored inside the portal.</p></div><div className="ac-actions">{actions.map(([label,slug])=><Link href={`/portal/amanda-catherine/owner/${slug}`} key={slug}>{label}<b>↗</b></Link>)}</div></section><section className="ac-grid-two"><article className="ac-card"><span className="ac-eyebrow">RESTORE</span><h3>Appointments & Jane</h3><p>Clinical booking stays connected to Jane rather than creating a duplicate calendar.</p><Link href="/portal/amanda-catherine/owner/appointments">Manage pathway →</Link></article><article className="ac-card ac-studio"><span className="ac-eyebrow">LEARN + CREATE</span><h3>One operating map.</h3><p>Academy, Practitioner Starter Kit, LIFELINE, Empower Art Collective, Founder Advisory, Founder Clarity, Speaking, The Entrepreneurial Artist, RIMAN and Reviews now have explicit portal destinations.</p></article></section></div>}
